// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileManager manages file-based document indexing with automatic parsing and chunking
 */
export class FileManager {

    /** Creates a new FileManager instance. */
    constructor($$source: Partial<FileManager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileManager instance from a string or object.
     */
    static createFrom($$source: any = {}): FileManager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileManager($$parsedSource as Partial<FileManager>);
    }
}

/**
 * Indexer is an Eino-compatible indexer that wraps chromem.Collection.
 * It implements the indexer.Indexer interface from Eino.
 */
export class Indexer {

    /** Creates a new Indexer instance. */
    constructor($$source: Partial<Indexer> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Indexer instance from a string or object.
     */
    static createFrom($$source: any = {}): Indexer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Indexer($$parsedSource as Partial<Indexer>);
    }
}

/**
 * Retriever is an Eino-compatible retriever that wraps chromem.Collection.
 * It implements the retriever.Retriever interface from Eino.
 */
export class Retriever {

    /** Creates a new Retriever instance. */
    constructor($$source: Partial<Retriever> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Retriever instance from a string or object.
     */
    static createFrom($$source: any = {}): Retriever {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Retriever($$parsedSource as Partial<Retriever>);
    }
}
