version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml

vars:
  APP_NAME: "veridium"
  BIN_DIR: "bin"
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'
  PKG_CONFIG_PATH: "{{.ROOT_DIR}}/go-whisper/build/install/lib/pkgconfig"

tasks:
  build:
    summary: Builds the application
    cmds:
      - task: "{{OS}}:build"

  package:
    summary: Packages a production build of the application
    cmds:
      - task: "{{OS}}:package"

  run:
    summary: Runs the application
    cmds:
      - task: "{{OS}}:run"

  dev:
    summary: Runs the application in development mode
    env:
      PKG_CONFIG_PATH: "{{.PKG_CONFIG_PATH}}"
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}

