// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChatCompletionTool represents an OpenAI-compatible tool definition
 */
export class ChatCompletionTool {
    "type": string;
    "function": FunctionDefinition;

    /** Creates a new ChatCompletionTool instance. */
    constructor($$source: Partial<ChatCompletionTool> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            this["function"] = (new FunctionDefinition());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatCompletionTool instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatCompletionTool {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("function" in $$parsedSource) {
            $$parsedSource["function"] = $$createField1_0($$parsedSource["function"]);
        }
        return new ChatCompletionTool($$parsedSource as Partial<ChatCompletionTool>);
    }
}

/**
 * FunctionDefinition represents a function definition for OpenAI
 */
export class FunctionDefinition {
    "name": string;
    "description": string;
    "parameters": { [_: string]: any };

    /** Creates a new FunctionDefinition instance. */
    constructor($$source: Partial<FunctionDefinition> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("parameters" in $$source)) {
            this["parameters"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FunctionDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): FunctionDefinition {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parameters" in $$parsedSource) {
            $$parsedSource["parameters"] = $$createField2_0($$parsedSource["parameters"]);
        }
        return new FunctionDefinition($$parsedSource as Partial<FunctionDefinition>);
    }
}

// Private type creation functions
const $$createType0 = FunctionDefinition.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
