// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileProcessorService is the Wails-exposed service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./internal/services/models.js";

/**
 * ProcessFileForStorage processes a file and saves to database
 * This is called from frontend after file upload
 */
export function ProcessFileForStorage(filePath: string, filename: string, fileType: string, userID: string, enableRAG: boolean): $CancellablePromise<services$0.ProcessFileResponse | null> {
    return $Call.ByID(4059865018, filePath, filename, fileType, userID, enableRAG).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = services$0.ProcessFileResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
