// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileProcessorService is the Wails-exposed service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./internal/services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ProcessFileFromPath processes a file from absolute path (e.g., from file dialog)
 * It copies the file to local storage and processes it for RAG
 * Returns the processed file response with the relative URL for frontend display
 */
export function ProcessFileFromPath(absolutePath: string, userID: string): $CancellablePromise<$models.ProcessFileFromPathResponse | null> {
    return $Call.ByID(1128345069, absolutePath, userID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetLLMProvider sets the LLM provider for OCR text cleanup
 */
export function SetLLMProvider(provider: services$0.LLMProvider): $CancellablePromise<void> {
    return $Call.ByID(3800136077, provider);
}

// Private type creation functions
const $$createType0 = $models.ProcessFileFromPathResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
