// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileProcessorService is the Wails-exposed service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fantasy$0 from "./fantasy/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ProcessFileFromPath processes a file from absolute path (e.g., from file dialog)
 * It copies the file to local storage and processes it for RAG
 * Returns the processed file response with the relative URL for frontend display
 */
export function ProcessFileFromPath(absolutePath: string): $CancellablePromise<$models.ProcessFileFromPathResponse | null> {
    return $Call.ByID(1128345069, absolutePath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveFiles deletes multiple files and their associated data
 * This replaces the complex frontend logic with a robust backend implementation
 */
export function RemoveFiles(ids: string[]): $CancellablePromise<void> {
    return $Call.ByID(395327522, ids);
}

/**
 * SetLanguageModel sets the language model for OCR/transcript cleanup
 */
export function SetLanguageModel(model: fantasy$0.LanguageModel): $CancellablePromise<void> {
    return $Call.ByID(3608364688, model);
}

// Private type creation functions
const $$createType0 = $models.ProcessFileFromPathResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
