// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoadFileService provides file loading functionality as a Wails service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadFile loads a file and returns a FileDocument with markdown content
 * @param {string} filePath
 * @param {$models.FileMetadata | null} fileMetadata
 * @returns {$CancellablePromise<$models.FileDocument | null>}
 */
export function LoadFile(filePath, fileMetadata) {
    return $Call.ByID(1593155773, filePath, fileMetadata).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.FileDocument.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
