// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProcessFileFromPathResponse represents the result of processing a file from absolute path
 */
export class ProcessFileFromPathResponse {
    "fileId": string;
    "documentId": string;
    "chunkIds"?: string[];
    "globalFileId"?: string;
    "processing"?: boolean;

    /**
     * URL for frontend to display (e.g., /files/uploads/123-file.pdf)
     */
    "relativeUrl": string;

    /**
     * Original filename
     */
    "filename": string;

    /** Creates a new ProcessFileFromPathResponse instance. */
    constructor($$source: Partial<ProcessFileFromPathResponse> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }
        if (!("relativeUrl" in $$source)) {
            this["relativeUrl"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessFileFromPathResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessFileFromPathResponse {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chunkIds" in $$parsedSource) {
            $$parsedSource["chunkIds"] = $$createField2_0($$parsedSource["chunkIds"]);
        }
        return new ProcessFileFromPathResponse($$parsedSource as Partial<ProcessFileFromPathResponse>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
