// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NodeBufferService provides Node.js Buffer equivalents as a Wails service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Alloc creates a zero-filled Buffer of the specified size
 */
export function Alloc(size: number): $CancellablePromise<string> {
    return $Call.ByID(3633356852, size);
}

/**
 * AllocUnsafe creates a Buffer of the specified size without zeroing
 */
export function AllocUnsafe(size: number): $CancellablePromise<string> {
    return $Call.ByID(3965427970, size);
}

/**
 * ByteLength returns the byte length of the input
 */
export function ByteLength(data: any, ...encoding: string[]): $CancellablePromise<number> {
    return $Call.ByID(3510009309, data, encoding);
}

/**
 * Compare compares two Buffers
 */
export function Compare(buf1: string, buf2: string): $CancellablePromise<number> {
    return $Call.ByID(590320510, buf1, buf2);
}

/**
 * Concat concatenates multiple Buffers
 */
export function Concat(buffers: string[], ...totalLength: number[]): $CancellablePromise<string> {
    return $Call.ByID(1974798447, buffers, totalLength);
}

/**
 * Contains checks if the Buffer contains the specified value
 */
export function Contains(buffer: string, value: string, ...byteOffset: number[]): $CancellablePromise<boolean> {
    return $Call.ByID(3849212598, buffer, value, byteOffset);
}

/**
 * Copy copies data from one Buffer to another
 */
export function Copy(source: string, target: string, ...targetStart: number[]): $CancellablePromise<number> {
    return $Call.ByID(1842985262, source, target, targetStart);
}

/**
 * Equals compares two Buffers
 */
export function Equals(buf1: string, buf2: string): $CancellablePromise<boolean> {
    return $Call.ByID(2802761314, buf1, buf2);
}

/**
 * Fill fills the Buffer with specified value
 */
export function Fill(buffer: string, value: string, ...offsetAndEnd: number[]): $CancellablePromise<string> {
    return $Call.ByID(4033988870, buffer, value, offsetAndEnd);
}

/**
 * From creates a Buffer from various input types
 */
export function From(data: any, ...encoding: string[]): $CancellablePromise<string> {
    return $Call.ByID(433692211, data, encoding);
}

/**
 * FromBase64 creates a Buffer from base64 string
 */
export function FromBase64(b64Str: string): $CancellablePromise<string> {
    return $Call.ByID(529342244, b64Str);
}

/**
 * FromHex creates a Buffer from hex string
 */
export function FromHex(hexStr: string): $CancellablePromise<string> {
    return $Call.ByID(2204815132, hexStr);
}

/**
 * IndexOf finds the index of the specified value
 */
export function IndexOf(buffer: string, value: string, ...byteOffset: number[]): $CancellablePromise<number> {
    return $Call.ByID(717599336, buffer, value, byteOffset);
}

/**
 * IsBuffer checks if the given value is a Buffer
 */
export function IsBuffer(obj: any): $CancellablePromise<boolean> {
    return $Call.ByID(148391129, obj);
}

/**
 * LastIndexOf finds the last index of the specified value
 */
export function LastIndexOf(buffer: string, value: string, ...byteOffset: number[]): $CancellablePromise<number> {
    return $Call.ByID(2098180008, buffer, value, byteOffset);
}

/**
 * Length returns the length of the Buffer
 */
export function Length(buffer: string): $CancellablePromise<number> {
    return $Call.ByID(4039503343, buffer);
}

/**
 * Get constants
 */
export function MaxLength(): $CancellablePromise<number> {
    return $Call.ByID(527675159);
}

export function MaxStringLength(): $CancellablePromise<number> {
    return $Call.ByID(2826415158);
}

/**
 * New creates a new Buffer with the given size
 */
export function New(size: number): $CancellablePromise<string> {
    return $Call.ByID(198832607, size);
}

/**
 * ReadInt8 reads a signed 8-bit integer
 */
export function ReadInt8(buffer: string, ...offset: number[]): $CancellablePromise<number> {
    return $Call.ByID(1069291868, buffer, offset);
}

/**
 * ReadUInt8 reads an unsigned 8-bit integer
 */
export function ReadUInt8(buffer: string, ...offset: number[]): $CancellablePromise<number> {
    return $Call.ByID(2123052793, buffer, offset);
}

/**
 * Slice returns a slice of the Buffer
 */
export function Slice(buffer: string, ...startAndEnd: number[]): $CancellablePromise<string> {
    return $Call.ByID(2821073695, buffer, startAndEnd);
}

/**
 * ToBase64 converts the Buffer to base64 string
 */
export function ToBase64(buffer: string): $CancellablePromise<string> {
    return $Call.ByID(2765870149, buffer);
}

/**
 * ToHex converts the Buffer to hex string
 */
export function ToHex(buffer: string): $CancellablePromise<string> {
    return $Call.ByID(2968580291, buffer);
}

/**
 * ToString converts the Buffer to a string
 */
export function ToString(buffer: string, ...encoding: string[]): $CancellablePromise<string> {
    return $Call.ByID(4063163987, buffer, encoding);
}

/**
 * WriteInt8 writes a signed 8-bit integer
 */
export function WriteInt8(buffer: string, value: number, ...offset: number[]): $CancellablePromise<string> {
    return $Call.ByID(1947367001, buffer, value, offset);
}

/**
 * WriteUInt8 writes an unsigned 8-bit integer
 */
export function WriteUInt8(buffer: string, value: number, ...offset: number[]): $CancellablePromise<string> {
    return $Call.ByID(3669897186, buffer, value, offset);
}
