// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NodeFsService provides Node.js fs module equivalents as a Wails service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AccessSync checks file access permissions
 */
export function AccessSync(path: string, mode: number): $CancellablePromise<void> {
    return $Call.ByID(2383118607, path, mode);
}

/**
 * AppendFileSync appends data to a file
 */
export function AppendFileSync(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2177323667, path, content);
}

/**
 * ChmodSync changes file permissions
 */
export function ChmodSync(path: string, mode: number): $CancellablePromise<void> {
    return $Call.ByID(273346064, path, mode);
}

/**
 * CopyFileSync copies a file
 */
export function CopyFileSync(src: string, dest: string): $CancellablePromise<void> {
    return $Call.ByID(546051302, src, dest);
}

/**
 * FileExistsSync checks if a file exists synchronously
 */
export function FileExistsSync(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(4018068639, path);
}

/**
 * MkdirSync creates a directory synchronously
 */
export function MkdirSync(path: string): $CancellablePromise<void> {
    return $Call.ByID(3120110990, path);
}

/**
 * MkdtempSync creates a temporary directory synchronously
 */
export function MkdtempSync(prefix: string): $CancellablePromise<string> {
    return $Call.ByID(3206413067, prefix);
}

/**
 * ReadDirSync reads directory contents synchronously
 */
export function ReadDirSync(path: string): $CancellablePromise<string[]> {
    return $Call.ByID(258110454, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ReadFile reads a file (synchronously in Go)
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(3951765268, path);
}

/**
 * ReadFileSync reads a file synchronously and returns as string
 */
export function ReadFileSync(path: string): $CancellablePromise<string> {
    return $Call.ByID(3743425911, path);
}

/**
 * RenameSync renames a file
 */
export function RenameSync(oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(2540010839, oldPath, newPath);
}

/**
 * RmSync removes a file or directory recursively
 */
export function RmSync(path: string): $CancellablePromise<void> {
    return $Call.ByID(2073427864, path);
}

/**
 * StatSync gets file stats synchronously
 */
export function StatSync(path: string): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(3367305179, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TruncateSync truncates a file to specified length
 */
export function TruncateSync(path: string, length: number): $CancellablePromise<void> {
    return $Call.ByID(3423124147, path, length);
}

/**
 * UnlinkSync removes a file
 */
export function UnlinkSync(path: string): $CancellablePromise<void> {
    return $Call.ByID(1800418402, path);
}

/**
 * WriteFile writes data to a file
 */
export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3047880915, path, content);
}

/**
 * WriteFileSync writes data to a file synchronously
 */
export function WriteFileSync(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3432024964, path, content);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
