// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TempFileService 安全存储临时文件工具类
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Cleanup 安全清理临时资源
 */
export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(4147283335);
}

/**
 * WriteTempFile 将字节数据写入临时文件
 */
export function WriteTempFile(data: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(3693206344, data, name);
}
