// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ToolsEngineService provides tools engineering capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExecuteTool executes a tool
 */
export function ExecuteTool(request: $models.ExecuteToolRequest): $CancellablePromise<$models.ExecuteToolResponse> {
    return $Call.ByID(3922452209, request).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GenerateTools generates tools for chat completion
 */
export function GenerateTools(request: $models.GenerateToolsRequest): $CancellablePromise<$models.GenerateToolsResponse> {
    return $Call.ByID(863250022, request).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAvailableTools returns all available tool IDs
 */
export function GetAvailableTools(): $CancellablePromise<$models.GetAvailableToolsResponse> {
    return $Call.ByID(2777565350).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetToolStats returns statistics about registered tools
 */
export function GetToolStats(): $CancellablePromise<$models.GetToolStatsResponse> {
    return $Call.ByID(2142109157).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * HasTool checks if a tool exists
 */
export function HasTool(request: $models.HasToolRequest): $CancellablePromise<$models.HasToolResponse> {
    return $Call.ByID(4136162218, request).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExecuteToolResponse.createFrom;
const $$createType1 = $models.GenerateToolsResponse.createFrom;
const $$createType2 = $models.GetAvailableToolsResponse.createFrom;
const $$createType3 = $models.GetToolStatsResponse.createFrom;
const $$createType4 = $models.HasToolResponse.createFrom;
