// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ZipService provides ZIP file extraction functionality as a Wails service
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExtractFiles extracts files from a ZIP archive based on a filter pattern
 * @param {string} zipPath
 * @param {string} filterPattern
 * @returns {$CancellablePromise<$models.ExtractedFile[]>}
 */
export function ExtractFiles(zipPath, filterPattern) {
    return $Call.ByID(2055606318, zipPath, filterPattern).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ExtractedFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
