// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Message represents a message in a prompt.
 */
export class Message {
    "role": MessageRole;
    "content": MessagePart[];
    "provider_options": ProviderOptions;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("role" in $$source)) {
            this["role"] = MessageRole.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = [];
        }
        if (!("provider_options" in $$source)) {
            this["provider_options"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField1_0($$parsedSource["content"]);
        }
        if ("provider_options" in $$parsedSource) {
            $$parsedSource["provider_options"] = $$createField2_0($$parsedSource["provider_options"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * MessagePart represents a part of a message content.
 */
export type MessagePart = any;

/**
 * MessageRole represents the role of a message.
 */
export enum MessageRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * MessageRoleSystem represents a system message.
     */
    MessageRoleSystem = "system",

    /**
     * MessageRoleUser represents a user message.
     */
    MessageRoleUser = "user",

    /**
     * MessageRoleAssistant represents an assistant message.
     */
    MessageRoleAssistant = "assistant",

    /**
     * MessageRoleTool represents a tool message.
     */
    MessageRoleTool = "tool",
};

/**
 * ProviderOptions represents additional provider-specific options.
 * Options are additional input to the provider. They are passed through
 * to the provider from the AI SDK and enable provider-specific functionality
 * that can be fully encapsulated in the provider.
 * 
 * This enables us to quickly ship provider-specific functionality
 * without affecting the core AI SDK.
 * 
 * The outer map is keyed by the provider name, and the inner
 * map is keyed by the provider-specific option key.
 * 
 * Example:
 * 
 * 	{
 * 	  "anthropic": {
 * 	    "cacheControl": { "type": "ephemeral" }
 * 	  }
 * 	}
 */
export type ProviderOptions = { [_: string]: ProviderOptionsData };

/**
 * ProviderOptionsData is an interface for provider-specific options data.
 * All implementations MUST also implement encoding/json.Marshaler and
 * encoding/json.Unmarshaler interfaces to ensure proper JSON serialization
 * with the provider registry system.
 * 
 * Recommended implementation pattern using generic helpers:
 * 
 * 	// Define type constants at the top of your file
 * 	const TypeMyProviderOptions = "myprovider.options"
 * 
 * 	type MyProviderOptions struct {
 * 	    Field string `json:"field"`
 * 	}
 * 
 * 	// Register the type in init() - place at top of file after constants
 * 	func init() {
 * 	    unillm.RegisterProviderType(TypeMyProviderOptions, func(data []byte) (unillm.ProviderOptionsData, error) {
 * 	        var opts MyProviderOptions
 * 	        if err := json.Unmarshal(data, &opts); err != nil {
 * 	            return nil, err
 * 	        }
 * 	        return &opts, nil
 * 	    })
 * 	}
 * 
 * 	// Implement ProviderOptionsData interface
 * 	func (*MyProviderOptions) Options() {}
 * 
 * 	// Implement json.Marshaler using the generic helper
 * 	func (m MyProviderOptions) MarshalJSON() ([]byte, error) {
 * 	    type plain MyProviderOptions
 * 	    return unillm.MarshalProviderType(TypeMyProviderOptions, plain(m))
 * 	}
 * 
 * 	// Implement json.Unmarshaler using the generic helper
 * 	// Note: Receives inner data after type routing by the registry.
 * 	func (m *MyProviderOptions) UnmarshalJSON(data []byte) error {
 * 	    type plain MyProviderOptions
 * 	    var p plain
 * 	    if err := unillm.UnmarshalProviderType(data, &p); err != nil {
 * 	        return err
 * 	    }
 * 	    *m = MyProviderOptions(p)
 * 	    return nil
 * 	}
 */
export type ProviderOptionsData = any;

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
var $$createType1 = (function $$initCreateType1(...args: any[]): any {
    if ($$createType1 === $$initCreateType1) {
        $$createType1 = $$createType2;
    }
    return $$createType1(...args);
});
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
