// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileItem represents a file database record
 */
export class FileItem {
    "url": string;
    "name": string;
    "size"?: number;

    /** Creates a new FileItem instance. */
    constructor($$source: Partial<FileItem> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileItem instance from a string or object.
     */
    static createFrom($$source: any = {}): FileItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileItem($$parsedSource as Partial<FileItem>);
    }
}
