// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./generated/models.js";

/**
 * CreateMessageWithRelationsParams contains all data needed to create a message with its relations
 */
export class CreateMessageWithRelationsParams {
    "Message": db$0.CreateMessageParams;
    "Plugin": db$0.CreateMessagePluginParams | null;
    "FileIds": string[];
    "FileChunks": {"ChunkId": string, "QueryId": string, "Similarity": sql$0.NullInt64}[];

    /** Creates a new CreateMessageWithRelationsParams instance. */
    constructor($$source: Partial<CreateMessageWithRelationsParams> = {}) {
        if (!("Message" in $$source)) {
            this["Message"] = (new db$0.CreateMessageParams());
        }
        if (!("Plugin" in $$source)) {
            this["Plugin"] = null;
        }
        if (!("FileIds" in $$source)) {
            this["FileIds"] = [];
        }
        if (!("FileChunks" in $$source)) {
            this["FileChunks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateMessageWithRelationsParams instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateMessageWithRelationsParams {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Message" in $$parsedSource) {
            $$parsedSource["Message"] = $$createField0_0($$parsedSource["Message"]);
        }
        if ("Plugin" in $$parsedSource) {
            $$parsedSource["Plugin"] = $$createField1_0($$parsedSource["Plugin"]);
        }
        if ("FileIds" in $$parsedSource) {
            $$parsedSource["FileIds"] = $$createField2_0($$parsedSource["FileIds"]);
        }
        if ("FileChunks" in $$parsedSource) {
            $$parsedSource["FileChunks"] = $$createField3_0($$parsedSource["FileChunks"]);
        }
        return new CreateMessageWithRelationsParams($$parsedSource as Partial<CreateMessageWithRelationsParams>);
    }
}

/**
 * UpdateMessageWithImagesParams contains data for updating a message with images
 */
export class UpdateMessageWithImagesParams {
    "MessageId": string;
    "Message": db$0.UpdateMessageParams;
    "ImageIds": string[];

    /** Creates a new UpdateMessageWithImagesParams instance. */
    constructor($$source: Partial<UpdateMessageWithImagesParams> = {}) {
        if (!("MessageId" in $$source)) {
            this["MessageId"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = (new db$0.UpdateMessageParams());
        }
        if (!("ImageIds" in $$source)) {
            this["ImageIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateMessageWithImagesParams instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateMessageWithImagesParams {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Message" in $$parsedSource) {
            $$parsedSource["Message"] = $$createField1_0($$parsedSource["Message"]);
        }
        if ("ImageIds" in $$parsedSource) {
            $$parsedSource["ImageIds"] = $$createField2_0($$parsedSource["ImageIds"]);
        }
        return new UpdateMessageWithImagesParams($$parsedSource as Partial<UpdateMessageWithImagesParams>);
    }
}

// Private type creation functions
const $$createType0 = db$0.CreateMessageParams.createFrom;
const $$createType1 = db$0.CreateMessagePluginParams.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = sql$0.NullInt64.createFrom;
const $$createType5 = $Create.Struct({
    "Similarity": $$createType4,
});
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = db$0.UpdateMessageParams.createFrom;
