// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./generated/models.js";

/**
 * CreateFileWithLinksParams contains all data needed to create a file with its links
 */
export class CreateFileWithLinksParams {
    /**
     * Creates a new CreateFileWithLinksParams instance.
     * @param {Partial<CreateFileWithLinksParams>} [$$source = {}] - The source object to create the CreateFileWithLinksParams.
     */
    constructor($$source = {}) {
        if (!("File" in $$source)) {
            /**
             * @member
             * @type {db$0.CreateFileParams}
             */
            this["File"] = (new db$0.CreateFileParams());
        }
        if (!("GlobalFile" in $$source)) {
            /**
             * @member
             * @type {db$0.CreateGlobalFileParams | null}
             */
            this["GlobalFile"] = null;
        }
        if (!("KnowledgeBase" in $$source)) {
            /**
             * Knowledge base ID to link to
             * @member
             * @type {string | null}
             */
            this["KnowledgeBase"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateFileWithLinksParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateFileWithLinksParams}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("File" in $$parsedSource) {
            $$parsedSource["File"] = $$createField0_0($$parsedSource["File"]);
        }
        if ("GlobalFile" in $$parsedSource) {
            $$parsedSource["GlobalFile"] = $$createField1_0($$parsedSource["GlobalFile"]);
        }
        return new CreateFileWithLinksParams(/** @type {Partial<CreateFileWithLinksParams>} */($$parsedSource));
    }
}

/**
 * CreateMessageWithRelationsParams contains all data needed to create a message with its relations
 */
export class CreateMessageWithRelationsParams {
    /**
     * Creates a new CreateMessageWithRelationsParams instance.
     * @param {Partial<CreateMessageWithRelationsParams>} [$$source = {}] - The source object to create the CreateMessageWithRelationsParams.
     */
    constructor($$source = {}) {
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {db$0.CreateMessageParams}
             */
            this["Message"] = (new db$0.CreateMessageParams());
        }
        if (!("Plugin" in $$source)) {
            /**
             * @member
             * @type {db$0.CreateMessagePluginParams | null}
             */
            this["Plugin"] = null;
        }
        if (!("FileIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["FileIds"] = [];
        }
        if (!("FileChunks" in $$source)) {
            /**
             * @member
             * @type {{"ChunkId": string, "QueryId": string, "Similarity": sql$0.NullInt64}[]}
             */
            this["FileChunks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateMessageWithRelationsParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateMessageWithRelationsParams}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Message" in $$parsedSource) {
            $$parsedSource["Message"] = $$createField0_0($$parsedSource["Message"]);
        }
        if ("Plugin" in $$parsedSource) {
            $$parsedSource["Plugin"] = $$createField1_0($$parsedSource["Plugin"]);
        }
        if ("FileIds" in $$parsedSource) {
            $$parsedSource["FileIds"] = $$createField2_0($$parsedSource["FileIds"]);
        }
        if ("FileChunks" in $$parsedSource) {
            $$parsedSource["FileChunks"] = $$createField3_0($$parsedSource["FileChunks"]);
        }
        return new CreateMessageWithRelationsParams(/** @type {Partial<CreateMessageWithRelationsParams>} */($$parsedSource));
    }
}

/**
 * DeleteFileWithCascadeParams contains data needed to delete a file with all related data
 */
export class DeleteFileWithCascadeParams {
    /**
     * Creates a new DeleteFileWithCascadeParams instance.
     * @param {Partial<DeleteFileWithCascadeParams>} [$$source = {}] - The source object to create the DeleteFileWithCascadeParams.
     */
    constructor($$source = {}) {
        if (!("FileID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FileID"] = "";
        }
        if (!("UserID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UserID"] = "";
        }
        if (!("RemoveGlobalFile" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["RemoveGlobalFile"] = false;
        }
        if (!("FileHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["FileHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteFileWithCascadeParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeleteFileWithCascadeParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteFileWithCascadeParams(/** @type {Partial<DeleteFileWithCascadeParams>} */($$parsedSource));
    }
}

/**
 * UpdateMessageWithImagesParams contains data for updating a message with images
 */
export class UpdateMessageWithImagesParams {
    /**
     * Creates a new UpdateMessageWithImagesParams instance.
     * @param {Partial<UpdateMessageWithImagesParams>} [$$source = {}] - The source object to create the UpdateMessageWithImagesParams.
     */
    constructor($$source = {}) {
        if (!("MessageId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["MessageId"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {db$0.UpdateMessageParams}
             */
            this["Message"] = (new db$0.UpdateMessageParams());
        }
        if (!("ImageIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["ImageIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateMessageWithImagesParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateMessageWithImagesParams}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Message" in $$parsedSource) {
            $$parsedSource["Message"] = $$createField1_0($$parsedSource["Message"]);
        }
        if ("ImageIds" in $$parsedSource) {
            $$parsedSource["ImageIds"] = $$createField2_0($$parsedSource["ImageIds"]);
        }
        return new UpdateMessageWithImagesParams(/** @type {Partial<UpdateMessageWithImagesParams>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = db$0.CreateFileParams.createFrom;
const $$createType1 = db$0.CreateGlobalFileParams.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = db$0.CreateMessageParams.createFrom;
const $$createType4 = db$0.CreateMessagePluginParams.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = sql$0.NullInt64.createFrom;
const $$createType8 = $Create.Struct({
    "Similarity": $$createType7,
});
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = db$0.UpdateMessageParams.createFrom;
