// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides database operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchInsertAIModels inserts multiple AI models atomically
 * Ignores conflicts (models that already exist)
 * @param {db$0.CreateAIModelParams[]} models
 * @returns {$CancellablePromise<db$0.AiModel[]>}
 */
export function BatchInsertAIModels(models) {
    return $Call.ByID(3944028528, models).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Close closes the database connection
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(2196848953);
}

/**
 * CreateFileWithLinks creates a file, optionally creates a global file, and links to knowledge base
 * All operations are atomic within a transaction
 * @param {$models.CreateFileWithLinksParams} params
 * @returns {$CancellablePromise<db$0.File | null>}
 */
export function CreateFileWithLinks(params) {
    return $Call.ByID(1179223106, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CreateMessageWithRelations creates a message and all its related data in a single transaction
 * @param {$models.CreateMessageWithRelationsParams} params
 * @param {string} userId
 * @returns {$CancellablePromise<db$0.Message>}
 */
export function CreateMessageWithRelations(params, userId) {
    return $Call.ByID(384784407, params, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * DB returns the underlying database connection
 * @returns {$CancellablePromise<sql$0.DB | null>}
 */
export function DB() {
    return $Call.ByID(270951045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * DeleteAIProviderWithModels deletes an AI provider and all its models atomically
 * @param {string} providerID
 * @param {string} userID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAIProviderWithModels(providerID, userID) {
    return $Call.ByID(2052033689, providerID, userID);
}

/**
 * DeleteFileWithCascade deletes a file and all its related chunks and embeddings
 * All operations are atomic within a transaction
 * @param {$models.DeleteFileWithCascadeParams} params
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFileWithCascade(params) {
    return $Call.ByID(4118927980, params);
}

/**
 * DeleteMessageWithRelated deletes a message and its related tool messages in a transaction
 * @param {string} toolCallIdsJson
 * @param {string[]} messageIds
 * @param {string} userId
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMessageWithRelated(toolCallIdsJson, messageIds, userId) {
    return $Call.ByID(3641449290, toolCallIdsJson, messageIds, userId);
}

/**
 * GetDocumentsByFileIds fetches documents by file IDs (batch operation)
 * @param {string} fileIdsJson
 * @param {string} userId
 * @returns {$CancellablePromise<db$0.GetDocumentByFileIdRow[]>}
 */
export function GetDocumentsByFileIds(fileIdsJson, userId) {
    return $Call.ByID(1781854764, fileIdsJson, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetMessagesByToolCallIds fetches messages by tool call IDs (batch operation)
 * @param {string} toolCallIdsJson
 * @param {string} userId
 * @returns {$CancellablePromise<string[]>}
 */
export function GetMessagesByToolCallIds(toolCallIdsJson, userId) {
    return $Call.ByID(2607655468, toolCallIdsJson, userId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * Queries returns the generated queries interface
 * @returns {$CancellablePromise<db$0.Queries | null>}
 */
export function Queries() {
    return $Call.ByID(1766016461).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * UpdateMessageWithImages updates a message and links images in a single transaction
 * @param {$models.UpdateMessageWithImagesParams} params
 * @param {string} userId
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMessageWithImages(params, userId) {
    return $Call.ByID(2812440899, params, userId);
}

/**
 * WithTx executes a function within a transaction
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function WithTx(fn) {
    return $Call.ByID(350966159, fn);
}

// Private type creation functions
const $$createType0 = db$0.AiModel.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = db$0.File.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = db$0.Message.createFrom;
const $$createType5 = sql$0.DB.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = db$0.GetDocumentByFileIdRow.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = db$0.Queries.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
