// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides database operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchInsertAIModels inserts multiple AI models atomically
 * Ignores conflicts (models that already exist)
 */
export function BatchInsertAIModels(models: db$0.CreateAIModelParams[]): $CancellablePromise<db$0.AiModel[]> {
    return $Call.ByID(3944028528, models).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Close closes the database connection
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2196848953);
}

/**
 * CreateFileWithLinks creates a file, optionally creates a global file, and links to knowledge base
 * All operations are atomic within a transaction
 */
export function CreateFileWithLinks(params: $models.CreateFileWithLinksParams): $CancellablePromise<db$0.File | null> {
    return $Call.ByID(1179223106, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreateMessageWithRelations creates a message and all its related data in a single transaction
 */
export function CreateMessageWithRelations(params: $models.CreateMessageWithRelationsParams): $CancellablePromise<db$0.Message> {
    return $Call.ByID(384784407, params).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * DB returns the underlying database connection
 */
export function DB(): $CancellablePromise<sql$0.DB | null> {
    return $Call.ByID(270951045).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * DeleteAIProviderWithModels deletes an AI provider and all its models atomically
 */
export function DeleteAIProviderWithModels(providerID: string): $CancellablePromise<void> {
    return $Call.ByID(2052033689, providerID);
}

/**
 * DeleteFileWithCascade deletes a file and all its related chunks and embeddings
 * All operations are atomic within a transaction
 */
export function DeleteFileWithCascade(params: $models.DeleteFileWithCascadeParams): $CancellablePromise<void> {
    return $Call.ByID(4118927980, params);
}

/**
 * DeleteMessageWithRelated deletes a message and its related tool messages in a transaction
 */
export function DeleteMessageWithRelated(toolCallIdsJson: string, messageIds: string[]): $CancellablePromise<void> {
    return $Call.ByID(3641449290, toolCallIdsJson, messageIds);
}

/**
 * GetDocumentsByFileIds fetches documents by file IDs (batch operation)
 */
export function GetDocumentsByFileIds(fileIdsJson: string): $CancellablePromise<db$0.GetDocumentByFileIdRow[]> {
    return $Call.ByID(1781854764, fileIdsJson).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetMessagesByToolCallIds fetches messages by tool call IDs (batch operation)
 */
export function GetMessagesByToolCallIds(toolCallIdsJson: string): $CancellablePromise<string[]> {
    return $Call.ByID(2607655468, toolCallIdsJson).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Queries returns the generated queries interface
 */
export function Queries(): $CancellablePromise<db$0.Queries | null> {
    return $Call.ByID(1766016461).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * SeedAvailableAgents loads pre-seeded agents from SQL dump
 */
export function SeedAvailableAgents(): $CancellablePromise<void> {
    return $Call.ByID(3729929935);
}

/**
 * UpdateMessageWithImages updates a message and links images in a single transaction
 */
export function UpdateMessageWithImages(params: $models.UpdateMessageWithImagesParams): $CancellablePromise<void> {
    return $Call.ByID(2812440899, params);
}

/**
 * WithTx executes a function within a transaction
 */
export function WithTx(fn: any): $CancellablePromise<void> {
    return $Call.ByID(350966159, fn);
}

// Private type creation functions
const $$createType0 = db$0.AiModel.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = db$0.File.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = db$0.Message.createFrom;
const $$createType5 = sql$0.DB.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = db$0.GetDocumentByFileIdRow.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = db$0.Queries.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
