// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides database operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close closes the database connection
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2196848953);
}

/**
 * CreateMessageWithRelations creates a message and all its related data in a single transaction
 */
export function CreateMessageWithRelations(params: $models.CreateMessageWithRelationsParams, userId: string): $CancellablePromise<db$0.Message> {
    return $Call.ByID(384784407, params, userId).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * DB returns the underlying database connection
 */
export function DB(): $CancellablePromise<sql$0.DB | null> {
    return $Call.ByID(270951045).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * DeleteMessageWithRelated deletes a message and its related tool messages in a transaction
 */
export function DeleteMessageWithRelated(toolCallIdsJson: string, messageIds: string[], userId: string): $CancellablePromise<void> {
    return $Call.ByID(3641449290, toolCallIdsJson, messageIds, userId);
}

/**
 * GetDocumentsByFileIds fetches documents by file IDs (batch operation)
 */
export function GetDocumentsByFileIds(fileIdsJson: string, userId: string): $CancellablePromise<db$0.GetDocumentByFileIdRow[]> {
    return $Call.ByID(1781854764, fileIdsJson, userId).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetMessagesByToolCallIds fetches messages by tool call IDs (batch operation)
 */
export function GetMessagesByToolCallIds(toolCallIdsJson: string, userId: string): $CancellablePromise<string[]> {
    return $Call.ByID(2607655468, toolCallIdsJson, userId).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Queries returns the generated queries interface
 */
export function Queries(): $CancellablePromise<db$0.Queries | null> {
    return $Call.ByID(1766016461).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * UpdateMessageWithImages updates a message and links images in a single transaction
 */
export function UpdateMessageWithImages(params: $models.UpdateMessageWithImagesParams, userId: string): $CancellablePromise<void> {
    return $Call.ByID(2812440899, params, userId);
}

/**
 * WithTx executes a function within a transaction
 */
export function WithTx(fn: any): $CancellablePromise<void> {
    return $Call.ByID(350966159, fn);
}

// Private type creation functions
const $$createType0 = db$0.Message.createFrom;
const $$createType1 = sql$0.DB.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = db$0.GetDocumentByFileIdRow.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = db$0.Queries.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
