// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close closes the current database connection if one is open, otherwise has no effect.
 * Additionally, Close closes all open prepared statements associated to the connection.
 * 
 * Even when a non-nil error is returned,
 * the database service is left in a consistent state,
 * ready for a call to [Service.Open].
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(3572972428);
}

/**
 * ClosePrepared closes a prepared statement
 * obtained with [Service.Prepare] or [Service.PrepareContext].
 * ClosePrepared is idempotent:
 * it has no effect on prepared statements that are already closed.
 * @param {$models.Stmt | null} stmt
 * @returns {$CancellablePromise<void>}
 */
function ClosePrepared(stmt) {
    return $Call.ByID(1189575769, stmt);
}

/**
 * ExecContext executes a query without returning any rows.
 * It supports early cancellation.
 * @param {string} query
 * @param {any[]} args
 * @returns {$CancellablePromise<void>}
 */
function ExecContext(query, ...args) {
    return $Call.ByID(1232535752, query, args);
}

/**
 * ExecPrepared executes a prepared statement
 * obtained with [Service.Prepare] or [Service.PrepareContext]
 * without returning any rows.
 * It supports early cancellation.
 * @param {$models.Stmt | null} stmt
 * @param {any[]} args
 * @returns {$CancellablePromise<void>}
 */
function ExecPrepared(stmt, ...args) {
    return $Call.ByID(1832697852, stmt, args);
}

/**
 * Open validates the current configuration,
 * closes the current connection if one is present,
 * then opens and validates a new connection.
 * 
 * Even when a non-nil error is returned,
 * the database service is left in a consistent state,
 * ready for a new call to Open.
 * @returns {$CancellablePromise<void>}
 */
export function Open() {
    return $Call.ByID(3257490240);
}

/**
 * PrepareContext creates a prepared statement for later queries or executions.
 * Multiple queries or executions may be run concurrently from the returned statement.
 * 
 * The caller must call the statement's Close method when it is no longer needed.
 * Statements are closed automatically
 * when the connection they are associated with is closed.
 * 
 * PrepareContext supports early cancellation.
 * @param {string} query
 * @returns {$CancellablePromise<$models.Stmt | null>}
 */
function PrepareContext(query) {
    return $Call.ByID(275194082, query);
}

/**
 * QueryContext executes a query and returns a slice of key-value records,
 * one per row, with column names as keys.
 * It supports early cancellation, returning the slice of results fetched so far.
 * @param {string} query
 * @param {any[]} args
 * @returns {$CancellablePromise<$models.Rows>}
 */
function QueryContext(query, ...args) {
    return $Call.ByID(3789340447, query, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * QueryPrepared executes a prepared statement
 * obtained with [Service.Prepare] or [Service.PrepareContext]
 * and returns a slice of key-value records, one per row, with column names as keys.
 * It supports early cancellation, returning the slice of results fetched so far.
 * @param {$models.Stmt | null} stmt
 * @param {any[]} args
 * @returns {$CancellablePromise<$models.Rows>}
 */
function QueryPrepared(stmt, ...args) {
    return $Call.ByID(233520361, stmt, args).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);

export {
    ExecContext as Execute,
    QueryContext as Query
};

import { Stmt } from "./stmt.ts";

/**
 * Prepare creates a prepared statement for later queries or executions.
 * Multiple queries or executions may be run concurrently from the returned statement.
 *
 * The caller must call the statement's Close method when it is no longer needed.
 * Statements are closed automatically
 * when the connection they are associated with is closed.
 *
 * Prepare supports early cancellation.
 *
 * @param {string} query
 * @returns {Promise<Stmt | null> & { cancel(): void }}
 */
export function Prepare(query) {
    const promise = PrepareContext(query);
    const wrapper = /** @type {any} */(promise.then(function (id) {
        return id == null ? null : new Stmt(
            ClosePrepared.bind(null, id),
            ExecPrepared.bind(null, id),
            QueryPrepared.bind(null, id));
    }));
    wrapper.cancel = promise.cancel;
    return wrapper;
}
