// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TTSService provides text-to-speech using native OS capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDefaultVoice returns the system default voice
 */
export function GetDefaultVoice(): $CancellablePromise<string> {
    return $Call.ByID(4147699036);
}

/**
 * GetPlatformInfo returns information about TTS capabilities on current platform
 */
export function GetPlatformInfo(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(3877218302).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetRecommendedVoices returns high-quality voices for common languages
 */
export function GetRecommendedVoices(): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(4129523931).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetVoicesByLanguage returns voices filtered by language code
 */
export function GetVoicesByLanguage(langCode: string): $CancellablePromise<$models.Voice[]> {
    return $Call.ByID(1307230325, langCode).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * IsPlatformSupported returns whether TTS is supported on current platform
 */
export function IsPlatformSupported(): $CancellablePromise<boolean> {
    return $Call.ByID(1880700274);
}

/**
 * ListVoices returns available TTS voices
 */
export function ListVoices(): $CancellablePromise<$models.Voice[]> {
    return $Call.ByID(2444780296).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Speak converts text to speech using default voice
 */
export function Speak(text: string): $CancellablePromise<void> {
    return $Call.ByID(144204815, text);
}

/**
 * SpeakToAudio generates speech and returns audio data as byte array
 * This is more convenient than SpeakToFile for frontend integration
 */
export function SpeakToAudio(text: string): $CancellablePromise<string> {
    return $Call.ByID(2408955780, text).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * SpeakToAudioWithVoice generates speech with specified voice and returns audio data
 */
export function SpeakToAudioWithVoice(text: string, voice: string): $CancellablePromise<string> {
    return $Call.ByID(1491100486, text, voice).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * SpeakToFile saves speech to an audio file
 * Supported formats: AIFF (macOS default), WAV, etc.
 */
export function SpeakToFile(text: string, outputPath: string): $CancellablePromise<void> {
    return $Call.ByID(1981988428, text, outputPath);
}

/**
 * SpeakToFileWithVoice saves speech to file with specified voice
 */
export function SpeakToFileWithVoice(text: string, outputPath: string, voice: string): $CancellablePromise<void> {
    return $Call.ByID(61657630, text, outputPath, voice);
}

/**
 * SpeakWithRate converts text to speech with custom speaking rate
 * rate: words per minute (default is ~175 for macOS)
 */
export function SpeakWithRate(text: string, rate: number): $CancellablePromise<void> {
    return $Call.ByID(3268846685, text, rate);
}

/**
 * SpeakWithVoice converts text to speech using specified voice
 */
export function SpeakWithVoice(text: string, voice: string): $CancellablePromise<void> {
    return $Call.ByID(1292911115, text, voice);
}

/**
 * Stop stops any ongoing speech (macOS only)
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(634066903);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.Voice.createFrom;
const $$createType3 = $Create.Array($$createType2);
