// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CreateImageRequest matches frontend createImage action parameters
 */
export class CreateImageRequest {
    "generationTopicId": string;
    "provider": string;
    "model": string;
    "imageNum": number;
    "params": RuntimeImageGenParams;

    /** Creates a new CreateImageRequest instance. */
    constructor($$source: Partial<CreateImageRequest> = {}) {
        if (!("generationTopicId" in $$source)) {
            this["generationTopicId"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("imageNum" in $$source)) {
            this["imageNum"] = 0;
        }
        if (!("params" in $$source)) {
            this["params"] = (new RuntimeImageGenParams());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateImageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateImageRequest {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField4_0($$parsedSource["params"]);
        }
        return new CreateImageRequest($$parsedSource as Partial<CreateImageRequest>);
    }
}

/**
 * RuntimeImageGenParams matches frontend model-bank/standard-parameters RuntimeImageGenParams
 */
export class RuntimeImageGenParams {
    "prompt": string;
    "imageUrl"?: string | null;
    "imageUrls"?: string[];
    "width"?: number | null;
    "height"?: number | null;
    "size"?: string;
    "aspectRatio"?: string;
    "cfg"?: number | null;
    "strength"?: number | null;
    "steps"?: number | null;
    "quality"?: string;
    "seed"?: number | null;
    "samplerName"?: string;
    "scheduler"?: string;

    /** Creates a new RuntimeImageGenParams instance. */
    constructor($$source: Partial<RuntimeImageGenParams> = {}) {
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeImageGenParams instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeImageGenParams {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("imageUrls" in $$parsedSource) {
            $$parsedSource["imageUrls"] = $$createField2_0($$parsedSource["imageUrls"]);
        }
        return new RuntimeImageGenParams($$parsedSource as Partial<RuntimeImageGenParams>);
    }
}

// Private type creation functions
const $$createType0 = RuntimeImageGenParams.createFrom;
const $$createType1 = $Create.Array($Create.Any);
