// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AudioRecorderService provides native audio recording capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * CancelRecording cancels the current recording without saving
 */
export function CancelRecording(): $CancellablePromise<void> {
    return $Call.ByID(1283608304);
}

/**
 * CheckRecordingCapabilities checks if audio recording is supported
 */
export function CheckRecordingCapabilities(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(4231698862).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetRecordingPath returns the path to the current recording
 */
export function GetRecordingPath(): $CancellablePromise<string> {
    return $Call.ByID(577238871);
}

/**
 * IsRecording returns whether audio is currently being recorded
 */
export function IsRecording(): $CancellablePromise<boolean> {
    return $Call.ByID(602178910);
}

/**
 * SetApp sets the application instance (for event emission)
 * This can be called after the app is created if the service was initialized before
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2446897756, app);
}

/**
 * StartRecording starts recording audio from the microphone
 * Returns the path where the audio will be saved
 */
export function StartRecording(): $CancellablePromise<string> {
    return $Call.ByID(2850119820);
}

/**
 * StopRecording stops the current recording
 * Returns the path to the recorded audio file
 */
export function StopRecording(): $CancellablePromise<string> {
    return $Call.ByID(2748351890);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
