// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FilterCondition represents a filter condition for queries
 */
export class FilterCondition {
    "column": string;

    /**
     * "equals", "contains", "startsWith", "endsWith"
     */
    "operator": string;
    "value": any;

    /** Creates a new FilterCondition instance. */
    constructor($$source: Partial<FilterCondition> = {}) {
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("operator" in $$source)) {
            this["operator"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterCondition($$parsedSource as Partial<FilterCondition>);
    }
}

/**
 * ForeignKey represents a foreign key relationship
 */
export class ForeignKey {
    "table": string;
    "column": string;

    /** Creates a new ForeignKey instance. */
    constructor($$source: Partial<ForeignKey> = {}) {
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKey instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKey($$parsedSource as Partial<ForeignKey>);
    }
}

/**
 * PaginationParams represents pagination and sorting parameters
 */
export class PaginationParams {
    "page": number;
    "pageSize": number;
    "sortBy"?: string | null;

    /**
     * "asc" or "desc"
     */
    "sortOrder"?: string | null;

    /** Creates a new PaginationParams instance. */
    constructor($$source: Partial<PaginationParams> = {}) {
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginationParams instance from a string or object.
     */
    static createFrom($$source: any = {}): PaginationParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaginationParams($$parsedSource as Partial<PaginationParams>);
    }
}

/**
 * PaginationResult wraps paginated data with metadata
 */
export class PaginationResult {
    "page": number;
    "pageSize": number;
    "total": number;

    /** Creates a new PaginationResult instance. */
    constructor($$source: Partial<PaginationResult> = {}) {
        if (!("page" in $$source)) {
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PaginationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaginationResult($$parsedSource as Partial<PaginationResult>);
    }
}

/**
 * TableBasicInfo represents basic information about a database table
 */
export class TableBasicInfo {
    "name": string;

    /**
     * "BASE TABLE" or "VIEW"
     */
    "type": string;
    "count": number;

    /** Creates a new TableBasicInfo instance. */
    constructor($$source: Partial<TableBasicInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableBasicInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableBasicInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableBasicInfo($$parsedSource as Partial<TableBasicInfo>);
    }
}

/**
 * TableColumnInfo represents detailed information about a table column
 */
export class TableColumnInfo {
    "name": string;
    "type": string;
    "nullable": boolean;
    "isPrimaryKey": boolean;
    "defaultValue"?: string | null;
    "foreignKey"?: ForeignKey | null;

    /** Creates a new TableColumnInfo instance. */
    constructor($$source: Partial<TableColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("isPrimaryKey" in $$source)) {
            this["isPrimaryKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableColumnInfo {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("foreignKey" in $$parsedSource) {
            $$parsedSource["foreignKey"] = $$createField5_0($$parsedSource["foreignKey"]);
        }
        return new TableColumnInfo($$parsedSource as Partial<TableColumnInfo>);
    }
}

/**
 * TableDataResult represents the result of a paginated table query
 */
export class TableDataResult {
    "data": { [_: string]: any }[];
    "pagination": PaginationResult;

    /** Creates a new TableDataResult instance. */
    constructor($$source: Partial<TableDataResult> = {}) {
        if (!("data" in $$source)) {
            this["data"] = [];
        }
        if (!("pagination" in $$source)) {
            this["pagination"] = (new PaginationResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDataResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TableDataResult {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        if ("pagination" in $$parsedSource) {
            $$parsedSource["pagination"] = $$createField1_0($$parsedSource["pagination"]);
        }
        return new TableDataResult($$parsedSource as Partial<TableDataResult>);
    }
}

// Private type creation functions
const $$createType0 = ForeignKey.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PaginationResult.createFrom;
