// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FilterCondition represents a filter condition for queries
 */
export class FilterCondition {
    /**
     * Creates a new FilterCondition instance.
     * @param {Partial<FilterCondition>} [$$source = {}] - The source object to create the FilterCondition.
     */
    constructor($$source = {}) {
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("operator" in $$source)) {
            /**
             * "equals", "contains", "startsWith", "endsWith"
             * @member
             * @type {string}
             */
            this["operator"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterCondition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FilterCondition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilterCondition(/** @type {Partial<FilterCondition>} */($$parsedSource));
    }
}

/**
 * ForeignKey represents a foreign key relationship
 */
export class ForeignKey {
    /**
     * Creates a new ForeignKey instance.
     * @param {Partial<ForeignKey>} [$$source = {}] - The source object to create the ForeignKey.
     */
    constructor($$source = {}) {
        if (!("table" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table"] = "";
        }
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKey instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ForeignKey}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKey(/** @type {Partial<ForeignKey>} */($$parsedSource));
    }
}

/**
 * PaginationParams represents pagination and sorting parameters
 */
export class PaginationParams {
    /**
     * Creates a new PaginationParams instance.
     * @param {Partial<PaginationParams>} [$$source = {}] - The source object to create the PaginationParams.
     */
    constructor($$source = {}) {
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["sortBy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "asc" or "desc"
             * @member
             * @type {string | null | undefined}
             */
            this["sortOrder"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginationParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaginationParams}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaginationParams(/** @type {Partial<PaginationParams>} */($$parsedSource));
    }
}

/**
 * PaginationResult wraps paginated data with metadata
 */
export class PaginationResult {
    /**
     * Creates a new PaginationResult instance.
     * @param {Partial<PaginationResult>} [$$source = {}] - The source object to create the PaginationResult.
     */
    constructor($$source = {}) {
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaginationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PaginationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaginationResult(/** @type {Partial<PaginationResult>} */($$parsedSource));
    }
}

/**
 * TableBasicInfo represents basic information about a database table
 */
export class TableBasicInfo {
    /**
     * Creates a new TableBasicInfo instance.
     * @param {Partial<TableBasicInfo>} [$$source = {}] - The source object to create the TableBasicInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "BASE TABLE" or "VIEW"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableBasicInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableBasicInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableBasicInfo(/** @type {Partial<TableBasicInfo>} */($$parsedSource));
    }
}

/**
 * TableColumnInfo represents detailed information about a table column
 */
export class TableColumnInfo {
    /**
     * Creates a new TableColumnInfo instance.
     * @param {Partial<TableColumnInfo>} [$$source = {}] - The source object to create the TableColumnInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nullable"] = false;
        }
        if (!("isPrimaryKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimaryKey"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["defaultValue"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ForeignKey | null | undefined}
             */
            this["foreignKey"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableColumnInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableColumnInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("foreignKey" in $$parsedSource) {
            $$parsedSource["foreignKey"] = $$createField5_0($$parsedSource["foreignKey"]);
        }
        return new TableColumnInfo(/** @type {Partial<TableColumnInfo>} */($$parsedSource));
    }
}

/**
 * TableDataResult represents the result of a paginated table query
 */
export class TableDataResult {
    /**
     * Creates a new TableDataResult instance.
     * @param {Partial<TableDataResult>} [$$source = {}] - The source object to create the TableDataResult.
     */
    constructor($$source = {}) {
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: any }[]}
             */
            this["data"] = [];
        }
        if (!("pagination" in $$source)) {
            /**
             * @member
             * @type {PaginationResult}
             */
            this["pagination"] = (new PaginationResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDataResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableDataResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField0_0($$parsedSource["data"]);
        }
        if ("pagination" in $$parsedSource) {
            $$parsedSource["pagination"] = $$createField1_0($$parsedSource["pagination"]);
        }
        return new TableDataResult(/** @type {Partial<TableDataResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ForeignKey.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PaginationResult.createFrom;
