// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TopicService handles topic-related operations including title generation
 */
export class TopicService {

    /** Creates a new TopicService instance. */
    constructor($$source: Partial<TopicService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopicService instance from a string or object.
     */
    static createFrom($$source: any = {}): TopicService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TopicService($$parsedSource as Partial<TopicService>);
    }
}
