/*
 * Copyright 2025 Veridium Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package services

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/kawai-network/veridium/fantasy"
	"github.com/kawai-network/veridium/fantasy/llamalib"
	"github.com/kawai-network/veridium/fantasy/llamalib/tools"
	yzmabuiltin "github.com/kawai-network/veridium/fantasy/llamalib/tools/builtin"
	"github.com/kawai-network/veridium/internal/database"
	db "github.com/kawai-network/veridium/internal/database/generated"
	"github.com/kawai-network/veridium/internal/topic"
	"github.com/kawai-network/veridium/types"
	"github.com/pemistahl/lingua-go"
	"github.com/wailsapp/wails/v3/pkg/application"
)

// AgentChatService provides agent-based chat with RAG, tools, and context awareness
// This replaces/complements the existing LibraryChatService with Yzma-based capabilities
type AgentChatService struct {
	app         *application.App
	db          *database.Service
	libService  *llamalib.Service
	kbService   *KnowledgeBaseService
	ragWorkflow *RAGWorkflow

	// Vector search for file-based RAG (direct file attachments)
	vectorSearch *VectorSearchService

	// Language models for different tasks (all fantasy.LanguageModel interface)
	// These can be ChainLanguageModel for fallback support
	chatModel    fantasy.LanguageModel // Main chat model (streaming + tools)
	titleModel   fantasy.LanguageModel // Title generation model (lightweight)
	summaryModel fantasy.LanguageModel // Summary generation model

	// Yzma tool registry (replaces Eino tools)
	toolRegistry *tools.ToolRegistry

	// Phase 4: Thread management
	threadService *ThreadManagementService // Thread management service
	topicService  *topic.TopicService      // Topic service for title generation

	// Reasoning mode configuration
	reasoningConfig ReasoningConfig // Controls reasoning behavior

	// Session management (hybrid: DB + in-memory cache)
	sessions      map[string]*AgentSession // In-memory cache for active sessions
	sessionsMutex sync.RWMutex

	// Memory integration for MemGPT-style memory
	memoryIntegration *MemoryIntegration

	// Language detector for detecting user message language
	languageDetector lingua.LanguageDetector
}

// AgentSession represents an ongoing conversation with context
type AgentSession struct {
	SessionID       string
	UserID          string
	Messages        []fantasy.Message // Native yzma messages
	KnowledgeBaseID string
	ToolNames       []string // Tool names to use for this session
	Context         map[string]any
	CreatedAt       int64
	UpdatedAt       int64
	DBSession       *db.Session // Link to DB session

	// Phase 4: Topic & Thread support
	TopicID  string // Current topic ID (may be auto-created)
	ThreadID string // Current thread ID (for branching)
}

// ChatRequest represents a chat request with agent capabilities
type ChatRequest struct {
	// Identity
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`

	// Message content
	Message string `json:"message"`

	// Message IDs (pre-generated by frontend for optimistic UI)
	MessageUserID      string `json:"message_user_id,omitempty"`      // Pre-generated user message ID
	MessageAssistantID string `json:"message_assistant_id,omitempty"` // Pre-generated assistant message ID

	// Context (Phase 4: Topic & Thread support)
	TopicID  string `json:"topic_id,omitempty"`  // Current topic (may be auto-created)
	ThreadID string `json:"thread_id,omitempty"` // Current thread (for branching)
	ParentID string `json:"parent_id,omitempty"` // Parent message (for threading)

	// File attachments (processed by FileProcessorService)
	FileIDs []string `json:"file_ids,omitempty"` // File IDs for RAG context retrieval

	// Configuration
	KnowledgeBaseID string         `json:"knowledge_base_id,omitempty"`
	Tools           []string       `json:"tools,omitempty"`
	Context         map[string]any `json:"context,omitempty"`
	Temperature     float32        `json:"temperature,omitempty"`
	MaxTokens       int            `json:"max_tokens,omitempty"`
	Stream          bool           `json:"stream,omitempty"`
}

// UIMessageRoleType represents the role of a message
type UIMessageRoleType string

const (
	UIMessageRoleUser       UIMessageRoleType = "user"
	UIMessageRoleSystem     UIMessageRoleType = "system"
	UIMessageRoleAssistant  UIMessageRoleType = "assistant"
	UIMessageRoleTool       UIMessageRoleType = "tool"
	UIMessageRoleSupervisor UIMessageRoleType = "supervisor"
	UIMessageRoleGroup      UIMessageRoleType = "group"
)

// MetaData represents metadata for messages/agents
type MetaData struct {
	Avatar          string   `json:"avatar,omitempty"`
	BackgroundColor string   `json:"backgroundColor,omitempty"`
	Description     string   `json:"description,omitempty"`
	Tags            []string `json:"tags,omitempty"`
	Title           string   `json:"title,omitempty"`
}

// ChatFileItem represents a file attachment
type ChatFileItem struct {
	Content  string `json:"content,omitempty"`
	FileType string `json:"fileType"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Size     int64  `json:"size"`
	URL      string `json:"url"`
}

// ChatImageItem represents an image attachment
type ChatImageItem struct {
	Alt string `json:"alt,omitempty"`
	ID  string `json:"id"`
	URL string `json:"url"`
}

// ChatVideoItem represents a video attachment
type ChatVideoItem struct {
	Cover string `json:"cover,omitempty"`
	ID    string `json:"id"`
	Name  string `json:"name,omitempty"`
	Size  int64  `json:"size,omitempty"`
	URL   string `json:"url"`
}

// ModelUsage represents token usage metrics
type ModelUsage struct {
	InputCachedTokens        int     `json:"inputCachedTokens,omitempty"`
	InputCacheMissTokens     int     `json:"inputCacheMissTokens,omitempty"`
	InputWriteCacheTokens    int     `json:"inputWriteCacheTokens,omitempty"`
	InputTextTokens          int     `json:"inputTextTokens,omitempty"`
	InputImageTokens         int     `json:"inputImageTokens,omitempty"`
	InputAudioTokens         int     `json:"inputAudioTokens,omitempty"`
	InputCitationTokens      int     `json:"inputCitationTokens,omitempty"`
	OutputTextTokens         int     `json:"outputTextTokens,omitempty"`
	OutputImageTokens        int     `json:"outputImageTokens,omitempty"`
	OutputAudioTokens        int     `json:"outputAudioTokens,omitempty"`
	OutputReasoningTokens    int     `json:"outputReasoningTokens,omitempty"`
	AcceptedPredictionTokens int     `json:"acceptedPredictionTokens,omitempty"`
	RejectedPredictionTokens int     `json:"rejectedPredictionTokens,omitempty"`
	TotalInputTokens         int     `json:"totalInputTokens,omitempty"`
	TotalOutputTokens        int     `json:"totalOutputTokens,omitempty"`
	TotalTokens              int     `json:"totalTokens,omitempty"`
	Cost                     float64 `json:"cost,omitempty"`
}

// ModelPerformance represents performance metrics
type ModelPerformance struct {
	TPS      float64 `json:"tps,omitempty"`
	TTFT     int64   `json:"ttft,omitempty"`
	Duration int64   `json:"duration,omitempty"`
	Latency  int64   `json:"latency,omitempty"`
}

// ModelReasoning represents reasoning/thinking content
type ModelReasoning struct {
	Content   string `json:"content,omitempty"`
	Duration  int64  `json:"duration,omitempty"`
	Signature string `json:"signature,omitempty"`
}

// ChatMessageError represents an error in a message
type ChatMessageError struct {
	Body    interface{} `json:"body,omitempty"`
	Message string      `json:"message"`
	Type    string      `json:"type"`
}

// MessageMetadata combines usage and performance metrics
type MessageMetadata struct {
	ModelUsage
	ModelPerformance
}

// ChatTTS represents text-to-speech data
type ChatTTS struct {
	ContentMd5 string `json:"contentMd5,omitempty"`
	File       string `json:"file,omitempty"`
	Voice      string `json:"voice,omitempty"`
}

// ChatTranslate represents translation data
type ChatTranslate struct {
	Content string `json:"content,omitempty"`
	From    string `json:"from,omitempty"`
	To      string `json:"to,omitempty"`
}

// ChatMessageExtra represents extra message fields
type ChatMessageExtra struct {
	FromModel    string         `json:"fromModel,omitempty"`
	FromProvider string         `json:"fromProvider,omitempty"`
	Translate    *ChatTranslate `json:"translate,omitempty"`
	TTS          *ChatTTS       `json:"tts,omitempty"`
}

// ChatToolResult represents tool execution result
type ChatToolResult struct {
	Content string      `json:"content"`
	Error   interface{} `json:"error,omitempty"`
	ID      string      `json:"id"`
	State   interface{} `json:"state,omitempty"`
}

// ChatToolPayload represents a tool call payload
type ChatToolPayload struct {
	APIName    string `json:"apiName"`
	Arguments  string `json:"arguments"`
	ID         string `json:"id"`
	Identifier string `json:"identifier"`
	Type       string `json:"type"`
}

// ChatFileChunk represents a file chunk from RAG system
type ChatFileChunk struct {
	FileID     string  `json:"fileId"`
	FileType   string  `json:"fileType"`
	FileURL    string  `json:"fileUrl"`
	Filename   string  `json:"filename"`
	ID         string  `json:"id"`
	Similarity float64 `json:"similarity,omitempty"`
	Text       string  `json:"text"`
}

// CitationItem represents a citation from search results
type CitationItem struct {
	Favicon string `json:"favicon,omitempty"`
	ID      string `json:"id,omitempty"`
	Title   string `json:"title,omitempty"`
	URL     string `json:"url"`
}

// GroundingSearch represents search grounding data for messages
type GroundingSearch struct {
	Citations     []CitationItem `json:"citations,omitempty"`
	SearchQueries []string       `json:"searchQueries,omitempty"`
}

// ChatToolPayloadWithResult combines tool payload with result
type ChatToolPayloadWithResult struct {
	ChatToolPayload
	Result *ChatToolResult `json:"result,omitempty"`
}

// ChatPluginPayload represents a plugin call payload
type ChatPluginPayload struct {
	APIName    string `json:"apiName"`
	Arguments  string `json:"arguments"`
	Identifier string `json:"identifier"`
	Type       string `json:"type"`
}

// AssistantContentBlock represents content block in grouped messages
type AssistantContentBlock struct {
	Content     string                      `json:"content"`
	FileList    []ChatFileItem              `json:"fileList,omitempty"`
	ID          string                      `json:"id"`
	ImageList   []ChatImageItem             `json:"imageList,omitempty"`
	Performance *ModelPerformance           `json:"performance,omitempty"`
	Tools       []ChatToolPayloadWithResult `json:"tools,omitempty"`
	Usage       *ModelUsage                 `json:"usage,omitempty"`
}

// UIChatMessage represents the response from agent (matches frontend/src/types/message/ui/chat.ts)
// This type is used for ALL message roles: user, assistant, tool, system, etc.
// For tool messages (role='tool'), use ToolCallID to link back to the tool call in assistant message.
type UIChatMessage struct {
	AgentID    string                  `json:"agentId,omitempty"`
	Children   []AssistantContentBlock `json:"children,omitempty"`
	ChunksList []ChatFileChunk         `json:"chunksList,omitempty"`
	Content    string                  `json:"content"`
	CreatedAt  int64                   `json:"createdAt"`
	Error      *ChatMessageError       `json:"error,omitempty"`
	Extra      *ChatMessageExtra       `json:"extra,omitempty"`
	FileList   []ChatFileItem          `json:"fileList,omitempty"`
	Files      []string                `json:"files,omitempty"` // deprecated
	GroupID    string                  `json:"groupId,omitempty"`
	ID         string                  `json:"id"`
	ImageList  []ChatImageItem         `json:"imageList,omitempty"`
	Meta       MetaData                `json:"meta"`
	Metadata   *MessageMetadata        `json:"metadata,omitempty"`

	ObservationID string            `json:"observationId,omitempty"`
	ParentID      string            `json:"parentId,omitempty"`
	Performance   *ModelPerformance `json:"performance,omitempty"`

	Plugin      *ChatPluginPayload `json:"plugin,omitempty"`
	PluginError interface{}        `json:"pluginError,omitempty"`
	PluginState interface{}        `json:"pluginState,omitempty"`

	QuotaID     string `json:"quotaId,omitempty"`
	RagQuery    string `json:"ragQuery,omitempty"`
	RagQueryID  string `json:"ragQueryId,omitempty"`
	RagRawQuery string `json:"ragRawQuery,omitempty"`

	Reasoning *ModelReasoning   `json:"reasoning,omitempty"`
	Role      UIMessageRoleType `json:"role"`
	Search    *GroundingSearch  `json:"search,omitempty"`

	SessionID  string `json:"sessionId,omitempty"`
	TargetID   string `json:"targetId,omitempty"`
	ThreadID   string `json:"threadId,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`

	Tools   []ChatToolPayload `json:"tools,omitempty"`
	TopicID string            `json:"topicId,omitempty"`
	TraceID string            `json:"traceId,omitempty"`

	UpdatedAt int64           `json:"updatedAt"`
	Usage     *ModelUsage     `json:"usage,omitempty"`
	VideoList []ChatVideoItem `json:"videoList,omitempty"`
}

// NewAgentChatService creates a new agent-based chat service
// Set threadService to nil to disable thread management
func NewAgentChatService(
	app *application.App,
	db *database.Service,
	libService *llamalib.Service,
	kbService *KnowledgeBaseService,
	vectorSearch *VectorSearchService,
	threadService *ThreadManagementService,
	topicService *topic.TopicService,
) *AgentChatService {
	ragWorkflow := NewRAGWorkflow(kbService)

	// Initialize Yzma Tool Registry & Register Builtin Tools
	// Pass SQL DB for tools that need database access (e.g., image describe)
	toolRegistry := tools.NewToolRegistry()
	if err := yzmabuiltin.RegisterAllWithDB(toolRegistry, db.DB()); err != nil {
		log.Printf("⚠️  Warning: Failed to register yzma builtin tools: %v", err)
	} else {
		log.Printf("✅ AgentChatService: Yzma builtin tools registered")
	}

	// Initialize language detector with common languages
	// Using a subset of languages for faster detection while covering most use cases
	languages := []lingua.Language{
		lingua.English,
		lingua.Indonesian,
		lingua.Chinese,
		lingua.Japanese,
		lingua.Korean,
		lingua.Spanish,
		lingua.French,
		lingua.German,
		lingua.Italian,
		lingua.Portuguese,
		lingua.Russian,
		lingua.Arabic,
		lingua.Hindi,
		lingua.Thai,
		lingua.Vietnamese,
		lingua.Dutch,
		lingua.Turkish,
		lingua.Polish,
		lingua.Malay,
	}
	languageDetector := lingua.NewLanguageDetectorBuilder().
		FromLanguages(languages...).
		WithMinimumRelativeDistance(0.25). // Require 25% confidence difference between top languages
		Build()
	log.Printf("✅ AgentChatService: Language detector initialized with %d languages", len(languages))

	service := &AgentChatService{
		app:              app,
		db:               db,
		libService:       libService,
		kbService:        kbService,
		ragWorkflow:      ragWorkflow,
		vectorSearch:     vectorSearch,
		toolRegistry:     toolRegistry,
		threadService:    threadService,
		topicService:     topicService,
		reasoningConfig:  DefaultReasoningConfig(), // Default: disabled (non-reasoning)
		sessions:         make(map[string]*AgentSession),
		languageDetector: languageDetector,
	}

	log.Printf("✅ AgentChatService: Initialized (models will be injected via SetChatModel/SetTitleModel/SetSummaryModel)")

	return service
}

// SetChatModel sets the main chat model (for streaming chat with tools)
func (s *AgentChatService) SetChatModel(model fantasy.LanguageModel) {
	s.chatModel = model
	if model != nil {
		log.Printf("✅ AgentChatService: Chat model set (%s/%s)", model.Provider(), model.Model())
	}
}

// SetTitleModel sets the title generation model
func (s *AgentChatService) SetTitleModel(model fantasy.LanguageModel) {
	if s.topicService != nil {
		s.topicService.SetTitleModel(model)
	}
	// Keep s.titleModel for backward compatibility or direct usage if any
	s.titleModel = model
	if model != nil {
		log.Printf("✅ AgentChatService: Title model set (%s/%s)", model.Provider(), model.Model())
	}
}

// SetSummaryModel sets the summary generation model
func (s *AgentChatService) SetSummaryModel(model fantasy.LanguageModel) {
	s.summaryModel = model
	if model != nil {
		log.Printf("✅ AgentChatService: Summary model set (%s/%s)", model.Provider(), model.Model())
	}
}

// GetToolRegistry returns the tool registry for external configuration
func (s *AgentChatService) GetToolRegistry() *tools.ToolRegistry {
	return s.toolRegistry
}

// RegisterMemoryTool registers the search_memory tool for recalling stored memories
// Also stores reference to memoryIntegration for auto-storing conversations
func (s *AgentChatService) RegisterMemoryTool(memoryIntegration *MemoryIntegration) error {

	if memoryIntegration == nil {
		return nil
	}
	s.memoryIntegration = memoryIntegration
	if err := memoryIntegration.RegisterMemoryTool(s.toolRegistry); err != nil {
		return err
	}
	log.Printf("✅ AgentChatService: Memory tool registered (search_memory)")
	return nil
}

// getOrCreateSession gets an existing session or creates a new one with DB persistence
func (s *AgentChatService) getOrCreateSession(ctx context.Context, req ChatRequest) (*AgentSession, error) {
	s.sessionsMutex.Lock()
	defer s.sessionsMutex.Unlock()

	// 1. Check in-memory cache first
	if session, exists := s.sessions[req.SessionID]; exists {
		log.Printf("♻️  Reusing cached session: %s", req.SessionID)
		// Update tool names if changed
		session.ToolNames = s.collectToolNames(ctx, req)
		return session, nil
	}

	// 2. Try to load from database
	dbSession, dbMessages, err := s.loadSessionFromDB(ctx, req.SessionID, req.UserID)
	if err == nil {
		// Session exists in DB - reconstruct from history
		log.Printf("📂 Loading session from DB: %s (%d messages)", req.SessionID, len(dbMessages))

		// Convert DB messages to message format
		yzmaMessages := make([]fantasy.Message, 0, len(dbMessages))
		for _, dbMsg := range dbMessages {
			if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
				yzmaMessages = append(yzmaMessages, msg)
			}
		}

		// Collect tool names for yzma
		toolNames := s.collectToolNames(ctx, req)

		// Create session with history
		session := &AgentSession{
			SessionID:       req.SessionID,
			UserID:          req.UserID,
			Messages:        yzmaMessages,
			KnowledgeBaseID: req.KnowledgeBaseID,
			ToolNames:       toolNames,
			Context:         req.Context,
			CreatedAt:       dbSession.CreatedAt,
			UpdatedAt:       dbSession.UpdatedAt,
			DBSession:       dbSession,
		}

		s.sessions[req.SessionID] = session

		log.Printf("✅ Reconstructed session from DB: %s (KB: %s, History: %d msgs, Tools: %v)",
			req.SessionID, req.KnowledgeBaseID, len(yzmaMessages), toolNames)

		return session, nil
	}

	// 3. Session doesn't exist - create new one
	log.Printf("🆕 Creating new session: %s", req.SessionID)

	// Create session in DB (handle race condition with UNIQUE constraint)
	dbSession, err = s.createSessionInDB(ctx, req.SessionID, req.KnowledgeBaseID)
	if err != nil {
		// Check if error is due to UNIQUE constraint (race condition)
		// Must NOT be FOREIGN KEY constraint (which is a real error, not race condition)
		errStr := err.Error()
		isUniqueConstraint := strings.Contains(errStr, "UNIQUE constraint failed")
		isForeignKey := strings.Contains(errStr, "FOREIGN KEY")
		if isUniqueConstraint && !isForeignKey {
			// Another process created the session - retry loading with exponential backoff
			log.Printf("⚠️  Race condition detected, retrying load from DB...")

			var dbMessages []db.Message
			maxRetries := 3
			for i := 0; i < maxRetries; i++ {
				// Wait a bit for the other process to commit
				time.Sleep(time.Duration(10*(i+1)) * time.Millisecond)

				dbSession, dbMessages, err = s.loadSessionFromDB(ctx, req.SessionID, req.UserID)
				if err == nil {
					log.Printf("✅ Successfully loaded session after %d retries", i+1)
					break
				}

				if i < maxRetries-1 {
					log.Printf("⏳ Retry %d/%d: session not yet available, waiting...", i+1, maxRetries)
				}
			}

			if err != nil {
				return nil, fmt.Errorf("failed to load session after race condition (tried %d times): %w", maxRetries, err)
			}

			// Convert DB messages to message format
			yzmaMessages := make([]fantasy.Message, 0, len(dbMessages))
			for _, dbMsg := range dbMessages {
				if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
					yzmaMessages = append(yzmaMessages, msg)
				}
			}

			// Collect tool names
			toolNames := s.collectToolNames(ctx, req)

			// Create session with history
			session := &AgentSession{
				SessionID:       req.SessionID,
				UserID:          req.UserID,
				Messages:        yzmaMessages,
				KnowledgeBaseID: req.KnowledgeBaseID,
				ToolNames:       toolNames,
				Context:         req.Context,
				CreatedAt:       dbSession.CreatedAt,
				UpdatedAt:       dbSession.UpdatedAt,
				DBSession:       dbSession,
			}

			s.sessions[req.SessionID] = session

			log.Printf("✅ Recovered from race condition: %s", req.SessionID)
			return session, nil
		}

		// Other error - fail
		return nil, fmt.Errorf("failed to create session in DB: %w", err)
	}

	// Collect tool names for yzma
	toolNames := s.collectToolNames(ctx, req)

	// Create in-memory session
	session := &AgentSession{
		SessionID:       req.SessionID,
		UserID:          req.UserID,
		Messages:        make([]fantasy.Message, 0),
		KnowledgeBaseID: req.KnowledgeBaseID,
		ToolNames:       toolNames,
		Context:         req.Context,
		CreatedAt:       dbSession.CreatedAt,
		UpdatedAt:       dbSession.UpdatedAt,
		DBSession:       dbSession,
	}

	s.sessions[req.SessionID] = session

	log.Printf("✅ Created new session: %s (KB: %s, Tools: %v)",
		req.SessionID, req.KnowledgeBaseID, toolNames)

	return session, nil
}

// collectToolNames collects tool names for the session based on request
// If no tools specified, returns nil which means "use all registered tools"
func (s *AgentChatService) collectToolNames(ctx context.Context, req ChatRequest) []string {
	var toolNames []string

	// Add KB search tool if KB is specified
	if req.KnowledgeBaseID != "" {
		// Register KB tool to registry if not exists
		if err := s.registerKBSearchTool(ctx, req.KnowledgeBaseID); err != nil {
			log.Printf("⚠️  Warning: Failed to register KB tool: %v", err)
		} else {
			kb, err := s.kbService.GetKnowledgeBase(ctx, req.KnowledgeBaseID)
			if err == nil {
				toolNames = append(toolNames, fmt.Sprintf("search_%s", kb.Name))
			}
		}
	}

	// Add requested tools
	toolNames = append(toolNames, req.Tools...)

	// If no tools specified, return nil to use all registered tools
	// This allows LLM to use any available tool including lobe-image-describe
	if len(toolNames) == 0 {
		return nil
	}

	return toolNames
}

// detectLanguage detects the language of the given text using lingua-go
// Returns the detected language name in English (e.g., "Indonesian", "English", "Japanese")
// Falls back to "English" if detection fails or confidence is too low
func (s *AgentChatService) detectLanguage(text string) string {
	if text == "" {
		return "English"
	}

	// Detect language with confidence
	detectedLang, exists := s.languageDetector.DetectLanguageOf(text)
	if !exists {
		log.Printf("🌐 Language detection: No confident match, defaulting to English")
		return "English"
	}

	langName := detectedLang.String()
	log.Printf("🌐 Language detected: %s", langName)
	return langName
}

// getAgentSystemRole fetches the agent's system role from database and builds base instruction
// Returns default system prompt with agent's custom system_role appended if available
func (s *AgentChatService) getAgentSystemRole(sessionID string, currentTime string, language string) string {
	// 1. Construct standard base instruction (always included)
	base := fmt.Sprintf(`You are kawai AI assistant with kawai model. %s

<response_language>
IMPORTANT: The user's message is detected to be in %s. You MUST respond in %s to match the user's language.
If the user writes in a specific language, always respond in that same language.
</response_language>

`, currentTime, language, language)

	// 2. Try to get agent for this session
	ctx := context.Background()
	agent, err := s.db.Queries().GetAgentBySessionId(ctx, sessionID)

	// 3. Append agent's system role if available
	if err == nil && agent.SystemRole.Valid && agent.SystemRole.String != "" {
		log.Printf("🤖 Appending agent's custom system role (%d chars)", len(agent.SystemRole.String))
		return base + fmt.Sprintf("\n%s\n\n", agent.SystemRole.String)
	}

	// Log fallback
	if err != nil {
		log.Printf("⚠️  Could not fetch agent for session %s: %v, using default system prompt", sessionID, err)
	} else {
		log.Printf("ℹ️  Agent has no custom system role, using default system prompt")
	}

	return base
}

// buildSystemPrompt builds the system prompt string for fantasy.Agent
// This is optimized for use with fantasy.WithSystemPrompt() which handles
// system prompt injection internally. Returns just the prompt string.
// The userMessage parameter is used to detect the user's language for response.
func (s *AgentChatService) buildSystemPrompt(session *AgentSession, memoryContext string, userMessage string) string {
	// Get current time for LLM awareness
	now := time.Now()
	currentTime := fmt.Sprintf("Current date and time: %s (%s)",
		now.Format("Monday, January 2, 2006 15:04:05"),
		now.Format("2006-01-02T15:04:05-07:00"))

	// Detect user message language
	detectedLanguage := s.detectLanguage(userMessage)

	// Build base instruction using agent's system role or default
	baseInstruction := s.getAgentSystemRole(session.SessionID, currentTime, detectedLanguage)

	// Inject summary if exists
	if session.Context != nil {
		if historySummary, ok := session.Context["history_summary"].(string); ok && historySummary != "" {
			summaryContext := fmt.Sprintf(`
<chat_history_summary>
<docstring>Previous conversation summary (older messages have been compressed):</docstring>
<summary>%s</summary>
</chat_history_summary>

`, historySummary)
			baseInstruction += summaryContext
			log.Printf("📋 Injected history summary into system prompt (%d chars)", len(historySummary))
		}
	}

	// Inject memory context (Hybrid Context) if exists
	if memoryContext != "" {
		memorySection := fmt.Sprintf(`
<relevant_memories>
<docstring>Relevant information from past conversations (Hybrid Context):</docstring>
%s
</relevant_memories>

`, memoryContext)
		baseInstruction += memorySection
		log.Printf("🧠 Injected hybrid memory context into system prompt (%d chars)", len(memoryContext))
	}

	if session.KnowledgeBaseID != "" {
		baseInstruction += "You have access to a knowledge base. Use the search tool to find relevant information before answering questions. "
	}

	// Apply reasoning mode to instruction
	instruction := s.reasoningConfig.GetSystemPrompt(baseInstruction)

	log.Printf("🧠 Building system prompt with reasoning mode: %s", s.reasoningConfig.Mode)
	log.Printf("🌐 Response language set to: %s", detectedLanguage)
	log.Printf("📝 System prompt length: %d chars", len(instruction))

	return instruction
}

// getHistoryMessages returns message history from session, excluding system messages
// This is optimized for use with fantasy.Agent which handles system prompt separately
func (s *AgentChatService) getHistoryMessages(session *AgentSession) []fantasy.Message {
	if len(session.Messages) == 0 {
		return nil
	}

	// Filter out system messages - fantasy.Agent handles system prompt via WithSystemPrompt()
	history := make([]fantasy.Message, 0, len(session.Messages))
	for _, msg := range session.Messages {
		if types.GetMessageRole(msg) != "system" {
			history = append(history, msg)
		}
	}
	return history
}

// registerKBSearchTool registers a knowledge base search tool to the yzma registry
func (s *AgentChatService) registerKBSearchTool(ctx context.Context, kbID string) error {
	kb, err := s.kbService.GetKnowledgeBase(ctx, kbID)
	if err != nil {
		return err
	}

	toolName := fmt.Sprintf("search_%s", kb.Name)

	// Check if already registered
	if _, exists := s.toolRegistry.Get(toolName); exists {
		return nil // Already registered
	}

	// Create tool using SimpleTool
	kbService := s.kbService
	tool := tools.NewSimpleTool(tools.SimpleToolConfig{
		Name:        toolName,
		Description: fmt.Sprintf("Search the %s knowledge base for relevant information", kb.Name),
		Parameters: map[string]any{
			"query": map[string]any{"type": "string", "description": "The search query to find relevant information"},
			"top_k": map[string]any{"type": "integer", "description": "Number of results to return (default: 5)"},
		},
		Required: []string{"query"},
		Parallel: true, // Safe to run in parallel - read-only search
		Executor: func(execCtx context.Context, args map[string]string) (string, error) {
			query := args["query"]
			if query == "" {
				return "", fmt.Errorf("query parameter is required")
			}

			topK := 5
			if topKStr, ok := args["top_k"]; ok && topKStr != "" {
				if n, err := fmt.Sscanf(topKStr, "%d", &topK); err != nil || n != 1 {
					topK = 5
				}
			}

			docs, err := kbService.QueryKnowledgeBase(execCtx, kbID, query, topK)
			if err != nil {
				return "", fmt.Errorf("KB search failed: %w", err)
			}

			result := map[string]interface{}{
				"found": len(docs),
				"results": func() []map[string]interface{} {
					results := make([]map[string]interface{}, len(docs))
					for i, doc := range docs {
						results[i] = map[string]interface{}{
							"content":  doc.Content,
							"metadata": doc.Metadata,
						}
					}
					return results
				}(),
			}

			resultJSON, _ := json.Marshal(result)
			return string(resultJSON), nil
		},
	})

	return s.toolRegistry.Register(tool)
}

// stripThinkTags removes <think>...</think> blocks from the text using regex
func stripThinkTags(text string) string {
	// First, try to remove complete <think>...</think> blocks
	re := regexp.MustCompile(`(?s)<think>.*?</think>`)
	cleaned := re.ReplaceAllString(text, "")

	// If <think> tag still exists (incomplete/unclosed), remove everything from <think> onwards
	if strings.Contains(cleaned, "<think>") {
		idx := strings.Index(cleaned, "<think>")
		cleaned = cleaned[:idx]
	}

	return strings.TrimSpace(cleaned)
}

// createTopicForSessionSync creates a topic synchronously and returns the topicID
// Phase 4: Used to create topic before first message so we have topicID for message saving
func (s *AgentChatService) createTopicForSessionSync(ctx context.Context, sessionID string) (string, error) {
	// Check if topic already exists for this session
	// Check if topic already exists for this session
	count, err := s.db.Queries().CountTopicsBySession(ctx, sql.NullString{String: sessionID, Valid: true})
	if err != nil {
		return "", fmt.Errorf("failed to check existing topics: %w", err)
	}

	if count > 0 {
		// Topic already exists - find and return it
		// TODO: Add GetTopicBySession query to SQLC if needed
		// For now, return empty string and let it be created with title later
		return "", fmt.Errorf("topic already exists for session")
	}

	// Create topic with placeholder title
	topicID := uuid.New().String()
	now := time.Now().UnixMilli()

	// Use sessionID as is (don't convert "inbox" to NULL)
	sessionIDForDB := sql.NullString{String: sessionID, Valid: true}

	_, err = s.db.Queries().CreateTopic(ctx, db.CreateTopicParams{
		ID:             topicID,
		Title:          sql.NullString{String: "New Conversation", Valid: true},
		Favorite:       0,
		SessionID:      sessionIDForDB,
		GroupID:        sql.NullString{},
		HistorySummary: sql.NullString{},
		Metadata:       sql.NullString{},
		CreatedAt:      now,
		UpdatedAt:      now,
	})

	if err != nil {
		return "", fmt.Errorf("failed to create topic: %w", err)
	}

	return topicID, nil
}

// convertDBMessageToYzma converts a database message to native message
// Returns the message and a boolean indicating if conversion was successful
func convertDBMessageToYzma(dbMsg *db.Message) (fantasy.Message, bool) {
	role := dbMsg.Role
	content := ""
	if dbMsg.Content.Valid {
		content = dbMsg.Content.String
	}

	// Check for tool calls
	if dbMsg.Tools.Valid && dbMsg.Tools.String != "" {
		var toolCalls []fantasy.ToolCall
		if err := json.Unmarshal([]byte(dbMsg.Tools.String), &toolCalls); err == nil && len(toolCalls) > 0 {
			return types.NewToolCallMessage(toolCalls), true
		}
	}

	// Check for tool response
	if role == "tool" && content != "" {
		return types.NewToolResultMessage("", "", content), true
	}

	// Skip empty messages
	if role == "" && content == "" {
		return fantasy.Message{}, false
	}

	// Regular chat message
	return fantasy.Message{
		Role:    fantasy.MessageRole(role),
		Content: []fantasy.MessagePart{fantasy.TextPart{Text: content}},
	}, true
}

// loadSessionFromDB loads a session from database
func (s *AgentChatService) loadSessionFromDB(ctx context.Context, sessionID, userID string) (*db.Session, []db.Message, error) {
	dbSession, err := s.db.Queries().GetSession(ctx, sessionID)
	if err != nil {
		return nil, nil, fmt.Errorf("session not found in DB: %w", err)
	}

	dbMessages, err := s.db.Queries().ListMessagesBySession(ctx, db.ListMessagesBySessionParams{
		SessionID: sql.NullString{String: dbSession.ID, Valid: true},
		Limit:     1000, // Load up to 1000 messages
		Offset:    0,
	})
	if err != nil {
		// If messages query fails, still return session
		log.Printf("Warning: Failed to load messages for session %s: %v", sessionID, err)
		return &dbSession, nil, nil
	}

	return &dbSession, dbMessages, nil
}

// createSessionInDB creates a new session in database
func (s *AgentChatService) createSessionInDB(ctx context.Context, sessionID, kbID string) (*db.Session, error) {
	now := time.Now().UnixMilli()

	params := db.CreateSessionParams{
		ID:        sessionID,
		Type:      sql.NullString{String: "agent", Valid: true},
		Pinned:    0,
		CreatedAt: now,
		UpdatedAt: now,
	}

	// Set title based on KB if available
	if kbID != "" {
		kb, err := s.kbService.GetKnowledgeBase(ctx, kbID)
		if err == nil {
			params.Title = sql.NullString{
				String: fmt.Sprintf("Chat with %s", kb.Name),
				Valid:  true,
			}
		}
	}

	if !params.Title.Valid {
		params.Title = sql.NullString{String: "New Conversation", Valid: true}
	}

	dbSession, err := s.db.Queries().CreateSession(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to create session in DB: %w", err)
	}

	return &dbSession, nil
}

// updateSessionTimestamp updates the session's updated_at timestamp
func (s *AgentChatService) updateSessionTimestamp(ctx context.Context, sessionID string) error {
	now := time.Now().UnixMilli()

	// Get current session
	dbSession, err := s.db.Queries().GetSession(ctx, sessionID)
	if err != nil {
		return fmt.Errorf("session not found: %w", err)
	}

	// Update timestamp
	_, err = s.db.Queries().UpdateSession(ctx, db.UpdateSessionParams{
		Title:           dbSession.Title,
		Description:     dbSession.Description,
		Avatar:          dbSession.Avatar,
		BackgroundColor: dbSession.BackgroundColor,
		GroupID:         dbSession.GroupID,
		Pinned:          dbSession.Pinned,
		UpdatedAt:       now,
		ID:              sessionID,
	})

	return err
}

// validateModelForReasoningMode checks if the currently loaded model is appropriate
func (s *AgentChatService) validateModelForReasoningMode() error {
	modelPath := s.libService.GetLoadedChatModel()
	if modelPath == "" {
		return fmt.Errorf("no model loaded")
	}

	return s.reasoningConfig.ValidateModelForMode(modelPath)
}

// switchToRecommendedModel loads the recommended model for current reasoning mode
func (s *AgentChatService) switchToRecommendedModel() error {
	recommendedModel := s.reasoningConfig.GetRecommendedModel()

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	modelsDir := filepath.Join(homeDir, ".llama-cpp", "models")
	modelPath := filepath.Join(modelsDir, recommendedModel)

	log.Printf("🔄 Switching to recommended model for %s mode: %s", s.reasoningConfig.Mode, recommendedModel)

	if err := s.libService.LoadChatModel(modelPath); err != nil {
		return fmt.Errorf("failed to load recommended model: %w", err)
	}

	// Note: llamaLM from provider uses libService internally, so no need to recreate

	log.Printf("✅ Successfully switched to %s", recommendedModel)
	return nil
}

// ============================================================================
// History Summary Functions
// ============================================================================

// autoSummarizeIfNeeded checks conditions and triggers summary automatically
// Runs in background goroutine, does not block chat response
func (s *AgentChatService) autoSummarizeIfNeeded(ctx context.Context, session *AgentSession, topicID string) {
	if topicID == "" {
		return // No topic, no summary
	}

	// 1. Check if reasoning mode supports summarization
	threshold := s.reasoningConfig.GetSummaryThreshold()
	if threshold == 0 {
		return // Verbose mode doesn't need summary (3-5 turns only)
	}

	// 2. Check turn count
	turnCount := len(session.Messages) / 2
	if turnCount < threshold {
		return // Not enough turns yet
	}

	// 3. Check if we already summarized recently
	topic, err := s.db.Queries().GetTopic(ctx, topicID)
	if err != nil {
		log.Printf("⚠️  autoSummarize: Failed to get topic: %v", err)
		return
	}

	// If summary exists, this will be handled by incrementalSummarizeIfNeeded()
	if topic.HistorySummary.Valid && topic.HistorySummary.String != "" {
		return // Summary already exists, incremental will handle updates
	}

	// 4. Get messages from database (not from session, could be stale)
	messages, err := s.db.Queries().GetMessagesByTopicId(ctx, sql.NullString{String: topicID, Valid: true})
	if err != nil || len(messages) < 4 {
		log.Printf("⚠️  autoSummarize: Not enough messages to summarize: %d", len(messages))
		return
	}

	// 5. Determine which messages to summarize
	// Keep recent messages based on reasoning mode
	keepCount := s.getKeepMessageCount()
	if len(messages) <= keepCount {
		return // Not enough messages to warrant summary
	}

	oldMessages := messages[:len(messages)-keepCount]

	// 6. Convert to message format
	yzmaMessages := make([]fantasy.Message, 0, len(oldMessages))
	for _, dbMsg := range oldMessages {
		if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
			yzmaMessages = append(yzmaMessages, msg)
		}
	}

	if len(yzmaMessages) < 2 {
		return // Need at least 2 messages (1 turn) to summarize
	}

	// 7. Generate summary (this is already in background goroutine)
	log.Printf("🔄 Auto-generating summary for topic %s (%d old messages, keeping %d recent)",
		topicID, len(yzmaMessages), keepCount)

	summary, err := s.generateHistorySummary(ctx, yzmaMessages)
	if err != nil {
		log.Printf("❌ Auto-summary failed: %v", err)
		return
	}

	// 8. Save summary to database
	now := time.Now().UnixMilli()
	metadata := fmt.Sprintf(`{"summarized_at":%d,"message_count":%d,"reasoning_mode":"%s"}`,
		now, len(yzmaMessages), s.reasoningConfig.Mode)

	_, err = s.db.Queries().UpdateTopic(ctx, db.UpdateTopicParams{
		Title:          topic.Title,
		HistorySummary: sql.NullString{String: summary, Valid: true},
		Metadata: sql.NullString{
			String: metadata,
			Valid:  true,
		},
		UpdatedAt: now,
		ID:        topicID,
	})

	if err != nil {
		log.Printf("❌ Failed to save auto-summary: %v", err)
	} else {
		log.Printf("✅ Auto-summary completed for topic %s (compressed %d messages into %d chars)",
			topicID, len(yzmaMessages), len(summary))

		// Emit subtle event to frontend (optional: show small toast or indicator)
		if s.app != nil {
			s.app.Event.Emit("chat:summary:auto-complete", map[string]interface{}{
				"topic_id":       topicID,
				"message_count":  len(yzmaMessages),
				"summary_length": len(summary),
			})
		}
	}
}

// getKeepMessageCount returns how many recent messages to keep (not summarize)
func (s *AgentChatService) getKeepMessageCount() int {
	switch s.reasoningConfig.Mode {
	case ReasoningDisabled:
		return 20 // Keep last 20 messages (10 turns)
	case ReasoningEnabled:
		return 12 // Keep last 12 messages (6 turns)
	case ReasoningVerbose:
		return 6 // Keep last 6 messages (3 turns) - but won't reach here
	default:
		return 16
	}
}

// generateHistorySummary generates summary using summaryModel
// ChainLanguageModel handles fallback internally if configured
func (s *AgentChatService) generateHistorySummary(ctx context.Context, messages []fantasy.Message) (string, error) {
	if len(messages) == 0 {
		return "", fmt.Errorf("no messages to summarize")
	}

	// Check if summary model is configured
	if s.summaryModel == nil {
		return "", fmt.Errorf("summary model not configured")
	}

	// Build summary prompt
	systemPrompt := `You're an assistant who's good at extracting key takeaways from conversations and summarizing them. 

Rules:
- Summarize the conversation in the user's original language
- Focus on key decisions, actions, and outcomes
- Maintain context for future conversation continuation
- Maximum 400 tokens
- Output ONLY the summary text, nothing else`

	// Build conversation text
	var conversationText string
	for _, msg := range messages {
		role := types.GetMessageRole(msg)
		text := types.GetMessageText(msg)
		if text != "" {
			conversationText += fmt.Sprintf("%s: %s\n\n", role, text)
		}
	}

	conversationContent := fmt.Sprintf(`<chat_history>
%s
</chat_history>

Please summarize the above conversation and retain key information. The summarized content will be used as context for subsequent prompts.`, conversationText)

	// Create messages for summary generation
	summaryMessages := fantasy.Prompt{
		fantasy.NewSystemMessage(systemPrompt),
		fantasy.NewUserMessage(conversationContent),
	}

	// Use summaryModel directly (ChainLanguageModel handles fallback)
	resp, err := s.summaryModel.Generate(ctx, fantasy.Call{Prompt: summaryMessages})
	if err != nil {
		return "", fmt.Errorf("summary generation failed: %w", err)
	}

	// Clean up response
	summary := strings.TrimSpace(resp.Content.Text())

	// Strip <think> tags if present (for reasoning models)
	if strings.Contains(summary, "<think>") {
		log.Printf("⚠️  WARNING: Summary contains <think> tags, stripping...")
		summary = stripThinkTags(summary)
	}

	if summary == "" {
		return "", fmt.Errorf("empty summary generated")
	}

	log.Printf("✅ Summary generated (%d chars)", len(summary))
	return summary, nil
}

// incrementalSummarizeIfNeeded checks if existing summary needs update with new messages
// Runs in background goroutine, does not block chat response
func (s *AgentChatService) incrementalSummarizeIfNeeded(ctx context.Context, session *AgentSession, topicID string) {
	if topicID == "" {
		return // No topic, no summary
	}

	// 1. Check if reasoning mode supports incremental summarization
	threshold := s.reasoningConfig.GetIncrementalSummaryThreshold()
	if threshold == 0 {
		return // Verbose mode doesn't use incremental summary
	}

	// 2. Get topic with existing summary
	topic, err := s.db.Queries().GetTopic(ctx, topicID)
	if err != nil {
		return // Topic not found
	}

	// 3. Check if summary exists (incremental only works if base summary exists)
	if !topic.HistorySummary.Valid || topic.HistorySummary.String == "" {
		return // No existing summary, nothing to update
	}

	// 4. Parse metadata to get summarized message count
	var metadata struct {
		SummarizedMessageCount int   `json:"summarized_message_count"`
		SummaryVersion         int   `json:"summary_version"`
		InitialSummaryAt       int64 `json:"initial_summary_at"`
	}

	if topic.Metadata.Valid && topic.Metadata.String != "" {
		if err := json.Unmarshal([]byte(topic.Metadata.String), &metadata); err != nil {
			log.Printf("⚠️  incrementalSummarize: Failed to parse metadata: %v", err)
			return
		}
	}

	// 5. Get all messages from database
	allMessages, err := s.db.Queries().GetMessagesByTopicId(ctx, sql.NullString{String: topicID, Valid: true})
	if err != nil {
		log.Printf("⚠️  incrementalSummarize: Failed to get messages: %v", err)
		return
	}

	// 6. Count new messages since last summary
	newMessageCount := len(allMessages) - metadata.SummarizedMessageCount
	if newMessageCount < threshold*2 { // *2 because 1 turn = 2 messages
		return // Not enough new messages yet
	}

	log.Printf("🔄 Re-summarizing topic %s (v%d → v%d, %d new messages)",
		topicID, metadata.SummaryVersion, metadata.SummaryVersion+1, newMessageCount)

	// 7. Load existing summary
	existingSummary := topic.HistorySummary.String

	// 8. Get new messages to incorporate
	newMessages := allMessages[metadata.SummarizedMessageCount:]
	keepCount := s.getKeepMessageCount()

	// Make sure we have messages to summarize
	if len(newMessages) <= keepCount {
		return // All new messages are in "keep" range, nothing to summarize
	}

	messagesToSummarize := newMessages[:len(newMessages)-keepCount]

	// 9. Convert DB messages to messages
	yzmaMessages := make([]fantasy.Message, 0, len(messagesToSummarize))
	for _, dbMsg := range messagesToSummarize {
		if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
			yzmaMessages = append(yzmaMessages, msg)
		}
	}

	if len(yzmaMessages) == 0 {
		return // No valid messages to summarize
	}

	// 10. Generate merged summary
	mergedSummary, err := s.generateIncrementalSummary(ctx, existingSummary, yzmaMessages)
	if err != nil {
		log.Printf("❌ Incremental summary failed: %v", err)
		return
	}

	// 11. Update metadata
	if metadata.InitialSummaryAt == 0 {
		metadata.InitialSummaryAt = time.Now().UnixMilli()
	}

	newMetadata := map[string]interface{}{
		"summary_version":          metadata.SummaryVersion + 1,
		"last_summarized_at":       time.Now().UnixMilli(),
		"summarized_message_count": len(allMessages) - keepCount,
		"initial_summary_at":       metadata.InitialSummaryAt,
		"reasoning_mode":           string(s.reasoningConfig.Mode),
	}

	metadataJSON, err := json.Marshal(newMetadata)
	if err != nil {
		log.Printf("⚠️  Failed to marshal metadata: %v", err)
		metadataJSON = []byte("{}")
	}

	// 12. Save updated summary to database
	_, err = s.db.Queries().UpdateTopic(ctx, db.UpdateTopicParams{
		ID:             topicID,
		Title:          topic.Title,
		HistorySummary: sql.NullString{String: mergedSummary, Valid: true},
		Metadata:       sql.NullString{String: string(metadataJSON), Valid: true},
		UpdatedAt:      time.Now().UnixMilli(),
	})

	if err != nil {
		log.Printf("❌ Failed to save incremental summary: %v", err)
		return
	}

	log.Printf("✅ Incremental summary v%d completed (%d total messages compressed)",
		newMetadata["summary_version"], newMetadata["summarized_message_count"])
}

// generateIncrementalSummary creates updated summary by merging existing summary with new messages
// Uses summaryModel directly (ChainLanguageModel handles fallback internally)
func (s *AgentChatService) generateIncrementalSummary(ctx context.Context, existingSummary string, newMessages []fantasy.Message) (string, error) {
	// Check if summary model is configured
	if s.summaryModel == nil {
		return "", fmt.Errorf("summary model not configured")
	}

	// Build conversation context from new messages
	var messagesText strings.Builder
	for i, msg := range newMessages {
		role := "User"
		if types.GetMessageRole(msg) == "assistant" {
			role = "Assistant"
		}
		text := types.GetMessageText(msg)
		if text != "" {
			messagesText.WriteString(fmt.Sprintf("%s: %s\n", role, text))
		}
		if i < len(newMessages)-1 {
			messagesText.WriteString("\n")
		}
	}

	// Build prompt for incremental summarization
	prompt := fmt.Sprintf(`You are a conversation summarizer. Your task is to UPDATE an existing summary with new information.

EXISTING SUMMARY:
%s

NEW MESSAGES TO INCORPORATE:
%s

INSTRUCTIONS:
1. Read the existing summary carefully
2. Read the new messages to identify new topics and developments
3. Create an UPDATED summary that:
   - Preserves important information from the existing summary
   - Adds new topics and details from recent messages
   - Maintains chronological flow (what happened first, then next)
   - Stays concise (maximum 400 tokens)
4. Use the same language as the original messages
5. Focus on key topics, decisions, and important information
6. DO NOT use <think> tags or any XML/HTML markup

UPDATED SUMMARY:`, existingSummary, messagesText.String())

	// Create messages for incremental summary
	summaryMessages := fantasy.Prompt{
		fantasy.NewUserMessage(prompt),
	}

	// Use summaryModel directly (ChainLanguageModel handles fallback)
	resp, err := s.summaryModel.Generate(ctx, fantasy.Call{Prompt: summaryMessages})
	if err != nil {
		return "", fmt.Errorf("failed to generate incremental summary: %w", err)
	}

	// Clean up response
	summary := strings.TrimSpace(resp.Content.Text())

	// Strip <think> tags if present
	if strings.Contains(summary, "<think>") {
		log.Printf("⚠️  WARNING: Incremental summary contains <think> tags, stripping...")
		summary = stripThinkTags(summary)
	}

	if summary == "" {
		return "", fmt.Errorf("empty incremental summary generated")
	}

	log.Printf("✅ Incremental summary generated (%d chars)", len(summary))
	return summary, nil
}
