/*
 * Copyright 2025 Veridium Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package services

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/kawai-network/veridium/internal/database"
	db "github.com/kawai-network/veridium/internal/database/generated"
	"github.com/kawai-network/veridium/internal/llama"
	"github.com/kawai-network/veridium/internal/llm"
	"github.com/kawai-network/veridium/pkg/yzma/tools"
	yzmabuiltin "github.com/kawai-network/veridium/pkg/yzma/tools/builtin"
	"github.com/kawai-network/veridium/types"
	"github.com/wailsapp/wails/v3/pkg/application"
)

// AgentChatService provides agent-based chat with RAG, tools, and context awareness
// This replaces/complements the existing LibraryChatService with Yzma-based capabilities
type AgentChatService struct {
	app         *application.App
	db          *database.Service
	libService  *llama.LibraryService
	yzmaModel   *llama.LlamaYzmaModel // Yzma model for all LLM operations (chat, title, summary)
	kbService   *KnowledgeBaseService
	ragWorkflow *RAGWorkflow

	// Vector search for file-based RAG (direct file attachments)
	vectorSearch *VectorSearchService

	// LLM Generator interface (for testing/mocking)
	llmGenerator llm.Provider

	// TaskRouter for multi-provider task distribution
	// Routes different tasks (chat, title, summary) to appropriate providers
	taskRouter *llm.TaskRouter

	// Yzma tool registry (replaces Eino tools)
	toolRegistry *tools.ToolRegistry

	// Phase 4: Thread management
	threadService *ThreadManagementService // Thread management service

	// Reasoning mode configuration
	reasoningConfig ReasoningConfig // Controls reasoning behavior

	// Utility models: use separate small & fast models for efficiency
	titleModelPath   string // Path to title generation model (optional, falls back to main model)
	summaryModelPath string // Path to summary generation model (optional, falls back to title/main model)

	// Session management (hybrid: DB + in-memory cache)
	sessions      map[string]*AgentSession // In-memory cache for active sessions
	sessionsMutex sync.RWMutex
}

// AgentSession represents an ongoing conversation with context
type AgentSession struct {
	SessionID       string
	UserID          string
	Messages        []types.Message // Native yzma messages
	KnowledgeBaseID string
	ToolNames       []string // Tool names to use for this session
	Context         map[string]any
	CreatedAt       int64
	UpdatedAt       int64
	DBSession       *db.Session // Link to DB session

	// Phase 4: Topic & Thread support
	TopicID  string // Current topic ID (may be auto-created)
	ThreadID string // Current thread ID (for branching)
}

// ChatRequest represents a chat request with agent capabilities
type ChatRequest struct {
	// Identity
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`

	// Message content
	Message string `json:"message"`

	// Message IDs (pre-generated by frontend for optimistic UI)
	MessageUserID      string `json:"message_user_id,omitempty"`      // Pre-generated user message ID
	MessageAssistantID string `json:"message_assistant_id,omitempty"` // Pre-generated assistant message ID

	// Context (Phase 4: Topic & Thread support)
	TopicID  string `json:"topic_id,omitempty"`  // Current topic (may be auto-created)
	ThreadID string `json:"thread_id,omitempty"` // Current thread (for branching)
	ParentID string `json:"parent_id,omitempty"` // Parent message (for threading)

	// File attachments (processed by FileProcessorService)
	FileIDs []string `json:"file_ids,omitempty"` // File IDs for RAG context retrieval

	// Configuration
	KnowledgeBaseID string         `json:"knowledge_base_id,omitempty"`
	Tools           []string       `json:"tools,omitempty"`
	Context         map[string]any `json:"context,omitempty"`
	Temperature     float32        `json:"temperature,omitempty"`
	MaxTokens       int            `json:"max_tokens,omitempty"`
	Stream          bool           `json:"stream,omitempty"`
}

// UIMessageRoleType represents the role of a message
type UIMessageRoleType string

const (
	UIMessageRoleUser       UIMessageRoleType = "user"
	UIMessageRoleSystem     UIMessageRoleType = "system"
	UIMessageRoleAssistant  UIMessageRoleType = "assistant"
	UIMessageRoleTool       UIMessageRoleType = "tool"
	UIMessageRoleSupervisor UIMessageRoleType = "supervisor"
	UIMessageRoleGroup      UIMessageRoleType = "group"
)

// MetaData represents metadata for messages/agents
type MetaData struct {
	Avatar          string   `json:"avatar,omitempty"`
	BackgroundColor string   `json:"backgroundColor,omitempty"`
	Description     string   `json:"description,omitempty"`
	Tags            []string `json:"tags,omitempty"`
	Title           string   `json:"title,omitempty"`
}

// ChatFileItem represents a file attachment
type ChatFileItem struct {
	Content  string `json:"content,omitempty"`
	FileType string `json:"fileType"`
	ID       string `json:"id"`
	Name     string `json:"name"`
	Size     int64  `json:"size"`
	URL      string `json:"url"`
}

// ChatImageItem represents an image attachment
type ChatImageItem struct {
	Alt string `json:"alt,omitempty"`
	ID  string `json:"id"`
	URL string `json:"url"`
}

// ChatVideoItem represents a video attachment
type ChatVideoItem struct {
	Cover string `json:"cover,omitempty"`
	ID    string `json:"id"`
	Name  string `json:"name,omitempty"`
	Size  int64  `json:"size,omitempty"`
	URL   string `json:"url"`
}

// ModelUsage represents token usage metrics
type ModelUsage struct {
	InputCachedTokens        int     `json:"inputCachedTokens,omitempty"`
	InputCacheMissTokens     int     `json:"inputCacheMissTokens,omitempty"`
	InputWriteCacheTokens    int     `json:"inputWriteCacheTokens,omitempty"`
	InputTextTokens          int     `json:"inputTextTokens,omitempty"`
	InputImageTokens         int     `json:"inputImageTokens,omitempty"`
	InputAudioTokens         int     `json:"inputAudioTokens,omitempty"`
	InputCitationTokens      int     `json:"inputCitationTokens,omitempty"`
	OutputTextTokens         int     `json:"outputTextTokens,omitempty"`
	OutputImageTokens        int     `json:"outputImageTokens,omitempty"`
	OutputAudioTokens        int     `json:"outputAudioTokens,omitempty"`
	OutputReasoningTokens    int     `json:"outputReasoningTokens,omitempty"`
	AcceptedPredictionTokens int     `json:"acceptedPredictionTokens,omitempty"`
	RejectedPredictionTokens int     `json:"rejectedPredictionTokens,omitempty"`
	TotalInputTokens         int     `json:"totalInputTokens,omitempty"`
	TotalOutputTokens        int     `json:"totalOutputTokens,omitempty"`
	TotalTokens              int     `json:"totalTokens,omitempty"`
	Cost                     float64 `json:"cost,omitempty"`
}

// ModelPerformance represents performance metrics
type ModelPerformance struct {
	TPS      float64 `json:"tps,omitempty"`
	TTFT     int64   `json:"ttft,omitempty"`
	Duration int64   `json:"duration,omitempty"`
	Latency  int64   `json:"latency,omitempty"`
}

// ModelReasoning represents reasoning/thinking content
type ModelReasoning struct {
	Content   string `json:"content,omitempty"`
	Duration  int64  `json:"duration,omitempty"`
	Signature string `json:"signature,omitempty"`
}

// ChatMessageError represents an error in a message
type ChatMessageError struct {
	Body    interface{} `json:"body,omitempty"`
	Message string      `json:"message"`
	Type    string      `json:"type"`
}

// MessageMetadata combines usage and performance metrics
type MessageMetadata struct {
	ModelUsage
	ModelPerformance
}

// ChatTTS represents text-to-speech data
type ChatTTS struct {
	ContentMd5 string `json:"contentMd5,omitempty"`
	File       string `json:"file,omitempty"`
	Voice      string `json:"voice,omitempty"`
}

// ChatTranslate represents translation data
type ChatTranslate struct {
	Content string `json:"content,omitempty"`
	From    string `json:"from,omitempty"`
	To      string `json:"to,omitempty"`
}

// ChatMessageExtra represents extra message fields
type ChatMessageExtra struct {
	FromModel    string         `json:"fromModel,omitempty"`
	FromProvider string         `json:"fromProvider,omitempty"`
	Translate    *ChatTranslate `json:"translate,omitempty"`
	TTS          *ChatTTS       `json:"tts,omitempty"`
}

// ChatToolResult represents tool execution result
type ChatToolResult struct {
	Content string      `json:"content"`
	Error   interface{} `json:"error,omitempty"`
	ID      string      `json:"id"`
	State   interface{} `json:"state,omitempty"`
}

// ChatToolPayload represents a tool call payload
type ChatToolPayload struct {
	APIName    string `json:"apiName"`
	Arguments  string `json:"arguments"`
	ID         string `json:"id"`
	Identifier string `json:"identifier"`
	Type       string `json:"type"`
}

// ChatFileChunk represents a file chunk from RAG system
type ChatFileChunk struct {
	FileID     string  `json:"fileId"`
	FileType   string  `json:"fileType"`
	FileURL    string  `json:"fileUrl"`
	Filename   string  `json:"filename"`
	ID         string  `json:"id"`
	Similarity float64 `json:"similarity,omitempty"`
	Text       string  `json:"text"`
}

// CitationItem represents a citation from search results
type CitationItem struct {
	Favicon string `json:"favicon,omitempty"`
	ID      string `json:"id,omitempty"`
	Title   string `json:"title,omitempty"`
	URL     string `json:"url"`
}

// GroundingSearch represents search grounding data for messages
type GroundingSearch struct {
	Citations     []CitationItem `json:"citations,omitempty"`
	SearchQueries []string       `json:"searchQueries,omitempty"`
}

// ChatToolPayloadWithResult combines tool payload with result
type ChatToolPayloadWithResult struct {
	ChatToolPayload
	Result *ChatToolResult `json:"result,omitempty"`
}

// ChatPluginPayload represents a plugin call payload
type ChatPluginPayload struct {
	APIName    string `json:"apiName"`
	Arguments  string `json:"arguments"`
	Identifier string `json:"identifier"`
	Type       string `json:"type"`
}

// AssistantContentBlock represents content block in grouped messages
type AssistantContentBlock struct {
	Content     string                      `json:"content"`
	FileList    []ChatFileItem              `json:"fileList,omitempty"`
	ID          string                      `json:"id"`
	ImageList   []ChatImageItem             `json:"imageList,omitempty"`
	Performance *ModelPerformance           `json:"performance,omitempty"`
	Tools       []ChatToolPayloadWithResult `json:"tools,omitempty"`
	Usage       *ModelUsage                 `json:"usage,omitempty"`
}

// UIChatMessage represents the response from agent (matches frontend/src/types/message/ui/chat.ts)
// This type is used for ALL message roles: user, assistant, tool, system, etc.
// For tool messages (role='tool'), use ToolCallID to link back to the tool call in assistant message.
type UIChatMessage struct {
	AgentID    string                  `json:"agentId,omitempty"`
	Children   []AssistantContentBlock `json:"children,omitempty"`
	ChunksList []ChatFileChunk         `json:"chunksList,omitempty"`
	Content    string                  `json:"content"`
	CreatedAt  int64                   `json:"createdAt"`
	Error      *ChatMessageError       `json:"error,omitempty"`
	Extra      *ChatMessageExtra       `json:"extra,omitempty"`
	FileList   []ChatFileItem          `json:"fileList,omitempty"`
	Files      []string                `json:"files,omitempty"` // deprecated
	GroupID    string                  `json:"groupId,omitempty"`
	ID         string                  `json:"id"`
	ImageList  []ChatImageItem         `json:"imageList,omitempty"`
	Meta       MetaData                `json:"meta"`
	Metadata   *MessageMetadata        `json:"metadata,omitempty"`

	ObservationID string            `json:"observationId,omitempty"`
	ParentID      string            `json:"parentId,omitempty"`
	Performance   *ModelPerformance `json:"performance,omitempty"`

	Plugin      *ChatPluginPayload `json:"plugin,omitempty"`
	PluginError interface{}        `json:"pluginError,omitempty"`
	PluginState interface{}        `json:"pluginState,omitempty"`

	QuotaID     string `json:"quotaId,omitempty"`
	RagQuery    string `json:"ragQuery,omitempty"`
	RagQueryID  string `json:"ragQueryId,omitempty"`
	RagRawQuery string `json:"ragRawQuery,omitempty"`

	Reasoning *ModelReasoning   `json:"reasoning,omitempty"`
	Role      UIMessageRoleType `json:"role"`
	Search    *GroundingSearch  `json:"search,omitempty"`

	SessionID  string `json:"sessionId,omitempty"`
	TargetID   string `json:"targetId,omitempty"`
	ThreadID   string `json:"threadId,omitempty"`
	ToolCallID string `json:"tool_call_id,omitempty"`

	Tools   []ChatToolPayload `json:"tools,omitempty"`
	TopicID string            `json:"topicId,omitempty"`
	TraceID string            `json:"traceId,omitempty"`

	UpdatedAt int64           `json:"updatedAt"`
	Usage     *ModelUsage     `json:"usage,omitempty"`
	VideoList []ChatVideoItem `json:"videoList,omitempty"`
}

// NewAgentChatService creates a new agent-based chat service
// Set threadService to nil to disable thread management
func NewAgentChatService(
	app *application.App,
	db *database.Service,
	libService *llama.LibraryService,
	kbService *KnowledgeBaseService,
	vectorSearch *VectorSearchService,
	threadService *ThreadManagementService,
) *AgentChatService {
	ragWorkflow := NewRAGWorkflow(kbService)

	// Initialize Yzma Tool Registry & Register Builtin Tools
	// Pass SQL DB for tools that need database access (e.g., image describe)
	toolRegistry := tools.NewToolRegistry()
	if err := yzmabuiltin.RegisterAllWithDB(toolRegistry, db.DB()); err != nil {
		log.Printf("⚠️  Warning: Failed to register yzma builtin tools: %v", err)
	} else {
		log.Printf("✅ AgentChatService: Yzma builtin tools registered")
	}

	// Create Yzma model with tool registry (used for all LLM operations)
	yzmaModel := llama.NewLlamaYzmaModel(libService, toolRegistry)

	// Auto-detect utility models for lightweight tasks
	titleModelPath := detectTitleGenerationModel(libService)
	summaryModelPath := detectSummaryGenerationModel(libService)

	// Create LLM provider adapter (wraps yzmaModel for interface compatibility)
	llmGenerator := NewLlamaProviderAdapter(yzmaModel)

	// Build TaskRouter with default dev config
	// This routes different tasks to appropriate providers
	devConfig := llm.GetDefaultDevConfig()
	taskRouter := llm.BuildTaskRouter(devConfig, toolRegistry, llmGenerator)

	service := &AgentChatService{
		app:              app,
		db:               db,
		libService:       libService,
		yzmaModel:        yzmaModel,
		llmGenerator:     llmGenerator,
		taskRouter:       taskRouter,
		kbService:        kbService,
		ragWorkflow:      ragWorkflow,
		vectorSearch:     vectorSearch,
		toolRegistry:     toolRegistry,
		threadService:    threadService,
		reasoningConfig:  DefaultReasoningConfig(), // Default: disabled (non-reasoning)
		titleModelPath:   titleModelPath,
		summaryModelPath: summaryModelPath,
		sessions:         make(map[string]*AgentSession),
	}

	if titleModelPath != "" {
		log.Printf("📝 Auto-detected title model: %s", filepath.Base(titleModelPath))
	} else {
		log.Printf("📝 No dedicated title model found, will use main chat model")
	}

	if summaryModelPath != "" {
		log.Printf("📋 Auto-detected summary model: %s", filepath.Base(summaryModelPath))
	} else {
		log.Printf("📋 No dedicated summary model found, will use main chat model")
	}

	return service
}

// SetLLMGenerator sets a custom LLM generator (useful for testing with mocks)
func (s *AgentChatService) SetLLMGenerator(generator llm.Provider) {
	s.sessionsMutex.Lock()
	defer s.sessionsMutex.Unlock()
	s.llmGenerator = generator
}

// GetLLMGenerator returns the current LLM generator
func (s *AgentChatService) GetLLMGenerator() llm.Provider {
	s.sessionsMutex.RLock()
	defer s.sessionsMutex.RUnlock()
	return s.llmGenerator
}

// SetTaskRouter sets a custom task router for multi-provider routing
func (s *AgentChatService) SetTaskRouter(router *llm.TaskRouter) {
	s.sessionsMutex.Lock()
	defer s.sessionsMutex.Unlock()
	s.taskRouter = router
	log.Printf("🔀 TaskRouter updated")
}

// GetTaskRouter returns the current task router
func (s *AgentChatService) GetTaskRouter() *llm.TaskRouter {
	s.sessionsMutex.RLock()
	defer s.sessionsMutex.RUnlock()
	return s.taskRouter
}

// detectTitleGenerationModel finds the smallest, fastest model for title generation
// Prefers utility models (Llama 3.2 1B/3B) which are optimized for quick tasks
// Reuses detectSummaryGenerationModel since both tasks need the same type of model
func detectTitleGenerationModel(libService *llama.LibraryService) string {
	return detectSummaryGenerationModel(libService)
}

// detectSummaryGenerationModel finds optimal model for summarization
// Strategy: Prefer small non-reasoning models (Llama 3.2 1B/3B, Mistral)
// These models are fast, don't generate <think> tags, and have good quality for utility tasks
func detectSummaryGenerationModel(libService *llama.LibraryService) string {
	models, err := libService.GetAvailableModels()
	if err != nil || len(models) == 0 {
		return ""
	}

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	modelsDir := filepath.Join(homeDir, ".llama-cpp", "models")

	var bestModel string
	var bestScore int

	for _, modelName := range models {
		modelPath := filepath.Join(modelsDir, modelName)
		nameLower := strings.ToLower(modelName)

		// Skip embedding models
		if strings.Contains(nameLower, "embedding") || strings.Contains(nameLower, "embed") {
			continue
		}

		// Get file size
		info, err := os.Stat(modelPath)
		if err != nil {
			continue
		}

		score := 0
		sizeMB := info.Size() / (1024 * 1024)

		// Prefer SMALL but not TOO small (1B-1.5B ideal for summary)
		// Summary needs slightly better quality than title
		if sizeMB >= 500 && sizeMB < 1000 {
			score += 100 // 1B models - BEST for summary (Llama 3.2 1B)
		} else if sizeMB >= 1000 && sizeMB < 2000 {
			score += 90 // 1.5B-3B models - good balance (Llama 3.2 3B)
		} else if sizeMB < 500 {
			score += 70 // 0.5B models - may be too simple
		} else if sizeMB < 4500 {
			score += 50 // 3B-7B models - slower, unnecessary (Mistral 7B)
		} else {
			score += 10 // 7B+ models - too slow for background task
		}

		// CRITICAL: Prefer non-reasoning models (NO <think> tags)
		if strings.Contains(nameLower, "llama-3.2-1b") || strings.Contains(nameLower, "llama_3.2_1b") {
			score += 100 // Llama 3.2 1B is BEST - fast, no think tags, good quality
		} else if strings.Contains(nameLower, "llama-3.2-3b") || strings.Contains(nameLower, "llama_3.2_3b") {
			score += 90 // Llama 3.2 3B is excellent - better quality
		} else if strings.Contains(nameLower, "llama") && !strings.Contains(nameLower, "3.2") {
			score += 70 // Other Llama models are okay
		} else if strings.Contains(nameLower, "mistral") {
			score += 60 // Mistral is decent
		} else if strings.Contains(nameLower, "gemma") {
			score += 50 // Gemma is okay
		} else if strings.Contains(nameLower, "phi") {
			score += 40 // Phi is acceptable
		} else if strings.Contains(nameLower, "qwen") {
			score -= 200 // AVOID Qwen - generates <think> tags in summary!
		} else if strings.Contains(nameLower, "deepseek") {
			score -= 150 // AVOID DeepSeek - reasoning model
		}

		// Prefer instruct/chat models
		if strings.Contains(nameLower, "instruct") || strings.Contains(nameLower, "chat") {
			score += 30
		}

		// Prefer Q4 quantization (good balance of quality & speed)
		if strings.Contains(nameLower, "q4") {
			score += 20
		}

		if score > bestScore {
			bestScore = score
			bestModel = modelPath
		}
	}

	return bestModel
}

// Chat processes a chat request and returns a response
func (s *AgentChatService) Chat(ctx context.Context, req ChatRequest) (*UIChatMessage, error) {
	// 1. Setup session, topic, and save user message using reusable helper
	// SetupSessionAndTopic handles:
	// - Get/create session
	// - Load history summary from DB
	// - Load thread messages
	// - Auto-create topic
	// - Add user message to session (in-memory)
	// - Save user message to DB
	setup, err := s.setupSessionAndTopic(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("failed to setup session/topic: %w", err)
	}
	session := setup.Session
	currentTopicID := setup.TopicID

	// 2. Validate model for current reasoning mode and auto-switch if needed
	// Note: This is NOT in SetupSessionAndTopic because it's specific to Chat()
	if err := s.ValidateModelForReasoningMode(); err != nil {
		log.Printf("⚠️  Model mismatch detected: %v", err)
		log.Printf("🔄 Auto-switching to recommended model...")
		if switchErr := s.SwitchToRecommendedModel(); switchErr != nil {
			log.Printf("❌ Failed to switch model: %v", switchErr)
			log.Printf("⚠️  Continuing with current model, but expect suboptimal performance")
		} else {
			log.Printf("✅ Successfully switched to recommended model")
		}
	}

	// Messages for agent (native yzma format)
	messagesToAgent := session.Messages

	// Prepare messages with system prompt
	messagesWithSystem := s.prepareMessagesWithSystemPrompt(messagesToAgent, session)

	// Use pre-generated assistant message ID from frontend, or generate new one
	assistantMsgID := req.MessageAssistantID
	if assistantMsgID == "" {
		assistantMsgID = uuid.New().String()
	}

	// Get LLM provider with requested tools
	// Use TaskRouter if configured, otherwise fallback to llmGenerator
	var llmWithTools llm.Provider
	if s.taskRouter != nil {
		llmWithTools = s.taskRouter.ChatWithTools(session.ToolNames)
		if llmWithTools == nil {
			llmWithTools = s.llmGenerator.WithTools(session.ToolNames)
		}
	} else {
		llmWithTools = s.llmGenerator.WithTools(session.ToolNames)
	}

	// Run agent with LLM generator (streaming or non-streaming)
	var finalMessage string
	var toolCalls []types.ToolCall
	var usage *types.LLMResponse
	var toolMessages []types.Message

	if req.Stream && s.app != nil {
		// Use streaming with agent loop
		resp, tms, streamErr := s.generateWithStreaming(ctx, session, assistantMsgID, messagesWithSystem, llmWithTools)
		if streamErr != nil {
			return nil, fmt.Errorf("streaming generation failed: %w", streamErr)
		}
		finalMessage = resp.Content
		toolCalls = resp.ToolCalls
		toolMessages = tms
	} else {
		// Use agent loop (non-streaming)
		resp, tms, runErr := llmWithTools.RunAgentLoop(ctx, messagesWithSystem, 10)
		if runErr != nil {
			return nil, fmt.Errorf("agent execution failed: %w", runErr)
		}

		finalMessage = resp.Content
		toolCalls = resp.ToolCalls
		toolMessages = tms
		usage = resp
	}

	// Add tool messages to session (for history)
	session.Messages = append(session.Messages, toolMessages...)

	// Note: Think tag stripping removed - proper model selection should prevent think tags
	// If reasoning mode is disabled, use non-reasoning models (Llama 3.2)
	// If reasoning mode is enabled, use reasoning models with /no_think (Qwen3)

	// Add assistant response to session
	if len(toolCalls) > 0 {
		session.Messages = append(session.Messages, types.NewToolCallMessage(toolCalls))
	} else {
		session.Messages = append(session.Messages, types.NewAssistantMessage(finalMessage))
	}

	// Monitor context usage and provide warnings/recommendations
	if usage != nil && usage.TotalTokens > 0 {
		contextSize := 16384 // Current context window size
		contextUsage := float64(usage.TotalTokens) / float64(contextSize)
		turnCount := len(session.Messages) / 2 // Approximate turn count (user + assistant pairs)

		log.Printf("📊 Context usage: %d/%d tokens (%.1f%%) after %d turns",
			usage.TotalTokens, contextSize, contextUsage*100, turnCount)

		// Warning at 50% usage
		if contextUsage > 0.5 && contextUsage <= 0.8 {
			log.Printf("⚠️  Context usage > 50%%. Consider switching to more efficient reasoning mode.")
			if s.reasoningConfig.Mode != ReasoningDisabled {
				log.Printf("💡 Recommendation: Switch to ReasoningDisabled (Llama 3.2) for longer conversations")
			}
		}

		// Critical warning at 80% usage
		if contextUsage > 0.8 {
			log.Printf("🚨 Context usage > 80%% Conversation may become unstable.")
			log.Printf("💡 Recommendations:")
			log.Printf("   1. Switch to ReasoningDisabled mode")
			log.Printf("   2. Summarize and truncate old messages")
			log.Printf("   3. Start a new conversation")
		}
	}

	// Phase 4: Generate topic title after first response
	// If we already created a placeholder topic, update it with LLM-generated title
	// We allow up to 4 messages (2 turns) to retry title generation if it failed or was skipped
	if len(session.Messages) >= 2 && len(session.Messages) <= 4 {
		log.Printf("📝 Checking if topic title needs update (msgs: %d, topic: %s)", len(session.Messages), currentTopicID)

		if currentTopicID != "" {
			// Update existing topic with LLM-generated title
			// This runs in background, so it won't block response
			err := s.updateTopicTitle(ctx, currentTopicID, session.UserID, session.Messages)
			if err != nil {
				log.Printf("⚠️  Warning: Failed to trigger topic title update: %v", err)
			} else {
				log.Printf("📝 Triggered background title update for topic %s", currentTopicID)
			}
		} else {
			// Topic was not created before - create it now with the actual conversation
			topicID, err := s.createTopicForSessionWithTitle(ctx, session.SessionID, session.UserID, session.Messages)
			if err != nil {
				log.Printf("⚠️  Warning: Failed to create topic with title: %v", err)
			} else {
				currentTopicID = topicID
				session.TopicID = topicID
				log.Printf("📝 Created topic with auto-generated title: %s", topicID)
			}
		}
	}

	// Save assistant message to DB with topic and thread IDs
	var assistantMsgForDB types.Message
	if len(toolCalls) > 0 {
		assistantMsgForDB = types.NewToolCallMessage(toolCalls)
	} else {
		assistantMsgForDB = types.NewAssistantMessage(finalMessage)
	}
	savedMsgID, err := s.saveYzmaMessageToDBWithID(ctx, assistantMsgForDB, session.SessionID, session.UserID, currentTopicID, req.ThreadID, assistantMsgID)
	if err != nil {
		log.Printf("⚠️  Warning: Failed to save assistant message to DB: %v", err)
		// Use the generated ID as fallback
		savedMsgID = assistantMsgID
	} else {
		log.Printf("💾 Saved assistant message: %s (topic: %s, thread: %s)", savedMsgID, currentTopicID, req.ThreadID)
		// Update assistantMsgID with the actual DB ID (should be the same as we passed it in)
		assistantMsgID = savedMsgID
	}

	// ✅ AUTO-TRIGGER SUMMARY (NON-BLOCKING)
	// This happens AFTER response is sent to user, so no blocking
	// Summary generation runs in background goroutine
	if currentTopicID != "" {
		go func() {
			bgCtx := context.Background()
			// First: Try initial summary creation (if no summary exists)
			s.autoSummarizeIfNeeded(bgCtx, session, currentTopicID, session.UserID)

			// Second: Try incremental summary update (if summary exists and enough new messages)
			s.incrementalSummarizeIfNeeded(bgCtx, session, currentTopicID, session.UserID)
		}()
	}

	// Emit streaming complete event (if streaming enabled)
	if req.Stream && s.app != nil {
		s.app.Event.Emit("chat:stream", map[string]interface{}{
			"type":       "complete",
			"session_id": session.SessionID,
			"message_id": assistantMsgID,
			"content":    finalMessage,
			"topic_id":   currentTopicID,
			"thread_id":  req.ThreadID,
		})
	}

	// Update session timestamp in DB
	if err := s.updateSessionTimestamp(ctx, session.SessionID, session.UserID); err != nil {
		log.Printf("⚠️  Warning: Failed to update session timestamp: %v", err)
	}

	// Phase 4: Return with all relevant IDs
	now := time.Now().UnixMilli()

	// Convert yzma ToolCalls to UI format
	var uiTools []ChatToolPayload
	if len(toolCalls) > 0 {
		uiTools = make([]ChatToolPayload, len(toolCalls))
		for i, tc := range toolCalls {
			argsJSON, _ := json.Marshal(tc.Function.Arguments)
			uiTools[i] = ChatToolPayload{
				ID:         fmt.Sprintf("%s_%d", assistantMsgID, i),
				APIName:    tc.Function.Name,
				Identifier: tc.Function.Name,
				Arguments:  string(argsJSON),
				Type:       tc.Type,
			}
		}
	}

	// Convert usage to UI format
	var uiUsage *ModelUsage
	if usage != nil {
		uiUsage = &ModelUsage{
			TotalInputTokens:  usage.PromptTokens,
			TotalOutputTokens: usage.CompletionTokens,
			TotalTokens:       usage.TotalTokens,
		}
	}

	return &UIChatMessage{
		ID:        assistantMsgID,
		SessionID: session.SessionID,
		TopicID:   currentTopicID,
		ThreadID:  req.ThreadID,
		Content:   finalMessage,
		Role:      UIMessageRoleAssistant,
		Tools:     uiTools,
		Usage:     uiUsage,
		Meta:      MetaData{},
		CreatedAt: now,
		UpdatedAt: now,
	}, nil
}

// getOrCreateSession gets an existing session or creates a new one with DB persistence
func (s *AgentChatService) getOrCreateSession(ctx context.Context, req ChatRequest) (*AgentSession, error) {
	s.sessionsMutex.Lock()
	defer s.sessionsMutex.Unlock()

	// 1. Check in-memory cache first
	if session, exists := s.sessions[req.SessionID]; exists {
		log.Printf("♻️  Reusing cached session: %s", req.SessionID)
		// Update tool names if changed
		session.ToolNames = s.collectToolNames(ctx, req)
		return session, nil
	}

	// 2. Try to load from database
	dbSession, dbMessages, err := s.loadSessionFromDB(ctx, req.SessionID, req.UserID)
	if err == nil {
		// Session exists in DB - reconstruct from history
		log.Printf("📂 Loading session from DB: %s (%d messages)", req.SessionID, len(dbMessages))

		// Convert DB messages to message format
		yzmaMessages := make([]types.Message, 0, len(dbMessages))
		for _, dbMsg := range dbMessages {
			if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
				yzmaMessages = append(yzmaMessages, msg)
			}
		}

		// Collect tool names for yzma
		toolNames := s.collectToolNames(ctx, req)

		// Create session with history
		session := &AgentSession{
			SessionID:       req.SessionID,
			UserID:          req.UserID,
			Messages:        yzmaMessages,
			KnowledgeBaseID: req.KnowledgeBaseID,
			ToolNames:       toolNames,
			Context:         req.Context,
			CreatedAt:       dbSession.CreatedAt,
			UpdatedAt:       dbSession.UpdatedAt,
			DBSession:       dbSession,
		}

		s.sessions[req.SessionID] = session

		log.Printf("✅ Reconstructed session from DB: %s (KB: %s, History: %d msgs, Tools: %v)",
			req.SessionID, req.KnowledgeBaseID, len(yzmaMessages), toolNames)

		return session, nil
	}

	// 3. Session doesn't exist - create new one
	log.Printf("🆕 Creating new session: %s", req.SessionID)

	// Create session in DB (handle race condition with UNIQUE constraint)
	dbSession, err = s.createSessionInDB(ctx, req.SessionID, req.UserID, req.KnowledgeBaseID)
	if err != nil {
		// Check if error is due to UNIQUE constraint (race condition)
		// Must NOT be FOREIGN KEY constraint (which is a real error, not race condition)
		errStr := err.Error()
		isUniqueConstraint := strings.Contains(errStr, "UNIQUE constraint failed")
		isForeignKey := strings.Contains(errStr, "FOREIGN KEY")
		if isUniqueConstraint && !isForeignKey {
			// Another process created the session - retry loading with exponential backoff
			log.Printf("⚠️  Race condition detected, retrying load from DB...")

			var dbMessages []db.Message
			maxRetries := 3
			for i := 0; i < maxRetries; i++ {
				// Wait a bit for the other process to commit
				time.Sleep(time.Duration(10*(i+1)) * time.Millisecond)

				dbSession, dbMessages, err = s.loadSessionFromDB(ctx, req.SessionID, req.UserID)
				if err == nil {
					log.Printf("✅ Successfully loaded session after %d retries", i+1)
					break
				}

				if i < maxRetries-1 {
					log.Printf("⏳ Retry %d/%d: session not yet available, waiting...", i+1, maxRetries)
				}
			}

			if err != nil {
				return nil, fmt.Errorf("failed to load session after race condition (tried %d times): %w", maxRetries, err)
			}

			// Convert DB messages to message format
			yzmaMessages := make([]types.Message, 0, len(dbMessages))
			for _, dbMsg := range dbMessages {
				if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
					yzmaMessages = append(yzmaMessages, msg)
				}
			}

			// Collect tool names
			toolNames := s.collectToolNames(ctx, req)

			// Create session with history
			session := &AgentSession{
				SessionID:       req.SessionID,
				UserID:          req.UserID,
				Messages:        yzmaMessages,
				KnowledgeBaseID: req.KnowledgeBaseID,
				ToolNames:       toolNames,
				Context:         req.Context,
				CreatedAt:       dbSession.CreatedAt,
				UpdatedAt:       dbSession.UpdatedAt,
				DBSession:       dbSession,
			}

			s.sessions[req.SessionID] = session

			log.Printf("✅ Recovered from race condition: %s", req.SessionID)
			return session, nil
		}

		// Other error - fail
		return nil, fmt.Errorf("failed to create session in DB: %w", err)
	}

	// Collect tool names for yzma
	toolNames := s.collectToolNames(ctx, req)

	// Create in-memory session
	session := &AgentSession{
		SessionID:       req.SessionID,
		UserID:          req.UserID,
		Messages:        make([]types.Message, 0),
		KnowledgeBaseID: req.KnowledgeBaseID,
		ToolNames:       toolNames,
		Context:         req.Context,
		CreatedAt:       dbSession.CreatedAt,
		UpdatedAt:       dbSession.UpdatedAt,
		DBSession:       dbSession,
	}

	s.sessions[req.SessionID] = session

	log.Printf("✅ Created new session: %s (KB: %s, Tools: %v)",
		req.SessionID, req.KnowledgeBaseID, toolNames)

	return session, nil
}

// collectToolNames collects tool names for the session based on request
// If no tools specified, returns nil which means "use all registered tools"
func (s *AgentChatService) collectToolNames(ctx context.Context, req ChatRequest) []string {
	var toolNames []string

	// Add KB search tool if KB is specified
	if req.KnowledgeBaseID != "" {
		// Register KB tool to registry if not exists
		if err := s.registerKBSearchTool(ctx, req.KnowledgeBaseID, req.UserID); err != nil {
			log.Printf("⚠️  Warning: Failed to register KB tool: %v", err)
		} else {
			kb, err := s.kbService.GetKnowledgeBase(ctx, req.KnowledgeBaseID, req.UserID)
			if err == nil {
				toolNames = append(toolNames, fmt.Sprintf("search_%s", kb.Name))
			}
		}
	}

	// Add requested tools
	toolNames = append(toolNames, req.Tools...)

	// If no tools specified, return nil to use all registered tools
	// This allows LLM to use any available tool including lobe-image-describe
	if len(toolNames) == 0 {
		return nil
	}

	return toolNames
}

// prepareMessagesWithSystemPrompt prepares messages with system prompt for yzma
func (s *AgentChatService) prepareMessagesWithSystemPrompt(messages []types.Message, session *AgentSession) []types.Message {
	// Build base instruction
	baseInstruction := "You are a helpful AI assistant. "

	// Inject summary if exists
	if session.Context != nil {
		if historySummary, ok := session.Context["history_summary"].(string); ok && historySummary != "" {
			summaryContext := fmt.Sprintf(`

<chat_history_summary>
<docstring>Previous conversation summary (older messages have been compressed):</docstring>
<summary>%s</summary>
</chat_history_summary>

`, historySummary)
			baseInstruction += summaryContext
			log.Printf("📋 Injected history summary into system prompt (%d chars)", len(historySummary))
		}
	}

	if session.KnowledgeBaseID != "" {
		baseInstruction += "You have access to a knowledge base. Use the search tool to find relevant information before answering questions. "
	}

	// Apply reasoning mode to instruction
	instruction := s.reasoningConfig.GetSystemPrompt(baseInstruction)

	log.Printf("🧠 Preparing messages with reasoning mode: %s", s.reasoningConfig.Mode)
	log.Printf("📝 System prompt length: %d chars", len(instruction))

	// Check if messages already have system prompt
	if len(messages) > 0 && messages[0].GetRole() == "system" {
		// Update existing system prompt
		result := make([]types.Message, len(messages))
		copy(result, messages)
		result[0] = types.NewSystemMessage(instruction)
		return result
	}

	// Prepend system prompt
	result := make([]types.Message, 0, len(messages)+1)
	result = append(result, types.NewSystemMessage(instruction))
	result = append(result, messages...)
	return result
}

// generateWithStreaming generates response with streaming using llm.Provider interface
func (s *AgentChatService) generateWithStreaming(ctx context.Context, session *AgentSession, messageID string, messages []types.Message, provider llm.Provider) (*types.LLMResponse, []types.Message, error) {
	// Emit start event
	if s.app != nil {
		s.app.Event.Emit("chat:stream", map[string]interface{}{
			"type":       "start",
			"session_id": session.SessionID,
			"message_id": messageID,
		})
	}

	var fullContent strings.Builder
	var buffer strings.Builder // Buffer untuk detect tool tags

	// Streaming callback with tool tag filtering
	callback := func(token string, isLast bool) {
		if token != "" {
			fullContent.WriteString(token)
			buffer.WriteString(token)

			// Check if we're inside a tool_call tag
			bufferStr := buffer.String()

			// If buffer contains complete tool_call tags, remove them from display
			if strings.Contains(bufferStr, "</tool_call>") {
				// Find all complete tool_call blocks
				for strings.Contains(bufferStr, "<tool_call>") && strings.Contains(bufferStr, "</tool_call>") {
					startIdx := strings.Index(bufferStr, "<tool_call>")
					endIdx := strings.Index(bufferStr, "</tool_call>")

					if startIdx < endIdx {
						// Remove the tool_call block
						bufferStr = bufferStr[:startIdx] + bufferStr[endIdx+len("</tool_call>"):]
					} else {
						break
					}
				}
				buffer.Reset()
				buffer.WriteString(bufferStr)
			}

			// Only emit content that's not inside tool tags
			displayContent := bufferStr
			if strings.Contains(displayContent, "<tool_call>") && !strings.Contains(displayContent, "</tool_call>") {
				// We're in the middle of a tool_call tag, only show content before it
				displayContent = displayContent[:strings.Index(displayContent, "<tool_call>")]
			}

			// Emit chunk event with filtered content
			if s.app != nil {
				s.app.Event.Emit("chat:stream", map[string]interface{}{
					"type":         "chunk",
					"session_id":   session.SessionID,
					"message_id":   messageID,
					"content":      token,
					"full_content": strings.TrimSpace(displayContent),
				})
			}
		}

		if isLast {
			// Clean final content from tool tags
			finalContent := fullContent.String()
			for strings.Contains(finalContent, "<tool_call>") {
				start := strings.Index(finalContent, "<tool_call>")
				end := strings.Index(finalContent, "</tool_call>")
				if start != -1 && end != -1 {
					finalContent = finalContent[:start] + finalContent[end+len("</tool_call>"):]
				} else {
					break
				}
			}
			finalContent = strings.TrimSpace(finalContent)

			// Emit complete event
			if s.app != nil {
				s.app.Event.Emit("chat:stream", map[string]interface{}{
					"type":       "complete",
					"session_id": session.SessionID,
					"message_id": messageID,
					"content":    finalContent,
				})
			}
		}
	}

	// Run agent loop with streaming (no tool callback for legacy method)
	resp, toolMessages, err := provider.RunAgentLoopWithStreaming(ctx, messages, 10, callback, nil)
	if err != nil {
		return nil, nil, err
	}

	// Emit tool calling event if tools were used
	if len(resp.ToolCalls) > 0 && s.app != nil {
		// Convert tool calls to frontend format
		frontendTools := make([]map[string]interface{}, len(resp.ToolCalls))
		for i, tc := range resp.ToolCalls {
			// Generate unique ID for each tool call
			toolCallID := fmt.Sprintf("%s_%d", messageID, i)

			frontendTools[i] = map[string]interface{}{
				"id":         toolCallID,
				"identifier": tc.Function.Name,
				"apiName":    tc.Function.Name,
				"arguments":  tc.Function.Arguments,
				"type":       tc.Type,
			}
		}

		s.app.Event.Emit("chat:stream", map[string]interface{}{
			"type":       "tool_calling",
			"session_id": session.SessionID,
			"message_id": messageID,
			"tools":      frontendTools,
		})

		log.Printf("🔧 Emitted tool_calling event with %d tools", len(frontendTools))
	}

	return resp, toolMessages, nil
}

// registerKBSearchTool registers a knowledge base search tool to the yzma registry
func (s *AgentChatService) registerKBSearchTool(ctx context.Context, kbID, userID string) error {
	kb, err := s.kbService.GetKnowledgeBase(ctx, kbID, userID)
	if err != nil {
		return err
	}

	toolName := fmt.Sprintf("search_%s", kb.Name)

	// Check if already registered
	if _, exists := s.toolRegistry.Get(toolName); exists {
		return nil // Already registered
	}

	// Create yzma tool
	kbService := s.kbService
	tool := &types.Tool{
		Type: "function",
		Function: types.ToolFunction{
			Name:        toolName,
			Description: fmt.Sprintf("Search the %s knowledge base for relevant information", kb.Name),
			Parameters: map[string]interface{}{
				"type": "object",
				"properties": map[string]interface{}{
					"query": map[string]interface{}{
						"type":        "string",
						"description": "The search query to find relevant information",
					},
					"top_k": map[string]interface{}{
						"type":        "integer",
						"description": "Number of results to return (default: 5)",
					},
				},
				"required": []string{"query"},
			},
		},
		Executor: func(execCtx context.Context, args map[string]string) (string, error) {
			query := args["query"]
			if query == "" {
				return "", fmt.Errorf("query parameter is required")
			}

			topK := 5
			if topKStr, ok := args["top_k"]; ok && topKStr != "" {
				if n, err := fmt.Sscanf(topKStr, "%d", &topK); err != nil || n != 1 {
					topK = 5
				}
			}

			// Query knowledge base
			docs, err := kbService.QueryKnowledgeBase(execCtx, kbID, query, topK, userID)
			if err != nil {
				return "", fmt.Errorf("KB search failed: %w", err)
			}

			// Format results
			result := map[string]interface{}{
				"found": len(docs),
				"results": func() []map[string]interface{} {
					results := make([]map[string]interface{}, len(docs))
					for i, doc := range docs {
						results[i] = map[string]interface{}{
							"content":  doc.Content,
							"metadata": doc.Metadata,
						}
					}
					return results
				}(),
			}

			resultJSON, err := json.Marshal(result)
			if err != nil {
				return "", fmt.Errorf("failed to marshal result: %w", err)
			}

			return string(resultJSON), nil
		},
		Enabled: true,
	}

	return s.toolRegistry.Register(tool)
}

// ClearSession removes a session from memory
func (s *AgentChatService) ClearSession(sessionID string) {
	s.sessionsMutex.Lock()
	defer s.sessionsMutex.Unlock()

	delete(s.sessions, sessionID)
	log.Printf("🗑️  Cleared session: %s", sessionID)
}

// GetSessionHistory returns the message history for a session (native yzma format)
func (s *AgentChatService) GetSessionHistory(sessionID string) ([]types.Message, error) {
	s.sessionsMutex.RLock()
	defer s.sessionsMutex.RUnlock()

	session, exists := s.sessions[sessionID]
	if !exists {
		return nil, fmt.Errorf("session not found: %s", sessionID)
	}

	return session.Messages, nil
}

// SetTitleModel sets a specific model for title generation
// Use a small, fast model (e.g., Llama 3.2 1B) for efficiency
// If not set, falls back to main chat model
func (s *AgentChatService) SetTitleModel(modelPath string) {
	s.sessionsMutex.Lock()
	defer s.sessionsMutex.Unlock()
	s.titleModelPath = modelPath
	log.Printf("📝 Title generation model set to: %s", modelPath)
}

// generateTopicTitle generates a concise title for the conversation using LLM
// Uses TaskRouter to route to appropriate provider (remote or local)
func (s *AgentChatService) generateTopicTitle(ctx context.Context, messages []types.Message, locale string) (string, error) {
	if len(messages) == 0 {
		return "New Conversation", nil
	}

	// Build summary prompt
	systemPrompt := fmt.Sprintf(`You are a professional conversation summarizer. Generate a concise title that captures the essence of the conversation.

Rules:
- Maximum 10 words
- Maximum 50 characters
- No punctuation marks, quotes, or special characters
- Use the language specified by the locale code: %s
- Output ONLY the title text, nothing else

Example: Sleep Functions for Body and Mind`, locale)

	// Build conversation text (User messages only)
	var conversationText string
	for _, msg := range messages {
		if msg.GetRole() == "user" {
			conversationText += fmt.Sprintf("user: %s\n", msg.GetText())
		}
	}

	// Fallback: if no user messages found (unlikely but possible), use all messages
	if conversationText == "" {
		for _, msg := range messages {
			conversationText += fmt.Sprintf("%s: %s\n", msg.GetRole(), msg.GetText())
		}
	}

	log.Printf("📝 Generating title for conversation (%d messages, %d chars)", len(messages), len(conversationText))

	// Create messages for title generation
	titleMessages := types.Prompt{
		types.NewSystemMessage(systemPrompt),
		types.NewUserMessage(conversationText),
	}

	var responseContent string

	// Try TaskRouter first (routes to configured provider)
	if s.taskRouter != nil && s.taskRouter.HasProvider(llm.TaskTitleGen) {
		log.Printf("📝 Using TaskRouter for title generation")
		resp, err := s.taskRouter.GenerateTitle(ctx, titleMessages)
		if err != nil {
			log.Printf("⚠️  TaskRouter title generation failed: %v, falling back to local", err)
		} else {
			responseContent = resp.Content
		}
	}

	// Fallback to local model if TaskRouter failed or not configured
	if responseContent == "" {
		if s.titleModelPath != "" {
			log.Printf("📝 Using dedicated local title model: %s", filepath.Base(s.titleModelPath))

			// Save current model state
			currentModel := s.libService.GetLoadedChatModel()

			// Load title model
			if err := s.libService.LoadChatModel(s.titleModelPath); err != nil {
				log.Printf("⚠️  Failed to load title model, falling back to main model: %v", err)
				resp, genErr := s.yzmaModel.WithoutTools().Generate(ctx, titleMessages)
				if genErr != nil {
					return "", fmt.Errorf("failed to generate title: %w", genErr)
				}
				responseContent = resp.Content
			} else {
				resp, genErr := s.yzmaModel.WithoutTools().Generate(ctx, titleMessages)
				if genErr != nil {
					if currentModel != "" {
						s.libService.LoadChatModel(currentModel)
					}
					return "", fmt.Errorf("failed to generate title: %w", genErr)
				}
				responseContent = resp.Content

				if currentModel != "" {
					if restoreErr := s.libService.LoadChatModel(currentModel); restoreErr != nil {
						log.Printf("⚠️  Failed to restore main model: %v", restoreErr)
					}
				}
			}
		} else {
			log.Printf("📝 Using main chat model for title generation")
			resp, err := s.yzmaModel.WithoutTools().Generate(ctx, titleMessages)
			if err != nil {
				return "", fmt.Errorf("failed to generate title: %w", err)
			}
			responseContent = resp.Content
		}
	}

	// Strip <think> tags if present (for reasoning models)
	if strings.Contains(responseContent, "<think>") {
		log.Printf("⚠️  Model generated <think> tags in title, stripping...")
		responseContent = stripThinkTags(responseContent)
	}

	log.Printf("📝 Raw title response: %q", responseContent)

	// Clean up the title
	title := strings.TrimSpace(responseContent)

	// If title is empty, try to extract from the original response
	if title == "" {
		// Try to find text in quotes
		quotePattern := regexp.MustCompile(`["']([^"']+)["']`)
		matches := quotePattern.FindStringSubmatch(responseContent)
		if len(matches) > 1 {
			title = matches[1]
		} else {
			// Fallback: use first non-empty line
			lines := strings.Split(responseContent, "\n")
			for _, line := range lines {
				line = strings.TrimSpace(line)
				if line != "" {
					title = line
					break
				}
			}
		}
	}

	// Final fallback if still empty
	if title == "" {
		log.Printf("⚠️  Title generation failed (empty result), using default")
		title = "New Conversation"
	}

	// Truncate to 50 characters
	if len(title) > 50 {
		title = title[:50]
	}

	return title, nil
}

// stripThinkTags removes <think>...</think> blocks from the text using regex
func stripThinkTags(text string) string {
	// First, try to remove complete <think>...</think> blocks
	re := regexp.MustCompile(`(?s)<think>.*?</think>`)
	cleaned := re.ReplaceAllString(text, "")

	// If <think> tag still exists (incomplete/unclosed), remove everything from <think> onwards
	if strings.Contains(cleaned, "<think>") {
		idx := strings.Index(cleaned, "<think>")
		cleaned = cleaned[:idx]
	}

	return strings.TrimSpace(cleaned)
}

// createTopicForSessionSync creates a topic synchronously and returns the topicID
// Phase 4: Used to create topic before first message so we have topicID for message saving
func (s *AgentChatService) createTopicForSessionSync(ctx context.Context, sessionID, userID string) (string, error) {
	// Check if topic already exists for this session
	count, err := s.db.Queries().CountTopicsBySession(ctx, db.CountTopicsBySessionParams{
		SessionID: sql.NullString{String: sessionID, Valid: true},
		UserID:    userID,
	})
	if err != nil {
		return "", fmt.Errorf("failed to check existing topics: %w", err)
	}

	if count > 0 {
		// Topic already exists - find and return it
		// TODO: Add GetTopicBySession query to SQLC if needed
		// For now, return empty string and let it be created with title later
		return "", fmt.Errorf("topic already exists for session")
	}

	// Create topic with placeholder title
	topicID := uuid.New().String()
	now := time.Now().UnixMilli()

	// Use sessionID as is (don't convert "inbox" to NULL)
	sessionIDForDB := sql.NullString{String: sessionID, Valid: true}

	_, err = s.db.Queries().CreateTopic(ctx, db.CreateTopicParams{
		ID:             topicID,
		Title:          sql.NullString{String: "New Conversation", Valid: true},
		Favorite:       0,
		SessionID:      sessionIDForDB,
		GroupID:        sql.NullString{},
		UserID:         userID,
		HistorySummary: sql.NullString{},
		Metadata:       sql.NullString{},
		CreatedAt:      now,
		UpdatedAt:      now,
	})

	if err != nil {
		return "", fmt.Errorf("failed to create topic: %w", err)
	}

	return topicID, nil
}

// updateTopicTitle updates an existing topic with LLM-generated title
// Phase 4 FIX: Used to update placeholder topic with meaningful title after first response
func (s *AgentChatService) updateTopicTitle(ctx context.Context, topicID, userID string, messages []types.Message) error {
	// Create a copy of messages to avoid race conditions
	messagesCopy := make([]types.Message, len(messages))
	copy(messagesCopy, messages)

	// Run in background
	go func() {
		// Add a small delay to ensure main chat request finishes and releases model resources
		time.Sleep(2 * time.Second)

		log.Printf("🔄 Generating title in background for topic %s...", topicID)

		// Create context with timeout
		ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
		defer cancel()

		// Generate title (default locale: en-US)
		title, err := s.generateTopicTitle(ctx, messagesCopy, "en-US")
		if err != nil {
			log.Printf("⚠️  Warning: Failed to generate topic title: %v", err)
			title = "New Conversation"
		}

		// Fetch existing topic first to preserve history_summary and metadata
		existingTopic, err := s.db.Queries().GetTopic(ctx, db.GetTopicParams{
			ID:     topicID,
			UserID: userID,
		})
		if err != nil {
			log.Printf("⚠️  Failed to fetch topic for update: %v", err)
			return
		}

		// Update topic title in database
		now := time.Now().UnixMilli()
		_, err = s.db.Queries().UpdateTopic(ctx, db.UpdateTopicParams{
			Title:          sql.NullString{String: title, Valid: true},
			HistorySummary: existingTopic.HistorySummary, // Preserve existing
			Metadata:       existingTopic.Metadata,       // Preserve existing
			UpdatedAt:      now,
			ID:             topicID,
			UserID:         userID,
		})

		if err != nil {
			log.Printf("⚠️  Failed to update topic title in DB: %v", err)
		} else {
			log.Printf("✅ Updated topic %s with title: %s", topicID, title)

			// Emit event to notify UI
			if s.app != nil {
				s.app.Event.Emit("chat:topic:updated", map[string]interface{}{
					"topic_id": topicID,
					"title":    title,
				})
			}
		}
	}()

	// Return immediately - title will be updated in background
	return nil
}

// createTopicForSessionWithTitle creates a topic with LLM-generated title and returns topicID
// Phase 4: Used after first response to create/update topic with meaningful title
func (s *AgentChatService) createTopicForSessionWithTitle(ctx context.Context, sessionID, userID string, messages []types.Message) (string, error) {
	// Check if topic already exists for this session
	count, err := s.db.Queries().CountTopicsBySession(ctx, db.CountTopicsBySessionParams{
		SessionID: sql.NullString{String: sessionID, Valid: true},
		UserID:    userID,
	})
	if err != nil {
		return "", fmt.Errorf("failed to check existing topics: %w", err)
	}

	if count > 0 {
		// Topic already exists - could update title here if needed
		// For now, just return success
		return "", nil
	}

	// Create topic in database with placeholder title first (non-blocking)
	topicID := uuid.New().String()
	now := time.Now().UnixMilli()

	// Use sessionID as is (don't convert "inbox" to NULL)
	sessionIDForDB := sql.NullString{String: sessionID, Valid: true}

	_, err = s.db.Queries().CreateTopic(ctx, db.CreateTopicParams{
		ID:             topicID,
		Title:          sql.NullString{String: "New Conversation", Valid: true}, // Placeholder
		Favorite:       0,
		SessionID:      sessionIDForDB,
		GroupID:        sql.NullString{},
		UserID:         userID,
		HistorySummary: sql.NullString{},
		Metadata:       sql.NullString{},
		CreatedAt:      now,
		UpdatedAt:      now,
	})

	if err != nil {
		return "", fmt.Errorf("failed to create topic: %w", err)
	}

	// Generate title in BACKGROUND to avoid blocking (model loading can take 2-5 seconds)
	messagesCopy := make([]types.Message, len(messages))
	copy(messagesCopy, messages)

	topicIDCopy := topicID
	userIDCopy := userID

	go func() {
		log.Printf("🔄 Generating title in background for new topic %s...", topicIDCopy)

		// Generate title (default locale: en-US)
		title, err := s.generateTopicTitle(context.Background(), messagesCopy, "en-US")
		if err != nil {
			log.Printf("⚠️  Warning: Failed to generate topic title: %v", err)
			title = "New Conversation"
		}

		// Update topic title in database
		now := time.Now().UnixMilli()
		_, err = s.db.Queries().UpdateTopic(context.Background(), db.UpdateTopicParams{
			Title:          sql.NullString{String: title, Valid: true},
			HistorySummary: sql.NullString{}, // Keep existing
			Metadata:       sql.NullString{}, // Keep existing
			UpdatedAt:      now,
			ID:             topicIDCopy,
			UserID:         userIDCopy,
		})

		if err != nil {
			log.Printf("⚠️  Failed to update topic title in DB: %v", err)
		} else {
			log.Printf("✅ Updated new topic %s with title: %s", topicIDCopy, title)

			// Emit event to notify UI
			if s.app != nil {
				s.app.Event.Emit("chat:topic:updated", map[string]interface{}{
					"topic_id": topicIDCopy,
					"title":    title,
				})
			}
		}
	}()

	return topicID, nil
}

// ============================================================================
// Database Persistence Methods
// ============================================================================

// convertDBMessageToYzma converts a database message to native message
// Returns the message and a boolean indicating if conversion was successful
func convertDBMessageToYzma(dbMsg *db.Message) (types.Message, bool) {
	role := dbMsg.Role
	content := ""
	if dbMsg.Content.Valid {
		content = dbMsg.Content.String
	}

	// Check for tool calls
	if dbMsg.Tools.Valid && dbMsg.Tools.String != "" {
		var toolCalls []types.ToolCall
		if err := json.Unmarshal([]byte(dbMsg.Tools.String), &toolCalls); err == nil && len(toolCalls) > 0 {
			return types.NewToolCallMessage(toolCalls), true
		}
	}

	// Check for tool response
	if role == "tool" && content != "" {
		return types.NewToolResultMessage("", "", content), true
	}

	// Skip empty messages
	if role == "" && content == "" {
		return types.Message{}, false
	}

	// Regular chat message
	return types.NewTextMessage(types.MessageRole(role), content), true
}

// convertYzmaMessageToDB converts yzma message to DB message params
func convertYzmaMessageToDB(msg types.Message, sessionID, userID string) db.CreateMessageParams {
	return convertYzmaMessageToDBWithID(msg, sessionID, userID, "")
}

// convertYzmaMessageToDBWithID converts yzma message to DB message params with optional pre-generated ID
func convertYzmaMessageToDBWithID(msg types.Message, sessionID, userID, messageID string) db.CreateMessageParams {
	now := time.Now().UnixMilli()

	// Use pre-generated ID if provided, otherwise generate new one
	msgID := messageID
	if msgID == "" {
		msgID = uuid.New().String()
	}

	params := db.CreateMessageParams{
		ID:        msgID,
		Role:      msg.GetRole(),
		UserID:    userID,
		CreatedAt: now,
		UpdatedAt: now,
	}

	if sessionID != "" {
		params.SessionID = sql.NullString{String: sessionID, Valid: true}
	}

	// Extract content based on message parts
	textContent := msg.GetText()
	if textContent != "" {
		params.Content = sql.NullString{String: textContent, Valid: true}
	}

	// Check for tool calls
	if msg.HasToolCalls() {
		toolCalls := msg.GetToolCalls()
		if toolCallsJSON, err := json.Marshal(toolCalls); err == nil {
			params.Tools = sql.NullString{String: string(toolCallsJSON), Valid: true}
		}
	}

	// Check for tool result
	for _, part := range msg.Content {
		if p, ok := part.(types.ToolResultPart); ok {
			params.Content = sql.NullString{String: p.Content, Valid: true}
			params.Role = "tool"
			break
		}
	}

	return params
}

// loadSessionFromDB loads a session from database
func (s *AgentChatService) loadSessionFromDB(ctx context.Context, sessionID, userID string) (*db.Session, []db.Message, error) {
	// Load session metadata (sessionID can be either ID or slug)
	dbSession, err := s.db.Queries().GetSessionByIdOrSlug(ctx, db.GetSessionByIdOrSlugParams{
		ID:     sessionID,
		Slug:   sessionID,
		UserID: userID,
	})
	if err != nil {
		return nil, nil, fmt.Errorf("session not found in DB: %w", err)
	}

	// Load message history (use actual session ID from DB, not slug)
	dbMessages, err := s.db.Queries().ListMessagesBySession(ctx, db.ListMessagesBySessionParams{
		UserID:    userID,
		SessionID: sql.NullString{String: dbSession.ID, Valid: true},
		Limit:     1000, // Load up to 1000 messages
		Offset:    0,
	})
	if err != nil {
		// If messages query fails, still return session
		log.Printf("Warning: Failed to load messages for session %s: %v", sessionID, err)
		return &dbSession, nil, nil
	}

	return &dbSession, dbMessages, nil
}

// createSessionInDB creates a new session in database
func (s *AgentChatService) createSessionInDB(ctx context.Context, sessionID, userID, kbID string) (*db.Session, error) {
	now := time.Now().UnixMilli()

	// Generate unique slug from sessionID
	// Use last 8 chars to ensure uniqueness (they contain timestamps/random)
	slug := sessionID
	if len(slug) > 8 {
		// Take last 8 chars for better uniqueness with timestamps
		slug = slug[len(slug)-8:]
	}

	params := db.CreateSessionParams{
		ID:        sessionID,
		Slug:      slug,
		UserID:    userID,
		Type:      sql.NullString{String: "agent", Valid: true},
		Pinned:    0,
		CreatedAt: now,
		UpdatedAt: now,
	}

	// Set title based on KB if available
	if kbID != "" {
		kb, err := s.kbService.GetKnowledgeBase(ctx, kbID, userID)
		if err == nil {
			params.Title = sql.NullString{
				String: fmt.Sprintf("Chat with %s", kb.Name),
				Valid:  true,
			}
		}
	}

	if !params.Title.Valid {
		params.Title = sql.NullString{String: "New Conversation", Valid: true}
	}

	dbSession, err := s.db.Queries().CreateSession(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to create session in DB: %w", err)
	}

	return &dbSession, nil
}

// saveMessageToDB saves a message to database
// saveMessageToDB saves a message to the database
// Phase 4: Now accepts topicID and threadID for proper message linking
func (s *AgentChatService) saveYzmaMessageToDB(ctx context.Context, msg types.Message, sessionID, userID, topicID, threadID string) (string, error) {
	return s.saveYzmaMessageToDBWithID(ctx, msg, sessionID, userID, topicID, threadID, "")
}

func (s *AgentChatService) saveYzmaMessageToDBWithID(ctx context.Context, msg types.Message, sessionID, userID, topicID, threadID, messageID string) (string, error) {
	params := convertYzmaMessageToDBWithID(msg, sessionID, userID, messageID)

	if topicID != "" {
		params.TopicID = sql.NullString{String: topicID, Valid: true}
	}
	if threadID != "" {
		params.ThreadID = sql.NullString{String: threadID, Valid: true}
	}

	dbMsg, err := s.db.Queries().CreateMessage(ctx, params)
	if err != nil {
		return "", fmt.Errorf("failed to save message to DB: %w", err)
	}

	return dbMsg.ID, nil
}

// updateSessionTimestamp updates the session's updated_at timestamp
func (s *AgentChatService) updateSessionTimestamp(ctx context.Context, sessionID, userID string) error {
	now := time.Now().UnixMilli()

	// Get current session
	dbSession, err := s.db.Queries().GetSession(ctx, db.GetSessionParams{
		ID:     sessionID,
		UserID: userID,
	})
	if err != nil {
		return fmt.Errorf("session not found: %w", err)
	}

	// Update timestamp
	_, err = s.db.Queries().UpdateSession(ctx, db.UpdateSessionParams{
		Title:           dbSession.Title,
		Description:     dbSession.Description,
		Avatar:          dbSession.Avatar,
		BackgroundColor: dbSession.BackgroundColor,
		GroupID:         dbSession.GroupID,
		Pinned:          dbSession.Pinned,
		UpdatedAt:       now,
		ID:              sessionID,
		UserID:          userID,
	})

	return err
}

// SetReasoningMode sets the reasoning mode for the service
// This affects all new conversations created after this call
// Validates hardware specs before allowing resource-intensive reasoning modes
func (s *AgentChatService) SetReasoningMode(mode ReasoningMode) error {
	s.sessionsMutex.Lock()
	defer s.sessionsMutex.Unlock()

	// Validate mode
	if mode != ReasoningDisabled && mode != ReasoningEnabled && mode != ReasoningVerbose {
		return fmt.Errorf("invalid reasoning mode: %s", mode)
	}

	// Get hardware specs from the installer
	var hardwareSpecs *llama.HardwareSpecs
	if s.libService != nil {
		hardwareSpecs = s.libService.GetHardwareSpecs()
	}

	// Create temp config to validate hardware
	tempConfig := s.reasoningConfig
	tempConfig.Mode = mode

	// Validate hardware requirements for reasoning modes
	if mode == ReasoningEnabled || mode == ReasoningVerbose {
		if valid, reason := tempConfig.ValidateHardware(hardwareSpecs); !valid {
			// Hardware insufficient - suggest alternative
			suggested := SuggestModeForHardware(hardwareSpecs)
			log.Printf("⚠️  Hardware validation failed for %s mode: %s", mode, reason)
			log.Printf("💡 Auto-switching to %s mode based on available hardware", suggested)

			// Auto-switch to suggested mode instead of failing
			mode = suggested
			tempConfig.Mode = suggested

			// If still trying reasoning mode after suggestion, validate again
			if mode != ReasoningDisabled {
				if valid, reason := tempConfig.ValidateHardware(hardwareSpecs); !valid {
					// Even suggested mode failed - force disable
					log.Printf("⚠️  Even suggested mode failed: %s. Forcing disabled mode.", reason)
					mode = ReasoningDisabled
				}
			}
		}
	}

	s.reasoningConfig.Mode = mode
	log.Printf("🧠 Reasoning mode changed to: %s (%s)", mode, s.reasoningConfig.GetModeDescription())

	// Log hardware requirements
	hwReq := s.reasoningConfig.GetHardwareRequirements()
	log.Printf("💻 Hardware requirements: %s", hwReq.Description)
	if hardwareSpecs != nil {
		log.Printf("📊 Current system: RAM=%dGB, Cores=%d, GPU=%s",
			hardwareSpecs.AvailableRAM, hardwareSpecs.CPUCores, hardwareSpecs.GPUModel)
	}

	// Log performance expectations
	perf := s.reasoningConfig.GetExpectedPerformance()
	log.Printf("📊 Expected performance:")
	log.Printf("   - Speed: %s", perf["speed"])
	log.Printf("   - Token efficiency: %s", perf["token_efficiency"])
	log.Printf("   - Max turns: %s", perf["max_turns"])
	log.Printf("   - Response size: %s", perf["response_size"])

	return nil
}

// GetReasoningMode returns the current reasoning mode
func (s *AgentChatService) GetReasoningMode() ReasoningMode {
	s.sessionsMutex.RLock()
	defer s.sessionsMutex.RUnlock()
	return s.reasoningConfig.Mode
}

// GetReasoningConfig returns the current reasoning configuration
func (s *AgentChatService) GetReasoningConfig() ReasoningConfig {
	s.sessionsMutex.RLock()
	defer s.sessionsMutex.RUnlock()
	return s.reasoningConfig
}

// ValidateModelForReasoningMode checks if the currently loaded model is appropriate
func (s *AgentChatService) ValidateModelForReasoningMode() error {
	modelPath := s.libService.GetLoadedChatModel()
	if modelPath == "" {
		return fmt.Errorf("no model loaded")
	}

	return s.reasoningConfig.ValidateModelForMode(modelPath)
}

// GetRecommendedModelForMode returns the recommended model for current reasoning mode
func (s *AgentChatService) GetRecommendedModelForMode() string {
	return s.reasoningConfig.GetRecommendedModel()
}

// SwitchToRecommendedModel loads the recommended model for current reasoning mode
func (s *AgentChatService) SwitchToRecommendedModel() error {
	recommendedModel := s.reasoningConfig.GetRecommendedModel()

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	modelsDir := filepath.Join(homeDir, ".llama-cpp", "models")
	modelPath := filepath.Join(modelsDir, recommendedModel)

	log.Printf("🔄 Switching to recommended model for %s mode: %s", s.reasoningConfig.Mode, recommendedModel)

	if err := s.libService.LoadChatModel(modelPath); err != nil {
		return fmt.Errorf("failed to load recommended model: %w", err)
	}

	// Note: yzmaModel uses libService internally, so no need to recreate

	log.Printf("✅ Successfully switched to %s", recommendedModel)
	return nil
}

// ============================================================================
// History Summary Functions
// ============================================================================

// autoSummarizeIfNeeded checks conditions and triggers summary automatically
// Runs in background goroutine, does not block chat response
func (s *AgentChatService) autoSummarizeIfNeeded(ctx context.Context, session *AgentSession, topicID, userID string) {
	if topicID == "" {
		return // No topic, no summary
	}

	// 1. Check if reasoning mode supports summarization
	threshold := s.reasoningConfig.GetSummaryThreshold()
	if threshold == 0 {
		return // Verbose mode doesn't need summary (3-5 turns only)
	}

	// 2. Check turn count
	turnCount := len(session.Messages) / 2
	if turnCount < threshold {
		return // Not enough turns yet
	}

	// 3. Check if we already summarized recently
	topic, err := s.db.Queries().GetTopic(ctx, db.GetTopicParams{
		ID:     topicID,
		UserID: userID,
	})
	if err != nil {
		log.Printf("⚠️  autoSummarize: Failed to get topic: %v", err)
		return
	}

	// If summary exists, this will be handled by incrementalSummarizeIfNeeded()
	if topic.HistorySummary.Valid && topic.HistorySummary.String != "" {
		return // Summary already exists, incremental will handle updates
	}

	// 4. Get messages from database (not from session, could be stale)
	messages, err := s.db.Queries().GetMessagesByTopicId(ctx, db.GetMessagesByTopicIdParams{
		TopicID: sql.NullString{String: topicID, Valid: true},
		UserID:  userID,
	})
	if err != nil || len(messages) < 4 {
		log.Printf("⚠️  autoSummarize: Not enough messages to summarize: %d", len(messages))
		return
	}

	// 5. Determine which messages to summarize
	// Keep recent messages based on reasoning mode
	keepCount := s.getKeepMessageCount()
	if len(messages) <= keepCount {
		return // Not enough messages to warrant summary
	}

	oldMessages := messages[:len(messages)-keepCount]

	// 6. Convert to message format
	yzmaMessages := make([]types.Message, 0, len(oldMessages))
	for _, dbMsg := range oldMessages {
		if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
			yzmaMessages = append(yzmaMessages, msg)
		}
	}

	if len(yzmaMessages) < 2 {
		return // Need at least 2 messages (1 turn) to summarize
	}

	// 7. Generate summary (this is already in background goroutine)
	log.Printf("🔄 Auto-generating summary for topic %s (%d old messages, keeping %d recent)",
		topicID, len(yzmaMessages), keepCount)

	summary, err := s.generateHistorySummary(ctx, yzmaMessages)
	if err != nil {
		log.Printf("❌ Auto-summary failed: %v", err)
		return
	}

	// 8. Save summary to database
	now := time.Now().UnixMilli()
	metadata := fmt.Sprintf(`{"summarized_at":%d,"message_count":%d,"reasoning_mode":"%s"}`,
		now, len(yzmaMessages), s.reasoningConfig.Mode)

	_, err = s.db.Queries().UpdateTopic(ctx, db.UpdateTopicParams{
		Title:          topic.Title,
		HistorySummary: sql.NullString{String: summary, Valid: true},
		Metadata: sql.NullString{
			String: metadata,
			Valid:  true,
		},
		UpdatedAt: now,
		ID:        topicID,
		UserID:    userID,
	})

	if err != nil {
		log.Printf("❌ Failed to save auto-summary: %v", err)
	} else {
		log.Printf("✅ Auto-summary completed for topic %s (compressed %d messages into %d chars)",
			topicID, len(yzmaMessages), len(summary))

		// Emit subtle event to frontend (optional: show small toast or indicator)
		if s.app != nil {
			s.app.Event.Emit("chat:summary:auto-complete", map[string]interface{}{
				"topic_id":       topicID,
				"message_count":  len(yzmaMessages),
				"summary_length": len(summary),
			})
		}
	}
}

// getKeepMessageCount returns how many recent messages to keep (not summarize)
func (s *AgentChatService) getKeepMessageCount() int {
	switch s.reasoningConfig.Mode {
	case ReasoningDisabled:
		return 20 // Keep last 20 messages (10 turns)
	case ReasoningEnabled:
		return 12 // Keep last 12 messages (6 turns)
	case ReasoningVerbose:
		return 6 // Keep last 6 messages (3 turns) - but won't reach here
	default:
		return 16
	}
}

// generateHistorySummary generates summary using TaskRouter or local fallback
// Uses TaskRouter first, then falls back to local models
func (s *AgentChatService) generateHistorySummary(ctx context.Context, messages []types.Message) (string, error) {
	if len(messages) == 0 {
		return "", fmt.Errorf("no messages to summarize")
	}

	// Build summary prompt
	systemPrompt := `You're an assistant who's good at extracting key takeaways from conversations and summarizing them. 

Rules:
- Summarize the conversation in the user's original language
- Focus on key decisions, actions, and outcomes
- Maintain context for future conversation continuation
- Maximum 400 tokens
- Output ONLY the summary text, nothing else`

	// Build conversation text
	var conversationText string
	for _, msg := range messages {
		role := msg.GetRole()
		text := msg.GetText()
		if text != "" {
			conversationText += fmt.Sprintf("%s: %s\n\n", role, text)
		}
	}

	conversationContent := fmt.Sprintf(`<chat_history>
%s
</chat_history>

Please summarize the above conversation and retain key information. The summarized content will be used as context for subsequent prompts.`, conversationText)

	// Create messages for summary generation
	summaryMessages := types.Prompt{
		types.NewSystemMessage(systemPrompt),
		types.NewUserMessage(conversationContent),
	}

	var responseContent string
	var modelUsed string

	// Try TaskRouter first (routes to configured provider)
	if s.taskRouter != nil && s.taskRouter.HasProvider(llm.TaskSummaryGen) {
		log.Printf("📋 Using TaskRouter for summary generation")
		resp, err := s.taskRouter.GenerateSummary(ctx, summaryMessages)
		if err != nil {
			log.Printf("⚠️  TaskRouter summary generation failed: %v, falling back to local", err)
		} else {
			responseContent = resp.Content
			modelUsed = "taskrouter"
		}
	}

	// Fallback to local models if TaskRouter failed or not configured
	if responseContent == "" {
		currentModel := s.libService.GetLoadedChatModel()
		modelWithoutTools := s.yzmaModel.WithoutTools()

		// Try 1: Dedicated summary model (BEST - optimized for this task)
		if s.summaryModelPath != "" && s.summaryModelPath != currentModel {
			log.Printf("📋 Using dedicated summary model: %s", filepath.Base(s.summaryModelPath))

			if loadErr := s.libService.LoadChatModel(s.summaryModelPath); loadErr != nil {
				log.Printf("⚠️  Failed to load summary model: %v", loadErr)
			} else {
				resp, genErr := modelWithoutTools.Generate(ctx, summaryMessages)
				if genErr == nil {
					responseContent = resp.Content
					modelUsed = "summary"
				} else {
					log.Printf("⚠️  Summary model generation failed: %v", genErr)
				}

				// Restore main model
				if currentModel != "" {
					if restoreErr := s.libService.LoadChatModel(currentModel); restoreErr != nil {
						log.Printf("⚠️  Failed to restore main model: %v", restoreErr)
					}
				}
			}
		}

		// Try 2: Title model (GOOD - small and fast, already tested)
		if responseContent == "" && s.titleModelPath != "" && s.titleModelPath != currentModel {
			log.Printf("📋 Falling back to title model: %s", filepath.Base(s.titleModelPath))

			if loadErr := s.libService.LoadChatModel(s.titleModelPath); loadErr != nil {
				log.Printf("⚠️  Failed to load title model: %v", loadErr)
			} else {
				resp, genErr := modelWithoutTools.Generate(ctx, summaryMessages)
				if genErr == nil {
					responseContent = resp.Content
					modelUsed = "title"
				} else {
					log.Printf("⚠️  Title model generation failed: %v", genErr)
				}

				// Restore main model
				if currentModel != "" {
					s.libService.LoadChatModel(currentModel)
				}
			}
		}

		// Try 3: Main chat model (FALLBACK - may be slow/reasoning model)
		if responseContent == "" {
			log.Printf("📋 Using main chat model for summary (no dedicated model available)")
			resp, err := modelWithoutTools.Generate(ctx, summaryMessages)
			if err != nil {
				return "", fmt.Errorf("failed to generate summary: %w", err)
			}
			responseContent = resp.Content
			modelUsed = "main"
		}
	}

	// Clean up response
	summary := strings.TrimSpace(responseContent)

	// Strip <think> tags if present (for reasoning models)
	if strings.Contains(summary, "<think>") {
		log.Printf("⚠️  WARNING: Summary contains <think> tags (model: %s), stripping...", modelUsed)
		summary = stripThinkTags(summary)
	}

	if summary == "" {
		return "", fmt.Errorf("empty summary generated")
	}

	log.Printf("✅ Summary generated using %s model (%d chars)", modelUsed, len(summary))
	return summary, nil
}

// incrementalSummarizeIfNeeded checks if existing summary needs update with new messages
// Runs in background goroutine, does not block chat response
func (s *AgentChatService) incrementalSummarizeIfNeeded(ctx context.Context, session *AgentSession, topicID, userID string) {
	if topicID == "" {
		return // No topic, no summary
	}

	// 1. Check if reasoning mode supports incremental summarization
	threshold := s.reasoningConfig.GetIncrementalSummaryThreshold()
	if threshold == 0 {
		return // Verbose mode doesn't use incremental summary
	}

	// 2. Get topic with existing summary
	topic, err := s.db.Queries().GetTopic(ctx, db.GetTopicParams{
		ID:     topicID,
		UserID: userID,
	})
	if err != nil {
		return // Topic not found
	}

	// 3. Check if summary exists (incremental only works if base summary exists)
	if !topic.HistorySummary.Valid || topic.HistorySummary.String == "" {
		return // No existing summary, nothing to update
	}

	// 4. Parse metadata to get summarized message count
	var metadata struct {
		SummarizedMessageCount int   `json:"summarized_message_count"`
		SummaryVersion         int   `json:"summary_version"`
		InitialSummaryAt       int64 `json:"initial_summary_at"`
	}

	if topic.Metadata.Valid && topic.Metadata.String != "" {
		if err := json.Unmarshal([]byte(topic.Metadata.String), &metadata); err != nil {
			log.Printf("⚠️  incrementalSummarize: Failed to parse metadata: %v", err)
			return
		}
	}

	// 5. Get all messages from database
	allMessages, err := s.db.Queries().GetMessagesByTopicId(ctx, db.GetMessagesByTopicIdParams{
		TopicID: sql.NullString{String: topicID, Valid: true},
		UserID:  userID,
	})
	if err != nil {
		log.Printf("⚠️  incrementalSummarize: Failed to get messages: %v", err)
		return
	}

	// 6. Count new messages since last summary
	newMessageCount := len(allMessages) - metadata.SummarizedMessageCount
	if newMessageCount < threshold*2 { // *2 because 1 turn = 2 messages
		return // Not enough new messages yet
	}

	log.Printf("🔄 Re-summarizing topic %s (v%d → v%d, %d new messages)",
		topicID, metadata.SummaryVersion, metadata.SummaryVersion+1, newMessageCount)

	// 7. Load existing summary
	existingSummary := topic.HistorySummary.String

	// 8. Get new messages to incorporate
	newMessages := allMessages[metadata.SummarizedMessageCount:]
	keepCount := s.getKeepMessageCount()

	// Make sure we have messages to summarize
	if len(newMessages) <= keepCount {
		return // All new messages are in "keep" range, nothing to summarize
	}

	messagesToSummarize := newMessages[:len(newMessages)-keepCount]

	// 9. Convert DB messages to messages
	yzmaMessages := make([]types.Message, 0, len(messagesToSummarize))
	for _, dbMsg := range messagesToSummarize {
		if msg, ok := convertDBMessageToYzma(&dbMsg); ok {
			yzmaMessages = append(yzmaMessages, msg)
		}
	}

	if len(yzmaMessages) == 0 {
		return // No valid messages to summarize
	}

	// 10. Generate merged summary
	mergedSummary, err := s.generateIncrementalSummary(ctx, existingSummary, yzmaMessages)
	if err != nil {
		log.Printf("❌ Incremental summary failed: %v", err)
		return
	}

	// 11. Update metadata
	if metadata.InitialSummaryAt == 0 {
		metadata.InitialSummaryAt = time.Now().UnixMilli()
	}

	newMetadata := map[string]interface{}{
		"summary_version":          metadata.SummaryVersion + 1,
		"last_summarized_at":       time.Now().UnixMilli(),
		"summarized_message_count": len(allMessages) - keepCount,
		"initial_summary_at":       metadata.InitialSummaryAt,
		"reasoning_mode":           string(s.reasoningConfig.Mode),
	}

	metadataJSON, err := json.Marshal(newMetadata)
	if err != nil {
		log.Printf("⚠️  Failed to marshal metadata: %v", err)
		metadataJSON = []byte("{}")
	}

	// 12. Save updated summary to database
	_, err = s.db.Queries().UpdateTopic(ctx, db.UpdateTopicParams{
		ID:             topicID,
		UserID:         userID,
		Title:          topic.Title,
		HistorySummary: sql.NullString{String: mergedSummary, Valid: true},
		Metadata:       sql.NullString{String: string(metadataJSON), Valid: true},
		UpdatedAt:      time.Now().UnixMilli(),
	})

	if err != nil {
		log.Printf("❌ Failed to save incremental summary: %v", err)
		return
	}

	log.Printf("✅ Incremental summary v%d completed (%d total messages compressed)",
		newMetadata["summary_version"], newMetadata["summarized_message_count"])
}

// generateIncrementalSummary creates updated summary by merging existing summary with new messages
func (s *AgentChatService) generateIncrementalSummary(ctx context.Context, existingSummary string, newMessages []types.Message) (string, error) {
	// Build conversation context from new messages
	var messagesText strings.Builder
	for i, msg := range newMessages {
		role := "User"
		if msg.GetRole() == "assistant" {
			role = "Assistant"
		}
		text := msg.GetText()
		if text != "" {
			messagesText.WriteString(fmt.Sprintf("%s: %s\n", role, text))
		}
		if i < len(newMessages)-1 {
			messagesText.WriteString("\n")
		}
	}

	// Build prompt for incremental summarization
	prompt := fmt.Sprintf(`You are a conversation summarizer. Your task is to UPDATE an existing summary with new information.

EXISTING SUMMARY:
%s

NEW MESSAGES TO INCORPORATE:
%s

INSTRUCTIONS:
1. Read the existing summary carefully
2. Read the new messages to identify new topics and developments
3. Create an UPDATED summary that:
   - Preserves important information from the existing summary
   - Adds new topics and details from recent messages
   - Maintains chronological flow (what happened first, then next)
   - Stays concise (maximum 400 tokens)
4. Use the same language as the original messages
5. Focus on key topics, decisions, and important information
6. DO NOT use <think> tags or any XML/HTML markup

UPDATED SUMMARY:`, existingSummary, messagesText.String())

	// Create messages for incremental summary
	summaryMessages := types.Prompt{
		types.NewUserMessage(prompt),
	}

	// Try 1: Summary model (BEST)
	var responseContent string
	modelUsed := "unknown"

	currentModel := s.libService.GetLoadedChatModel()

	// Use model WITHOUT tools for summary generation
	modelWithoutTools := s.yzmaModel.WithoutTools()

	if s.summaryModelPath != "" && s.summaryModelPath != currentModel {
		log.Printf("📋 Using dedicated summary model for incremental: %s", filepath.Base(s.summaryModelPath))

		if loadErr := s.libService.LoadChatModel(s.summaryModelPath); loadErr != nil {
			log.Printf("⚠️  Failed to load summary model: %v", loadErr)
		} else {
			resp, genErr := modelWithoutTools.Generate(ctx, summaryMessages)
			if genErr == nil {
				responseContent = resp.Content
				modelUsed = "summary"
			} else {
				log.Printf("⚠️  Summary model generation failed: %v", genErr)
			}

			// Restore main model
			if currentModel != "" {
				s.libService.LoadChatModel(currentModel)
			}
		}
	}

	// Try 2: Title model (GOOD)
	if responseContent == "" && s.titleModelPath != "" && s.titleModelPath != currentModel {
		log.Printf("📋 Falling back to title model for incremental: %s", filepath.Base(s.titleModelPath))

		if loadErr := s.libService.LoadChatModel(s.titleModelPath); loadErr != nil {
			log.Printf("⚠️  Failed to load title model: %v", loadErr)
		} else {
			resp, genErr := modelWithoutTools.Generate(ctx, summaryMessages)
			if genErr == nil {
				responseContent = resp.Content
				modelUsed = "title"
			} else {
				log.Printf("⚠️  Title model generation failed: %v", genErr)
			}

			// Restore main model
			if currentModel != "" {
				s.libService.LoadChatModel(currentModel)
			}
		}
	}

	// Try 3: Main chat model (FALLBACK)
	if responseContent == "" {
		log.Printf("📋 Using main chat model for incremental summary")
		resp, err := modelWithoutTools.Generate(ctx, summaryMessages)
		if err != nil {
			return "", fmt.Errorf("failed to generate incremental summary: %w", err)
		}
		responseContent = resp.Content
		modelUsed = "main"
	}

	// Clean up response
	summary := strings.TrimSpace(responseContent)

	// Strip <think> tags if present
	if strings.Contains(summary, "<think>") {
		log.Printf("⚠️  WARNING: Incremental summary contains <think> tags (model: %s), stripping...", modelUsed)
		summary = stripThinkTags(summary)
	}

	if summary == "" {
		return "", fmt.Errorf("empty incremental summary generated")
	}

	log.Printf("✅ Incremental summary generated using %s model (%d chars)", modelUsed, len(summary))
	return summary, nil
}
