// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * EditLocalFileParams parameters for editing a file
 */
export class EditLocalFileParams {
    "file_path": string;
    "old_string": string;
    "new_string": string;
    "replace_all"?: boolean;

    /** Creates a new EditLocalFileParams instance. */
    constructor($$source: Partial<EditLocalFileParams> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("old_string" in $$source)) {
            this["old_string"] = "";
        }
        if (!("new_string" in $$source)) {
            this["new_string"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditLocalFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): EditLocalFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditLocalFileParams($$parsedSource as Partial<EditLocalFileParams>);
    }
}

/**
 * EditLocalFileResult result of editing a file
 */
export class EditLocalFileResult {
    "success": boolean;
    "replacements": number;
    "error"?: string;

    /** Creates a new EditLocalFileResult instance. */
    constructor($$source: Partial<EditLocalFileResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("replacements" in $$source)) {
            this["replacements"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditLocalFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EditLocalFileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EditLocalFileResult($$parsedSource as Partial<EditLocalFileResult>);
    }
}

/**
 * GetCommandOutputParams parameters for getting command output
 */
export class GetCommandOutputParams {
    "shell_id": string;
    "filter"?: string;

    /** Creates a new GetCommandOutputParams instance. */
    constructor($$source: Partial<GetCommandOutputParams> = {}) {
        if (!("shell_id" in $$source)) {
            this["shell_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetCommandOutputParams instance from a string or object.
     */
    static createFrom($$source: any = {}): GetCommandOutputParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetCommandOutputParams($$parsedSource as Partial<GetCommandOutputParams>);
    }
}

/**
 * GetCommandOutputResult result of getting command output
 */
export class GetCommandOutputResult {
    "success": boolean;
    "output": string;
    "stdout": string;
    "stderr": string;
    "running": boolean;
    "error"?: string;

    /** Creates a new GetCommandOutputResult instance. */
    constructor($$source: Partial<GetCommandOutputResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("stdout" in $$source)) {
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            this["stderr"] = "";
        }
        if (!("running" in $$source)) {
            this["running"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetCommandOutputResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GetCommandOutputResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetCommandOutputResult($$parsedSource as Partial<GetCommandOutputResult>);
    }
}

/**
 * GlobFilesParams parameters for glob file search
 */
export class GlobFilesParams {
    "pattern": string;
    "path"?: string;

    /** Creates a new GlobFilesParams instance. */
    constructor($$source: Partial<GlobFilesParams> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobFilesParams instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobFilesParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlobFilesParams($$parsedSource as Partial<GlobFilesParams>);
    }
}

/**
 * GlobFilesResult result of glob file search
 */
export class GlobFilesResult {
    "success": boolean;
    "files": string[];
    "total_files": number;

    /** Creates a new GlobFilesResult instance. */
    constructor($$source: Partial<GlobFilesResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("total_files" in $$source)) {
            this["total_files"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlobFilesResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GlobFilesResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new GlobFilesResult($$parsedSource as Partial<GlobFilesResult>);
    }
}

/**
 * GrepContentParams parameters for grep content search
 */
export class GrepContentParams {
    "pattern": string;
    "path"?: string;
    "type"?: string;
    "glob"?: string;

    /**
     * "content", "files_with_matches", "count"
     */
    "output_mode"?: string;
    "multiline"?: boolean;
    "-i"?: boolean;
    "-n"?: boolean;

    /**
     * Lines after
     */
    "-A"?: number;

    /**
     * Lines before
     */
    "-B"?: number;

    /**
     * Lines around
     */
    "-C"?: number;
    "head_limit"?: number;

    /** Creates a new GrepContentParams instance. */
    constructor($$source: Partial<GrepContentParams> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GrepContentParams instance from a string or object.
     */
    static createFrom($$source: any = {}): GrepContentParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GrepContentParams($$parsedSource as Partial<GrepContentParams>);
    }
}

/**
 * GrepContentResult result of grep content search
 */
export class GrepContentResult {
    "success": boolean;
    "matches": string[];
    "total_matches": number;

    /** Creates a new GrepContentResult instance. */
    constructor($$source: Partial<GrepContentResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }
        if (!("total_matches" in $$source)) {
            this["total_matches"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GrepContentResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GrepContentResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new GrepContentResult($$parsedSource as Partial<GrepContentResult>);
    }
}

/**
 * KillCommandParams parameters for killing a command
 */
export class KillCommandParams {
    "shell_id": string;

    /** Creates a new KillCommandParams instance. */
    constructor($$source: Partial<KillCommandParams> = {}) {
        if (!("shell_id" in $$source)) {
            this["shell_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillCommandParams instance from a string or object.
     */
    static createFrom($$source: any = {}): KillCommandParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillCommandParams($$parsedSource as Partial<KillCommandParams>);
    }
}

/**
 * KillCommandResult result of killing a command
 */
export class KillCommandResult {
    "success": boolean;
    "error"?: string;

    /** Creates a new KillCommandResult instance. */
    constructor($$source: Partial<KillCommandResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KillCommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): KillCommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KillCommandResult($$parsedSource as Partial<KillCommandResult>);
    }
}

/**
 * ListLocalFileParams parameters for listing files
 */
export class ListLocalFileParams {
    "path": string;

    /** Creates a new ListLocalFileParams instance. */
    constructor($$source: Partial<ListLocalFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListLocalFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ListLocalFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListLocalFileParams($$parsedSource as Partial<ListLocalFileParams>);
    }
}

/**
 * LocalFileItem represents a file or directory item
 */
export class LocalFileItem {
    "name": string;
    "path": string;
    "size": number;
    "type": string;
    "isDirectory": boolean;
    "contentType"?: string;
    "createdTime": time$0.Time;
    "modifiedTime": time$0.Time;
    "lastAccessTime": time$0.Time;
    "metadata"?: { [_: string]: any };

    /** Creates a new LocalFileItem instance. */
    constructor($$source: Partial<LocalFileItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("isDirectory" in $$source)) {
            this["isDirectory"] = false;
        }
        if (!("createdTime" in $$source)) {
            this["createdTime"] = null;
        }
        if (!("modifiedTime" in $$source)) {
            this["modifiedTime"] = null;
        }
        if (!("lastAccessTime" in $$source)) {
            this["lastAccessTime"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalFileItem instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalFileItem {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField9_0($$parsedSource["metadata"]);
        }
        return new LocalFileItem($$parsedSource as Partial<LocalFileItem>);
    }
}

/**
 * LocalMoveFilesResultItem result of moving a single file
 */
export class LocalMoveFilesResultItem {
    "sourcePath": string;
    "newPath"?: string;
    "success": boolean;
    "error"?: string;

    /** Creates a new LocalMoveFilesResultItem instance. */
    constructor($$source: Partial<LocalMoveFilesResultItem> = {}) {
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalMoveFilesResultItem instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalMoveFilesResultItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalMoveFilesResultItem($$parsedSource as Partial<LocalMoveFilesResultItem>);
    }
}

/**
 * LocalReadFileParams parameters for reading a file
 */
export class LocalReadFileParams {
    "path": string;

    /**
     * Optional line range [start, end]
     */
    "loc"?: number[] | null;

    /** Creates a new LocalReadFileParams instance. */
    constructor($$source: Partial<LocalReadFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalReadFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalReadFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalReadFileParams($$parsedSource as Partial<LocalReadFileParams>);
    }
}

/**
 * LocalReadFileResult result of reading a file
 */
export class LocalReadFileResult {
    "content": string;
    "filename": string;
    "fileType": string;
    "charCount": number;
    "lineCount": number;
    "totalCharCount": number;
    "totalLineCount": number;
    "loc": number[];
    "createdTime": time$0.Time;
    "modifiedTime": time$0.Time;

    /** Creates a new LocalReadFileResult instance. */
    constructor($$source: Partial<LocalReadFileResult> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("fileType" in $$source)) {
            this["fileType"] = "";
        }
        if (!("charCount" in $$source)) {
            this["charCount"] = 0;
        }
        if (!("lineCount" in $$source)) {
            this["lineCount"] = 0;
        }
        if (!("totalCharCount" in $$source)) {
            this["totalCharCount"] = 0;
        }
        if (!("totalLineCount" in $$source)) {
            this["totalLineCount"] = 0;
        }
        if (!("loc" in $$source)) {
            this["loc"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("createdTime" in $$source)) {
            this["createdTime"] = null;
        }
        if (!("modifiedTime" in $$source)) {
            this["modifiedTime"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalReadFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalReadFileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalReadFileResult($$parsedSource as Partial<LocalReadFileResult>);
    }
}

/**
 * LocalReadFilesParams parameters for reading multiple files
 */
export class LocalReadFilesParams {
    "paths": string[];

    /** Creates a new LocalReadFilesParams instance. */
    constructor($$source: Partial<LocalReadFilesParams> = {}) {
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalReadFilesParams instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalReadFilesParams {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new LocalReadFilesParams($$parsedSource as Partial<LocalReadFilesParams>);
    }
}

/**
 * LocalSearchFilesParams parameters for searching files
 */
export class LocalSearchFilesParams {
    "keywords": string;
    "directory"?: string;

    /** Creates a new LocalSearchFilesParams instance. */
    constructor($$source: Partial<LocalSearchFilesParams> = {}) {
        if (!("keywords" in $$source)) {
            this["keywords"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalSearchFilesParams instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalSearchFilesParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalSearchFilesParams($$parsedSource as Partial<LocalSearchFilesParams>);
    }
}

/**
 * MoveLocalFileParams parameters for moving a single file
 */
export class MoveLocalFileParams {
    "oldPath": string;
    "newPath": string;

    /** Creates a new MoveLocalFileParams instance. */
    constructor($$source: Partial<MoveLocalFileParams> = {}) {
        if (!("oldPath" in $$source)) {
            this["oldPath"] = "";
        }
        if (!("newPath" in $$source)) {
            this["newPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveLocalFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): MoveLocalFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MoveLocalFileParams($$parsedSource as Partial<MoveLocalFileParams>);
    }
}

/**
 * MoveLocalFilesParams parameters for moving multiple files
 */
export class MoveLocalFilesParams {
    "items": MoveLocalFileParams[];

    /** Creates a new MoveLocalFilesParams instance. */
    constructor($$source: Partial<MoveLocalFilesParams> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveLocalFilesParams instance from a string or object.
     */
    static createFrom($$source: any = {}): MoveLocalFilesParams {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new MoveLocalFilesParams($$parsedSource as Partial<MoveLocalFilesParams>);
    }
}

/**
 * OpenLocalFileParams parameters for opening a file
 */
export class OpenLocalFileParams {
    "path": string;

    /** Creates a new OpenLocalFileParams instance. */
    constructor($$source: Partial<OpenLocalFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenLocalFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenLocalFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenLocalFileParams($$parsedSource as Partial<OpenLocalFileParams>);
    }
}

/**
 * OpenLocalFolderParams parameters for opening a folder
 */
export class OpenLocalFolderParams {
    "path": string;
    "isDirectory"?: boolean;

    /** Creates a new OpenLocalFolderParams instance. */
    constructor($$source: Partial<OpenLocalFolderParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenLocalFolderParams instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenLocalFolderParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenLocalFolderParams($$parsedSource as Partial<OpenLocalFolderParams>);
    }
}

/**
 * RenameLocalFileParams parameters for renaming a file
 */
export class RenameLocalFileParams {
    "path": string;
    "newName": string;

    /** Creates a new RenameLocalFileParams instance. */
    constructor($$source: Partial<RenameLocalFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("newName" in $$source)) {
            this["newName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameLocalFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameLocalFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameLocalFileParams($$parsedSource as Partial<RenameLocalFileParams>);
    }
}

/**
 * RenameLocalFileResult result of renaming a file
 */
export class RenameLocalFileResult {
    "newPath": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new RenameLocalFileResult instance. */
    constructor($$source: Partial<RenameLocalFileResult> = {}) {
        if (!("newPath" in $$source)) {
            this["newPath"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameLocalFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameLocalFileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameLocalFileResult($$parsedSource as Partial<RenameLocalFileResult>);
    }
}

/**
 * RunCommandParams parameters for running a command
 */
export class RunCommandParams {
    "command": string;
    "description"?: string;
    "run_in_background"?: boolean;

    /**
     * Timeout in seconds
     */
    "timeout"?: number;

    /** Creates a new RunCommandParams instance. */
    constructor($$source: Partial<RunCommandParams> = {}) {
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunCommandParams instance from a string or object.
     */
    static createFrom($$source: any = {}): RunCommandParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunCommandParams($$parsedSource as Partial<RunCommandParams>);
    }
}

/**
 * RunCommandResult result of running a command
 */
export class RunCommandResult {
    "success": boolean;
    "output"?: string;
    "stdout"?: string;
    "stderr"?: string;
    "exit_code"?: number;
    "shell_id"?: string;
    "error"?: string;

    /** Creates a new RunCommandResult instance. */
    constructor($$source: Partial<RunCommandResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunCommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): RunCommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunCommandResult($$parsedSource as Partial<RunCommandResult>);
    }
}

/**
 * WriteFileResult result of writing a file
 */
export class WriteFileResult {
    "path": string;
    "success": boolean;
    "message": string;
    "error"?: string;

    /** Creates a new WriteFileResult instance. */
    constructor($$source: Partial<WriteFileResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriteFileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): WriteFileResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriteFileResult($$parsedSource as Partial<WriteFileResult>);
    }
}

/**
 * WriteLocalFileParams parameters for writing a file
 */
export class WriteLocalFileParams {
    "path": string;
    "content": string;

    /** Creates a new WriteLocalFileParams instance. */
    constructor($$source: Partial<WriteLocalFileParams> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriteLocalFileParams instance from a string or object.
     */
    static createFrom($$source: any = {}): WriteLocalFileParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriteLocalFileParams($$parsedSource as Partial<WriteLocalFileParams>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = MoveLocalFileParams.createFrom;
const $$createType3 = $Create.Array($$createType2);
