// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StableDiffusion handles Stable Diffusion CPP release management
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckInstalledModels checks what Stable Diffusion models are currently installed
 */
export function CheckInstalledModels(): $CancellablePromise<string[]> {
    return $Call.ByID(299752267).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * CreateImage handles frontend CreateImageRequest and generates images
 */
export function CreateImage(req: $models.CreateImageRequest): $CancellablePromise<void> {
    return $Call.ByID(3099831724, req);
}

/**
 * CreateImageWithOptions generates an image using GenerationOptions directly
 * Used by internal services like image_designer
 */
export function CreateImageWithOptions(opts: $models.GenerationOptions): $CancellablePromise<void> {
    return $Call.ByID(1379676314, opts);
}

/**
 * GetFirstAvailableModel returns the first available SD model
 */
export function GetFirstAvailableModel(): $CancellablePromise<string> {
    return $Call.ByID(3045849309);
}

/**
 * GetModelPath returns the full path to a specific model file
 */
export function GetModelPath(filename: string): $CancellablePromise<string> {
    return $Call.ByID(4139656469, filename);
}

/**
 * GetModelsPath returns the path where Stable Diffusion models are stored
 */
export function GetModelsPath(): $CancellablePromise<string> {
    return $Call.ByID(3531692384);
}

/**
 * GetOutputsPath returns the path for generated images
 */
export function GetOutputsPath(): $CancellablePromise<string> {
    return $Call.ByID(1891601522);
}

/**
 * IsStableDiffusionInstalled checks if Stable Diffusion binary exists and is valid
 */
export function IsStableDiffusionInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(1014732463);
}

/**
 * VerifyChecksum verifies the downloaded file against the provided checksums
 */
export function VerifyChecksum(filePath: string, checksumPath: string, binaryName: string): $CancellablePromise<void> {
    return $Call.ByID(2336978029, filePath, checksumPath, binaryName);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
