// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as message$0 from "../../pkg/yzma/message/models.js";

/**
 * YzmaResponse represents a response from yzma model generation
 */
export class YzmaResponse {
    "Content": string;
    "ToolCalls": message$0.ToolCall[];
    "FinishReason": string;
    "PromptTokens": number;
    "CompletionTokens": number;
    "TotalTokens": number;

    /** Creates a new YzmaResponse instance. */
    constructor($$source: Partial<YzmaResponse> = {}) {
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("ToolCalls" in $$source)) {
            this["ToolCalls"] = [];
        }
        if (!("FinishReason" in $$source)) {
            this["FinishReason"] = "";
        }
        if (!("PromptTokens" in $$source)) {
            this["PromptTokens"] = 0;
        }
        if (!("CompletionTokens" in $$source)) {
            this["CompletionTokens"] = 0;
        }
        if (!("TotalTokens" in $$source)) {
            this["TotalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new YzmaResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): YzmaResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ToolCalls" in $$parsedSource) {
            $$parsedSource["ToolCalls"] = $$createField1_0($$parsedSource["ToolCalls"]);
        }
        return new YzmaResponse($$parsedSource as Partial<YzmaResponse>);
    }
}

// Private type creation functions
const $$createType0 = message$0.ToolCall.createFrom;
const $$createType1 = $Create.Array($$createType0);
