// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides LLM inference using llama.cpp
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoDownloadRecommendedModel automatically downloads the best model for the system using llama-cli
 */
export function AutoDownloadRecommendedModel(): $CancellablePromise<void> {
    return $Call.ByID(2081361982);
}

/**
 * DownloadModelWithLlamaCLI downloads a model using llama-cli's built-in HuggingFace integration
 */
export function DownloadModelWithLlamaCLI(modelSpec: $models.QwenModelSpec): $CancellablePromise<void> {
    return $Call.ByID(2719622767, modelSpec);
}

/**
 * GetAvailableModels returns a list of available GGUF models
 */
export function GetAvailableModels(): $CancellablePromise<string[]> {
    return $Call.ByID(3259973076).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetBinaryPath returns the path to the llama.cpp binary directory
 */
export function GetBinaryPath(): $CancellablePromise<string> {
    return $Call.ByID(518447565);
}

/**
 * GetInstalledVersion returns the currently installed version
 */
export function GetInstalledVersion(): $CancellablePromise<string> {
    return $Call.ByID(532345125);
}

/**
 * GetModelsDirectory returns the directory where models are stored
 */
export function GetModelsDirectory(): $CancellablePromise<string> {
    return $Call.ByID(3697124908);
}

/**
 * GetServerStatus returns the current status of llama-server
 */
export function GetServerStatus(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(4274510970).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetServerURL returns the URL of the running llama-server
 */
export function GetServerURL(): $CancellablePromise<string> {
    return $Call.ByID(2175291209);
}

/**
 * IsLlamaCppInstalled checks if llama.cpp is installed
 */
export function IsLlamaCppInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(3445623667);
}

/**
 * IsServerRunning checks if llama-server is running by making a health check request
 */
export function IsServerRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1675216765);
}

/**
 * StartServer starts the llama-server with automatic model selection
 * If modelPath is empty, automatically selects the best available model
 */
export function StartServer(modelPath: string, port: number): $CancellablePromise<void> {
    return $Call.ByID(1079204088, modelPath, port);
}

/**
 * StartServerAuto starts the llama-server with automatic model selection
 * This is the recommended way to start the server for Kawai AI
 */
export function StartServerAuto(): $CancellablePromise<void> {
    return $Call.ByID(372018223);
}

/**
 * StopServer stops the llama-server if it's running
 */
export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(2894379918);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
