// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Clear deletes all keys from the store. If AutoSave is true, the store is saved to disk.
 */
export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(1632336053);
}

/**
 * Delete deletes the given key from the store. If AutoSave is true, the store is saved to disk.
 */
export function Delete(key: string): $CancellablePromise<void> {
    return $Call.ByID(2549287475, key);
}

/**
 * Get returns the value for the given key. If key is empty, the entire store is returned.
 */
export function Get(key: string): $CancellablePromise<any> {
    return $Call.ByID(535628692, key);
}

/**
 * Load loads the store from disk.
 * If the store is in-memory, i.e. not associated with a file, Load has no effect.
 * If the operation fails, a non-nil error is returned
 * and the store's content and state at call time are preserved.
 */
export function Load(): $CancellablePromise<void> {
    return $Call.ByID(4243932388);
}

/**
 * Save saves the store to disk.
 * If the store is in-memory, i.e. not associated with a file, Save has no effect.
 */
export function Save(): $CancellablePromise<void> {
    return $Call.ByID(2249758213);
}

/**
 * Set sets the value for the given key. If AutoSave is true, the store is saved to disk.
 */
export function Set(key: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(986790344, key, value);
}
