// Code generated by obfuscator-gen. DO NOT EDIT.
package constant

import (
	"math/rand"
	"time"

	"github.com/kawai-network/veridium/pkg/obfuscator"
)

const (
	obfuscatedEtherscanApiKey0 = "B48m5RsJKX0oipiQGfgi2+Dco+hz+Cyq4JLm6/16uXcH3H=="
	obfuscatedEtherscanApiKey1 = "5Nf2r1Zf+LxtQrUWolLErEzceCZSn3Qxw31661DvuVp7gH=="
	obfuscatedEtherscanApiKey2 = "QS0zzxnx7g6H06U+Uz6FvxS+EiaA5luA96ha95v6dsR7jn=="
	obfuscatedEtherscanApiKey3 = "hIbg5PFdUoBvPe4+Z5OiM+CxsEywl8Rs9rHxf1vS1cQsod=="
)

// GetRandomEtherscanApiKey returns a random decoded Etherscan API key from the pool
func GetRandomEtherscanApiKey() string {
	keys := getEtherscanApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// getEtherscanApiKeys returns a slice of all decoded Etherscan API keys
func getEtherscanApiKeys() []string {
	return []string{
		getEtherscanApiKey0(),
		getEtherscanApiKey1(),
		getEtherscanApiKey2(),
		getEtherscanApiKey3(),
	}
}

func getEtherscanApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedEtherscanApiKey0)
	return val
}

func getEtherscanApiKey1() string {
	val, _ := obfuscator.DecodeString(obfuscatedEtherscanApiKey1)
	return val
}

func getEtherscanApiKey2() string {
	val, _ := obfuscator.DecodeString(obfuscatedEtherscanApiKey2)
	return val
}

func getEtherscanApiKey3() string {
	val, _ := obfuscator.DecodeString(obfuscatedEtherscanApiKey3)
	return val
}

