// Code generated by obfuscator-gen. DO NOT EDIT.
package constant

import (
	"math/rand"
	"time"

	"github.com/kawai-network/veridium/pkg/obfuscator"
)

const (
	// OpenRouter API Keys
	obfuscatedOpenRouterApiKey0 = "TDl/o2/F9clGOo7OPoqvlwe0yKmXMn6hKJgdbQn6kDkFTfr3SDB+8oZ2wtJMLFJVBa1azOPuGGu5PCQfmcEG9WKpsG+bkO9irD=="
	obfuscatedOpenRouterApiKey1 = "TDl/o2/F9clGJivj+5yTpwe05sW0/zVufPeh0eGl+JLhvliZSEk87F7VKVselrCezHoRquqVDqRQAQgvm53q9w4RsG+wAk18mt=="
	obfuscatedOpenRouterApiKey2 = "TDl/o2/F9clGOwDOJhcOtEfQyGF8/wMh1a6h0WljmJnAVmvYWjZTMhzGx/kYNrFUduYEO9G5ot459j1Dya6+JfGFQt7nkAfMNt=="

	// ZAI API Keys
	obfuscatedZaiApiKey0 = "0gTbgkb9uV+C97WJR/s9cwJvzxKq1uKb/dod9XwkqVjNMIRsh5L6/0PTRJL79Xl0iX=="

	// Gemini API Keys
	obfuscatedGeminiApiKey0 = "jurKk47h4Ql57hi8fPan0+HK/Eg69I0jQX3y4Gr895xZlDpi2VGT"
	obfuscatedGeminiApiKey1 = "jurKW47hxwl6dau6cbLmKN4E6TI43LuqeTURMQz8+EMWCTEwe68l"
	obfuscatedGeminiApiKey2 = "jurKAW7h4QlemojgalMnYzoZ4k/ioJmD9D1Nt5Y14GsfIBog2VWT"
	obfuscatedGeminiApiKey3 = "jurKuW7hxwinol3nFl1AlBEEcE37hg8P88/IIGFpRtqtgC9wcJyT"
)

// GetRandomOpenRouterApiKey returns a random decoded OpenRouter API key from the pool
func GetRandomOpenRouterApiKey() string {
	keys := GetOpenRouterApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetOpenRouterApiKeys returns a slice of all decoded OpenRouter API keys
func GetOpenRouterApiKeys() []string {
	return []string{
		getOpenRouterApiKey0(),
		getOpenRouterApiKey1(),
		getOpenRouterApiKey2(),
	}
}

func getOpenRouterApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey0)
	return val
}

func getOpenRouterApiKey1() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey1)
	return val
}

func getOpenRouterApiKey2() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey2)
	return val
}

// GetRandomZaiApiKey returns a random decoded ZAI API key from the pool
func GetRandomZaiApiKey() string {
	keys := GetZaiApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetZaiApiKeys returns a slice of all decoded ZAI API keys
func GetZaiApiKeys() []string {
	return []string{
		getZaiApiKey0(),
	}
}

func getZaiApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedZaiApiKey0)
	return val
}

// GetRandomGeminiApiKey returns a random decoded Gemini API key from the pool
func GetRandomGeminiApiKey() string {
	keys := GetGeminiApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetGeminiApiKeys returns a slice of all decoded Gemini API keys
func GetGeminiApiKeys() []string {
	return []string{
		getGeminiApiKey0(),
		getGeminiApiKey1(),
		getGeminiApiKey2(),
		getGeminiApiKey3(),
	}
}

func getGeminiApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey0)
	return val
}

func getGeminiApiKey1() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey1)
	return val
}

func getGeminiApiKey2() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey2)
	return val
}

func getGeminiApiKey3() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey3)
	return val
}

