// Code generated by obfuscator-gen. DO NOT EDIT.
package constant

import (
	"math/rand"
	"time"

	"github.com/kawai-network/veridium/pkg/obfuscator"
)

const (
	// OpenRouter API Keys
	obfuscatedOpenRouterApiKey0 = "TDl/o2/F9clGOo7OPoqvlwe0yKmXMn6hKJgdbQn6kDkFTfr3SDB+8oZ2wtJMLFJVBa1azOPuGGu5PCQfmcEG9WKpsG+bkO9irD=="
	obfuscatedOpenRouterApiKey1 = "TDl/o2/F9clGJivj+5yTpwe05sW0/zVufPeh0eGl+JLhvliZSEk87F7VKVselrCezHoRquqVDqRQAQgvm53q9w4RsG+wAk18mt=="
	obfuscatedOpenRouterApiKey2 = "TDl/o2/F9clGOwDOJhcOtEfQyGF8/wMh1a6h0WljmJnAVmvYWjZTMhzGx/kYNrFUduYEO9G5ot459j1Dya6+JfGFQt7nkAfMNt=="
	obfuscatedOpenRouterApiKey3 = "TDl/o2/F9clGG04mJXy1pyOgSY9AOwAxRpkd1xzM+NiiYW00v6BK+m+rpBMyGm5abU8CwGCuZD/UO07Dy3aHS0vl7dWnyfb8DD=="
	obfuscatedOpenRouterApiKey4 = "TDl/o2/F9clGli8mwj3frjW3L84dHXuxIcPw0gpjOb6K+z0o0Uks8l7+7DGDYX/VJDCRCRJbMFOGM7kfhi2Z3MWpvWPg8AyQvD=="
	obfuscatedOpenRouterApiKey5 = "TDl/o2/F9clGJuuNMz3ocdwMfKmkJpogslgq+selZTCncdbPvuPKMuzVxmg0GjVUdoGEy9D5kN4GskMfhUGkrYtRo5uUA4IkYD=="
	obfuscatedOpenRouterApiKey6 = "TDl/o2/F9clGlojtYxfhdmcjfY80kzU31cOzHqNhLyJotj/cvwQiGlxAwLuDJa/VFb9ZqwD5Gp9zM+6Nnp9JFcCwtoANyzt8Rj=="

	// ZAI API Keys
	obfuscatedZaiApiKey0 = "0gTbgkb9uV+C97WJR/s9cwJvzxKq1uKb/dod9XwkqVjNMIRsh5L6/0PTRJL79Xl0iX=="

	// Gemini API Keys
	obfuscatedGeminiApiKey0 = "jurKk47h4Ql57hi8fPan0+HK/Eg69I0jQX3y4Gr895xZlDpi2VGT"
	obfuscatedGeminiApiKey1 = "jurKW47hxwl6dau6cbLmKN4E6TI43LuqeTURMQz8+EMWCTEwe68l"
	obfuscatedGeminiApiKey2 = "jurKAW7h4QlemojgalMnYzoZ4k/ioJmD9D1Nt5Y14GsfIBog2VWT"
	obfuscatedGeminiApiKey3 = "jurKuW7hxwinol3nFl1AlBEEcE37hg8P88/IIGFpRtqtgC9wcJyT"
	obfuscatedGeminiApiKey4 = "jurKIW7hxwlXVuJN/CEl0hEkaPI6naPK/9YqZoC1dWiiKMRE8E/m"
	obfuscatedGeminiApiKey5 = "jurKfW7hlwk7L7Gc5MTAL1HaohAxzK1e44fn6trJo8zUsK2zEpfC"
	obfuscatedGeminiApiKey6 = "jurKL47hAGktHiwpOSmrwVv4yqAxinVEp85nHJF2a6624USCgjvm"
	obfuscatedGeminiApiKey7 = "jurKGm7hxwl5b3P6/zE6OP5p/H8OOmWTXd2b9IvQYK/RKOeCdV+0"

	// HuggingFace API Keys
	obfuscatedHfApiKey0 = "n8WdhNgeIksx6PtFWC6jUBvfC9wsd9MomzF7sNvzeaEXlZPQbX=="
	obfuscatedHfApiKey1 = "n+EdObueQVE7Vku7khATJ5Mt0SGLG6ZPmQO6yoQU+JVbSdMtVN=="
	obfuscatedHfApiKey2 = "n3cdCE8e0W/uVmaJ6hJvxx4llxgZ4I5N/lZAOSTbXD7FCVRB6t=="

	// Cloudflare API Keys
	obfuscatedCloudflareApiKey0 = "9RJQVl4nh4mmGy97+4LotVv7tO8E2QMLxaWCE6DhxV/QSTI9bCE/f0Yw+DYPr7m/L+9JzlH43XVlcbVRPZhhw0sgLJOEGzB3nj=="
)

// GetRandomOpenRouterApiKey returns a random decoded OpenRouter API key from the pool
func GetRandomOpenRouterApiKey() string {
	keys := GetOpenRouterApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetOpenRouterApiKeys returns a slice of all decoded OpenRouter API keys
func GetOpenRouterApiKeys() []string {
	return []string{
		getOpenRouterApiKey0(),
		getOpenRouterApiKey1(),
		getOpenRouterApiKey2(),
		getOpenRouterApiKey3(),
		getOpenRouterApiKey4(),
		getOpenRouterApiKey5(),
		getOpenRouterApiKey6(),
	}
}

func getOpenRouterApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey0)
	return val
}

func getOpenRouterApiKey1() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey1)
	return val
}

func getOpenRouterApiKey2() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey2)
	return val
}

func getOpenRouterApiKey3() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey3)
	return val
}

func getOpenRouterApiKey4() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey4)
	return val
}

func getOpenRouterApiKey5() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey5)
	return val
}

func getOpenRouterApiKey6() string {
	val, _ := obfuscator.DecodeString(obfuscatedOpenRouterApiKey6)
	return val
}

// GetRandomZaiApiKey returns a random decoded ZAI API key from the pool
func GetRandomZaiApiKey() string {
	keys := GetZaiApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetZaiApiKeys returns a slice of all decoded ZAI API keys
func GetZaiApiKeys() []string {
	return []string{
		getZaiApiKey0(),
	}
}

func getZaiApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedZaiApiKey0)
	return val
}

// GetRandomGeminiApiKey returns a random decoded Gemini API key from the pool
func GetRandomGeminiApiKey() string {
	keys := GetGeminiApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetGeminiApiKeys returns a slice of all decoded Gemini API keys
func GetGeminiApiKeys() []string {
	return []string{
		getGeminiApiKey0(),
		getGeminiApiKey1(),
		getGeminiApiKey2(),
		getGeminiApiKey3(),
		getGeminiApiKey4(),
		getGeminiApiKey5(),
		getGeminiApiKey6(),
		getGeminiApiKey7(),
	}
}

func getGeminiApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey0)
	return val
}

func getGeminiApiKey1() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey1)
	return val
}

func getGeminiApiKey2() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey2)
	return val
}

func getGeminiApiKey3() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey3)
	return val
}

func getGeminiApiKey4() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey4)
	return val
}

func getGeminiApiKey5() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey5)
	return val
}

func getGeminiApiKey6() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey6)
	return val
}

func getGeminiApiKey7() string {
	val, _ := obfuscator.DecodeString(obfuscatedGeminiApiKey7)
	return val
}

// GetRandomHfApiKey returns a random decoded HuggingFace API key from the pool
func GetRandomHfApiKey() string {
	keys := GetHfApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetHfApiKeys returns a slice of all decoded HuggingFace API keys
func GetHfApiKeys() []string {
	return []string{
		getHfApiKey0(),
		getHfApiKey1(),
		getHfApiKey2(),
	}
}

func getHfApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedHfApiKey0)
	return val
}

func getHfApiKey1() string {
	val, _ := obfuscator.DecodeString(obfuscatedHfApiKey1)
	return val
}

func getHfApiKey2() string {
	val, _ := obfuscator.DecodeString(obfuscatedHfApiKey2)
	return val
}

// GetRandomCloudflareApiKey returns a random decoded Cloudflare API key from the pool
func GetRandomCloudflareApiKey() string {
	keys := GetCloudflareApiKeys()
	if len(keys) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	return keys[r.Intn(len(keys))]
}

// GetCloudflareApiKeys returns a slice of all decoded Cloudflare API keys
func GetCloudflareApiKeys() []string {
	return []string{
		getCloudflareApiKey0(),
	}
}

func getCloudflareApiKey0() string {
	val, _ := obfuscator.DecodeString(obfuscatedCloudflareApiKey0)
	return val
}

