// Code generated by obfuscator-gen. DO NOT EDIT.
package constant

import "github.com/kawai-network/veridium/pkg/obfuscator"

const (
	obfuscatedAdminPrivateKey = "OMsmRu3fGlqOR7ycZZE256SVIhT6eEXdfBnh3H30eSlR2Z14vN6AILbdfsAvYyr7Bf+YHCJRr13D4NBtXklUuJ=="
	obfuscatedAdminAddress = "u+Dw6+NhTMch9nCXSZo6ciIFWZlT/ijfETnGnGNWSSHU7tq1Sh5T0/tm"
)

// GetAdminPrivateKey returns the decoded value of ADMIN_PRIVATE_KEY
// Admin Private Key for contract operations
func GetAdminPrivateKey() string {
	val, _ := obfuscator.DecodeString(obfuscatedAdminPrivateKey)
	return val
}

// GetAdminAddress returns the decoded value of ADMIN_ADDRESS
// Admin Address for contract operations
func GetAdminAddress() string {
	val, _ := obfuscator.DecodeString(obfuscatedAdminAddress)
	return val
}

