// Code generated by obfuscator-gen. DO NOT EDIT.
package constant

import (
	"math/rand"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/kawai-network/veridium/pkg/obfuscator"
)

const (
	obfuscatedTreasuryAddress0 = "u+B5orNhPxXoaYxrUln1AR2uIyP/gsiVEbIRMTdvmQTkO9pq0B76ZWqW"
	obfuscatedTreasuryAddress1 = "u97wL//hA0aGIvvirTEfE4VlIPkT4nwVR8sSMfzV58Tyi4mHiL5rZatq"
	obfuscatedTreasuryAddress2 = "u9insKBhqrjtCF7MDnrYE9ULbzgCFYccRgrvuLH/C3A/h3bVF8uVQ7lq"
	obfuscatedTreasuryAddress3 = "u8601BNhw5XkP75ejk5mE/pRMasT4BucEqkSZBl1C76izrDnSiNiRGqm"
	obfuscatedTreasuryAddress4 = "u755odNhn87iVLDdSg7YEipX3qw34GMUdSWmaGtBVLYGuG/VSL9kQOJR"
	obfuscatedTreasuryAddress5 = "ueLTepphqK+xmG8sSg6zEr+sWXwCVpMcRxcrHGt3kbYdzwLeIPY/37xm"
)

// GetRandomTreasuryAddress returns a random decoded Treasury Address from the pool
func GetRandomTreasuryAddress() string {
	addresses := GetTreasuryAddresses()
	if len(addresses) == 0 {
		return ""
	}
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	address := addresses[r.Intn(len(addresses))]
	return common.HexToAddress(address).Hex()
}

// GetTreasuryAddresses returns a slice of all decoded Treasury Addresses
func GetTreasuryAddresses() []string {
	return []string{
		getTreasuryAddress0(),
		getTreasuryAddress1(),
		getTreasuryAddress2(),
		getTreasuryAddress3(),
		getTreasuryAddress4(),
		getTreasuryAddress5(),
	}
}

func getTreasuryAddress0() string {
	val, _ := obfuscator.DecodeString(obfuscatedTreasuryAddress0)
	return val
}

func getTreasuryAddress1() string {
	val, _ := obfuscator.DecodeString(obfuscatedTreasuryAddress1)
	return val
}

func getTreasuryAddress2() string {
	val, _ := obfuscator.DecodeString(obfuscatedTreasuryAddress2)
	return val
}

func getTreasuryAddress3() string {
	val, _ := obfuscator.DecodeString(obfuscatedTreasuryAddress3)
	return val
}

func getTreasuryAddress4() string {
	val, _ := obfuscator.DecodeString(obfuscatedTreasuryAddress4)
	return val
}

func getTreasuryAddress5() string {
	val, _ := obfuscator.DecodeString(obfuscatedTreasuryAddress5)
	return val
}

