// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides table viewer operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchDelete deletes multiple rows
 */
export function BatchDelete(tableName: string, ids: string[], primaryKeyColumn: string): $CancellablePromise<void> {
    return $Call.ByID(3959824018, tableName, ids, primaryKeyColumn);
}

/**
 * DeleteRow deletes a row from the table
 */
export function DeleteRow(tableName: string, id: string, primaryKeyColumn: string): $CancellablePromise<void> {
    return $Call.ByID(4158710876, tableName, id, primaryKeyColumn);
}

/**
 * ExecuteRawQuery executes a raw SQL query and returns results as JSON
 * This is useful for the PgTable UI to execute arbitrary queries
 */
export function ExecuteRawQuery(query: string, args: any[]): $CancellablePromise<string> {
    return $Call.ByID(3174662508, query, args);
}

/**
 * GetAllTables returns all tables and views in the database
 */
export function GetAllTables(): $CancellablePromise<$models.TableBasicInfo[]> {
    return $Call.ByID(4272964945).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTableData returns paginated table data with optional filtering and sorting
 */
export function GetTableData(tableName: string, pagination: $models.PaginationParams, filters: $models.FilterCondition[]): $CancellablePromise<$models.TableDataResult | null> {
    return $Call.ByID(1297343527, tableName, pagination, filters).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTableDetails returns detailed structure information for a table
 */
export function GetTableDetails(tableName: string): $CancellablePromise<$models.TableColumnInfo[]> {
    return $Call.ByID(2199566679, tableName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * InsertRow inserts a new row into the table
 */
export function InsertRow(tableName: string, data: { [_: string]: any }): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(919879878, tableName, data).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpdateRow updates a row in the table
 */
export function UpdateRow(tableName: string, id: string, primaryKeyColumn: string, data: { [_: string]: any }): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(553819574, tableName, id, primaryKeyColumn, data).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TableBasicInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.TableDataResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.TableColumnInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
