// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentChatService provides agent-based chat with RAG, tools, and context awareness
 * This replaces/complements the existing LibraryChatService with Eino-based capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../../cloudwego/eino/schema/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Chat processes a chat request and returns a response
 */
export function Chat(req: $models.ChatRequest): $CancellablePromise<$models.ChatResponse | null> {
    return $Call.ByID(3994848739, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ChatStream processes a chat request with streaming response
 * TODO: Implement streaming via Wails v3 events API once documented
 */
export function ChatStream(req: $models.ChatRequest): $CancellablePromise<$models.ChatResponse | null> {
    return $Call.ByID(3398888139, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearSession removes a session from memory
 */
export function ClearSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3298569262, sessionID);
}

/**
 * GetReasoningConfig returns the current reasoning configuration
 */
export function GetReasoningConfig(): $CancellablePromise<$models.ReasoningConfig> {
    return $Call.ByID(46956079).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetReasoningMode returns the current reasoning mode
 */
export function GetReasoningMode(): $CancellablePromise<$models.ReasoningMode> {
    return $Call.ByID(2342951530);
}

/**
 * GetRecommendedModelForMode returns the recommended model for current reasoning mode
 */
export function GetRecommendedModelForMode(): $CancellablePromise<string> {
    return $Call.ByID(1751664809);
}

/**
 * GetSessionHistory returns the message history for a session
 */
export function GetSessionHistory(sessionID: string): $CancellablePromise<(schema$0.Message | null)[]> {
    return $Call.ByID(396946379, sessionID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SetReasoningMode sets the reasoning mode for the service
 * This affects all new conversations created after this call
 */
export function SetReasoningMode(mode: $models.ReasoningMode): $CancellablePromise<void> {
    return $Call.ByID(3600806230, mode);
}

/**
 * SwitchToRecommendedModel loads the recommended model for current reasoning mode
 */
export function SwitchToRecommendedModel(): $CancellablePromise<void> {
    return $Call.ByID(3072995856);
}

/**
 * ValidateModelForReasoningMode checks if the currently loaded model is appropriate
 */
export function ValidateModelForReasoningMode(): $CancellablePromise<void> {
    return $Call.ByID(483038906);
}

// Private type creation functions
const $$createType0 = $models.ChatResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ReasoningConfig.createFrom;
const $$createType3 = schema$0.Message.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
