// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentChatService provides agent-based chat with RAG, tools, and context awareness
 * This replaces/complements the existing LibraryChatService with Yzma-based capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fantasy$0 from "../../fantasy/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../../pkg/yzma/tools/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChatMock handles mock chat responses for testing UI flow without real AI backend
 * This method saves complete mock messages to DB with all UI components:
 * - Reasoning (step-by-step thinking)
 * - RAG Chunks (file chunks with similarity scores)
 * - Tool Calls (web browsing, local file system)
 * - Tool Messages (separate role='tool' messages with results)
 * - Search Grounding (citations from web search)
 * - Images (placeholder images)
 * - Usage & Performance metrics
 * 
 * Returns array of all messages created: [user, assistant, tool1, tool2, ...]
 * This matches the real flow where frontend fetches all messages from DB.
 * 
 * Usage from frontend:
 * 
 * 	const messages = await AgentChatService.ChatMock(request);
 * 	// messages is array: [userMsg, assistantMsg, toolMsg1, toolMsg2, ...]
 */
export function ChatMock(req: $models.ChatRequest): $CancellablePromise<$models.UIChatMessage[]> {
    return $Call.ByID(944716749, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ChatMockStream handles mock chat with event streaming for realistic UI testing
 * Instead of returning all messages at once, it emits events progressively:
 * 1. start - Generation begins
 * 2. reasoning - Thinking content (streamed)
 * 3. chunk - Content chunks (streamed word by word)
 * 4. tool_call - Tool call initiated
 * 5. tool_result - Tool execution result (with pluginState)
 * 6. complete - Generation finished
 * 
 * Frontend listens to 'chat:stream' events via Events.On()
 * Data is saved to DB at the end (same as ChatMock)
 * 
 * Usage from frontend:
 * 
 * 	await AgentChatService.ChatMockStream(request);
 * 	// No return value - data comes via events
 * 	// Events.On('chat:stream', handler) receives all updates
 */
export function ChatMockStream(req: $models.ChatRequest): $CancellablePromise<void> {
    return $Call.ByID(3416642717, req);
}

/**
 * ChatRealStream handles chat with REAL LLM calls using event streaming.
 * This combines:
 * - Real LLM logic from Chat() in agent_chat_service.go
 * - Streaming architecture from ChatMockStream
 * 
 * Flow:
 * 1. start - Generation begins
 * 2. reasoning - Real thinking content from LLM (if reasoning model)
 * 3. chunk - Real content chunks from LLM
 * 4. tool_call - Real tool call initiated by LLM
 * 5. tool_result - Real tool execution result
 * 6. complete - Generation finished
 * 
 * Frontend listens to 'chat:stream' events via Events.On()
 * Data is saved to DB at the end.
 * 
 * Usage from frontend:
 * 
 * 	await AgentChatService.ChatRealStream(request);
 * 	// No return value - data comes via events
 * 	// Events.On('chat:stream', handler) receives all updates
 */
export function ChatRealStream(req: $models.ChatRequest): $CancellablePromise<void> {
    return $Call.ByID(564759359, req);
}

/**
 * GetStreamEventPayloadType returns an empty StreamEventPayload for type inference.
 * This method exists to expose StreamEventPayload in Wails bindings.
 * Frontend can use this type for handling 'chat:stream' events.
 */
export function GetStreamEventPayloadType(): $CancellablePromise<$models.StreamEventPayload> {
    return $Call.ByID(1681290149).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetToolRegistry returns the tool registry for external configuration
 */
export function GetToolRegistry(): $CancellablePromise<tools$0.ToolRegistry | null> {
    return $Call.ByID(306369018).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetChatModel sets the main chat model (for streaming chat with tools)
 */
export function SetChatModel(model: fantasy$0.LanguageModel): $CancellablePromise<void> {
    return $Call.ByID(8199130, model);
}

/**
 * SetSummaryModel sets the summary generation model
 */
export function SetSummaryModel(model: fantasy$0.LanguageModel): $CancellablePromise<void> {
    return $Call.ByID(3154586890, model);
}

/**
 * SetTitleModel sets the title generation model
 */
export function SetTitleModel(model: fantasy$0.LanguageModel): $CancellablePromise<void> {
    return $Call.ByID(468930904, model);
}

// Private type creation functions
const $$createType0 = $models.UIChatMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.StreamEventPayload.createFrom;
const $$createType3 = tools$0.ToolRegistry.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
