// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentChatService provides agent-based chat with RAG, tools, and context awareness
 * This replaces/complements the existing LibraryChatService with Yzma-based capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as message$0 from "../../pkg/yzma/message/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Chat processes a chat request and returns a response
 */
export function Chat(req: $models.ChatRequest): $CancellablePromise<$models.ChatResponse | null> {
    return $Call.ByID(3994848739, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ChatMock handles mock chat responses for testing UI flow without real AI backend
 * This method returns a simple mock response that matches ChatResponse structure
 * 
 * Usage from frontend:
 * 
 * 	const response = await AgentChatService.ChatMock(request);
 * 
 * Note: This is a simplified mock that doesn't save to DB or handle streaming.
 * For full mock with all UI components (reasoning, tools, chunks, etc.),
 * the frontend currently handles mock data directly in generateAIChat.ts
 */
export function ChatMock(req: $models.ChatRequest): $CancellablePromise<$models.ChatResponse | null> {
    return $Call.ByID(944716749, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClearSession removes a session from memory
 */
export function ClearSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3298569262, sessionID);
}

/**
 * GetLLMGenerator returns the current LLM generator
 */
export function GetLLMGenerator(): $CancellablePromise<$models.LLMGenerator> {
    return $Call.ByID(1599155355);
}

/**
 * GetReasoningConfig returns the current reasoning configuration
 */
export function GetReasoningConfig(): $CancellablePromise<$models.ReasoningConfig> {
    return $Call.ByID(46956079).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetReasoningMode returns the current reasoning mode
 */
export function GetReasoningMode(): $CancellablePromise<$models.ReasoningMode> {
    return $Call.ByID(2342951530);
}

/**
 * GetRecommendedModelForMode returns the recommended model for current reasoning mode
 */
export function GetRecommendedModelForMode(): $CancellablePromise<string> {
    return $Call.ByID(1751664809);
}

/**
 * GetSessionHistory returns the message history for a session (native yzma format)
 */
export function GetSessionHistory(sessionID: string): $CancellablePromise<message$0.Message[]> {
    return $Call.ByID(396946379, sessionID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetLLMGenerator sets a custom LLM generator (useful for testing with mocks)
 */
export function SetLLMGenerator(generator: $models.LLMGenerator): $CancellablePromise<void> {
    return $Call.ByID(3521022399, generator);
}

/**
 * SetReasoningMode sets the reasoning mode for the service
 * This affects all new conversations created after this call
 * Validates hardware specs before allowing resource-intensive reasoning modes
 */
export function SetReasoningMode(mode: $models.ReasoningMode): $CancellablePromise<void> {
    return $Call.ByID(3600806230, mode);
}

/**
 * SetTitleModel sets a specific model for title generation
 * Use a small, fast model (e.g., Llama 3.2 1B) for efficiency
 * If not set, falls back to main chat model
 */
export function SetTitleModel(modelPath: string): $CancellablePromise<void> {
    return $Call.ByID(468930904, modelPath);
}

/**
 * SwitchToRecommendedModel loads the recommended model for current reasoning mode
 */
export function SwitchToRecommendedModel(): $CancellablePromise<void> {
    return $Call.ByID(3072995856);
}

/**
 * ValidateModelForReasoningMode checks if the currently loaded model is appropriate
 */
export function ValidateModelForReasoningMode(): $CancellablePromise<void> {
    return $Call.ByID(483038906);
}

// Private type creation functions
const $$createType0 = $models.ChatResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ReasoningConfig.createFrom;
const $$createType3 = $Create.Array($Create.Any);
