// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes backend configuration to frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns current backend configuration
 * This reads from internal/constant which is generated from .env
 */
export function GetConfig(): $CancellablePromise<$models.BackendConfig> {
    return $Call.ByID(1652334452).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetContractAddress returns specific contract address by name
 */
export function GetContractAddress(name: string): $CancellablePromise<string> {
    return $Call.ByID(924450040, name);
}

/**
 * GetContracts returns all contract addresses
 */
export function GetContracts(): $CancellablePromise<$models.ContractAddresses> {
    return $Call.ByID(3186057345).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEnvironment returns current environment name
 */
export function GetEnvironment(): $CancellablePromise<string> {
    return $Call.ByID(315484295);
}

/**
 * GetNetwork returns current network configuration
 */
export function GetNetwork(): $CancellablePromise<$models.NetworkEnvironment> {
    return $Call.ByID(1049879064).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * IsMainnet returns true if running on mainnet
 */
export function IsMainnet(): $CancellablePromise<boolean> {
    return $Call.ByID(3074131790);
}

/**
 * IsTestnet returns true if running on testnet
 */
export function IsTestnet(): $CancellablePromise<boolean> {
    return $Call.ByID(1434956869);
}

// Private type creation functions
const $$createType0 = $models.BackendConfig.createFrom;
const $$createType1 = $models.ContractAddresses.createFrom;
const $$createType2 = $models.NetworkEnvironment.createFrom;
