// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeAIService handles interactions with the Veridium smart contracts
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveToken approves a spender to spend a specific token
 */
export function ApproveToken(tokenName: string, spenderStr: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(1430028655, tokenName, spenderStr, amountStr);
}

/**
 * ApproveUSDT approves a spender to spend MockUSDT
 */
export function ApproveUSDT(spenderStr: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(946882682, spenderStr, amountStr);
}

/**
 * BuyOrder buys an order from the OTC Market
 */
export function BuyOrder(orderIdStr: string): $CancellablePromise<string> {
    return $Call.ByID(288290637, orderIdStr);
}

/**
 * ClaimCashbackReward claims deposit cashback rewards using a Merkle proof
 * Uses the DepositCashbackDistributor contract with period-based claims
 */
export function ClaimCashbackReward(period: number, kawaiAmount: string, proof: string[]): $CancellablePromise<$models.ClaimResult | null> {
    return $Call.ByID(139037128, period, kawaiAmount, proof).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClaimKawaiReward claims KAWAI rewards using a Merkle proof
 */
export function ClaimKawaiReward(periodID: number, index: number, amount: string, proof: string[]): $CancellablePromise<$models.ClaimResult | null> {
    return $Call.ByID(1586412849, periodID, index, amount, proof).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClaimMiningReward claims mining rewards with referral-based splits
 * Uses the new MiningRewardDistributor contract with 9-field Merkle leaves
 */
export function ClaimMiningReward(period: number, contributorAmount: string, developerAmount: string, userAmount: string, affiliatorAmount: string, developerAddress: string, userAddress: string, affiliatorAddress: string, proof: string[]): $CancellablePromise<$models.ClaimResult | null> {
    return $Call.ByID(3916078352, period, contributorAmount, developerAmount, userAmount, affiliatorAmount, developerAddress, userAddress, affiliatorAddress, proof).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ClaimUSDTReward claims USDT rewards using a Merkle proof
 */
export function ClaimUSDTReward(periodID: number, index: number, amount: string, proof: string[]): $CancellablePromise<$models.ClaimResult | null> {
    return $Call.ByID(1243120848, periodID, index, amount, proof).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ConfirmRewardClaim confirms a reward claim after the transaction is confirmed on-chain
 */
export function ConfirmRewardClaim(periodID: number): $CancellablePromise<void> {
    return $Call.ByID(2988904612, periodID);
}

/**
 * CreateSellOrder creates a sell order in the OTC Market
 */
export function CreateSellOrder(tokenAmountStr: string, priceStr: string): $CancellablePromise<string> {
    return $Call.ByID(3964541039, tokenAmountStr, priceStr);
}

/**
 * DepositToVault deposits USDT into the vault for service credits
 */
export function DepositToVault(amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(2547645408, amountStr);
}

/**
 * GetClaimableRewards fetches all claimable rewards for the current wallet
 * Uses Cloudflare KV store directly for off-chain Merkle proof data
 */
export function GetClaimableRewards(): $CancellablePromise<$models.ClaimableRewardsResponse | null> {
    return $Call.ByID(1243461775).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetDistributorMerkleRoot returns the current Merkle root from a distributor contract
 */
export function GetDistributorMerkleRoot(rewardType: string): $CancellablePromise<string> {
    return $Call.ByID(3557111590, rewardType);
}

/**
 * GetUSDTAllowance returns the current allowance of owner to spender
 */
export function GetUSDTAllowance(ownerStr: string, spenderStr: string): $CancellablePromise<string> {
    return $Call.ByID(3908918835, ownerStr, spenderStr);
}

/**
 * GetVaultBalance returns the USDT balance of the current wallet
 */
export function GetVaultBalance(): $CancellablePromise<string> {
    return $Call.ByID(4000684215);
}

/**
 * IsRewardClaimed checks if a specific reward has already been claimed on-chain
 */
export function IsRewardClaimed(rewardType: string, index: number): $CancellablePromise<boolean> {
    return $Call.ByID(2715141111, rewardType, index);
}

/**
 * MarkClaimFailed marks a claim as failed after the transaction reverts
 */
export function MarkClaimFailed(periodID: number, reason: string): $CancellablePromise<void> {
    return $Call.ByID(2017968369, periodID, reason);
}

/**
 * MintTestTokens mints MockUSDT and KawaiTokens to the caller (for testing only)
 */
export function MintTestTokens(): $CancellablePromise<string> {
    return $Call.ByID(1596408719);
}

/**
 * TransferNative sends native coin (MON, ETH) from the current wallet to a recipient
 */
export function TransferNative(to: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(3297709697, to, amountStr);
}

/**
 * TransferToken sends any ERC20 token from the current wallet to a recipient
 */
export function TransferToken(tokenAddress: string, to: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(1059336147, tokenAddress, to, amountStr);
}

/**
 * TransferUSDT sends USDT from the current wallet to a recipient
 */
export function TransferUSDT(to: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(1311324606, to, amountStr);
}

/**
 * WaitForClaimConfirmation waits for a claim transaction to be mined
 */
export function WaitForClaimConfirmation(txHash: string): $CancellablePromise<boolean> {
    return $Call.ByID(3856604776, txHash);
}

// Private type creation functions
const $$createType0 = $models.ClaimResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ClaimableRewardsResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
