// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeAIService handles interactions with the Veridium smart contracts
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ApproveToken approves a spender to spend a specific token
 */
export function ApproveToken(tokenName: string, spenderStr: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(1430028655, tokenName, spenderStr, amountStr);
}

/**
 * ApproveUSDT approves a spender to spend MockUSDT
 */
export function ApproveUSDT(spenderStr: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(946882682, spenderStr, amountStr);
}

/**
 * BuyOrder buys an order from the OTC Market
 */
export function BuyOrder(orderIdStr: string): $CancellablePromise<string> {
    return $Call.ByID(288290637, orderIdStr);
}

/**
 * CreateSellOrder creates a sell order in the OTC Market
 */
export function CreateSellOrder(tokenAmountStr: string, priceStr: string): $CancellablePromise<string> {
    return $Call.ByID(3964541039, tokenAmountStr, priceStr);
}

/**
 * DepositToVault deposits USDT into the vault for service credits
 */
export function DepositToVault(amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(2547645408, amountStr);
}

/**
 * GetUSDTAllowance returns the current allowance of owner to spender
 */
export function GetUSDTAllowance(ownerStr: string, spenderStr: string): $CancellablePromise<string> {
    return $Call.ByID(3908918835, ownerStr, spenderStr);
}

/**
 * GetVaultBalance returns the USDT balance of the current wallet
 */
export function GetVaultBalance(): $CancellablePromise<string> {
    return $Call.ByID(4000684215);
}

/**
 * MintTestTokens mints MockUSDT and KawaiTokens to the caller (for testing only)
 */
export function MintTestTokens(): $CancellablePromise<string> {
    return $Call.ByID(1596408719);
}

/**
 * TransferNative sends native coin (MON, ETH) from the current wallet to a recipient
 */
export function TransferNative(to: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(3297709697, to, amountStr);
}

/**
 * TransferToken sends any ERC20 token from the current wallet to a recipient
 */
export function TransferToken(tokenAddress: string, to: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(1059336147, tokenAddress, to, amountStr);
}

/**
 * TransferUSDT sends USDT from the current wallet to a recipient
 */
export function TransferUSDT(to: string, amountStr: string): $CancellablePromise<string> {
    return $Call.ByID(1311324606, to, amountStr);
}
