// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService handles local file storage operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CreatePreSignedUrl creates pre-signed upload URL (for local files, just returns path)
 */
export function CreatePreSignedUrl(key: string): $CancellablePromise<string> {
    return $Call.ByID(1826759100, key);
}

/**
 * CreatePreSignedUrlForPreview creates pre-signed preview URL
 */
export function CreatePreSignedUrlForPreview(key: string): $CancellablePromise<string> {
    return $Call.ByID(3275868261, key);
}

/**
 * DeleteFile deletes a single file
 */
export function DeleteFile(key: string): $CancellablePromise<void> {
    return $Call.ByID(948831131, key);
}

/**
 * DeleteFiles batch deletes files
 */
export function DeleteFiles(keys: string[]): $CancellablePromise<void> {
    return $Call.ByID(4019201592, keys);
}

/**
 * GetFileByteArray gets file byte array
 */
export function GetFileByteArray(key: string): $CancellablePromise<string> {
    return $Call.ByID(4080885587, key).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * GetFileContent gets file content as string
 */
export function GetFileContent(key: string): $CancellablePromise<string> {
    return $Call.ByID(804575277, key);
}

/**
 * GetFullFileUrl gets complete file URL (for local files, returns the key)
 */
export function GetFullFileUrl(fileUrl: string): $CancellablePromise<string> {
    return $Call.ByID(2209997786, fileUrl);
}

/**
 * GetKeyFromFullUrl extracts key from complete URL
 */
export function GetKeyFromFullUrl(fullUrl: string): $CancellablePromise<string> {
    return $Call.ByID(2384010965, fullUrl);
}

/**
 * ReadFileFromAbsolutePath reads file from absolute path (for drag & drop)
 */
export function ReadFileFromAbsolutePath(absolutePath: string): $CancellablePromise<string> {
    return $Call.ByID(2083098666, absolutePath).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * UploadContent uploads content (not implemented)
 */
export function UploadContent(filePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(471472544, filePath, content);
}

/**
 * UploadMedia uploads media file
 * buffer parameter can be either:
 * - []byte: raw binary data
 * - string: base64-encoded data (for Wails binding compatibility)
 */
export function UploadMedia(key: string, buffer: any): $CancellablePromise<string> {
    return $Call.ByID(4262710761, key, buffer);
}
