// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService wraps LocalFileStorage to provide high-level file operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CopyFileFromAbsolutePath copies file from absolute path to local storage (for drag & drop)
 */
export function CopyFileFromAbsolutePath(absolutePath: string): $CancellablePromise<string> {
    return $Call.ByID(4059871, absolutePath);
}

/**
 * CreatePreSignedUrl creates pre-signed upload URL
 */
export function CreatePreSignedUrl(key: string): $CancellablePromise<string> {
    return $Call.ByID(1826759100, key);
}

/**
 * CreatePreSignedUrlForPreview creates pre-signed preview URL
 */
export function CreatePreSignedUrlForPreview(key: string): $CancellablePromise<string> {
    return $Call.ByID(3275868261, key);
}

/**
 * DeleteFile deletes file
 */
export function DeleteFile(key: string): $CancellablePromise<void> {
    return $Call.ByID(948831131, key);
}

/**
 * DeleteFiles batch deletes files
 */
export function DeleteFiles(keys: string[]): $CancellablePromise<void> {
    return $Call.ByID(4019201592, keys);
}

/**
 * DownloadFileToLocal downloads file to local temp storage
 */
export function DownloadFileToLocal(fileId: string): $CancellablePromise<[any, $models.FileItem | null, string]> {
    return $Call.ByID(1042652032, fileId).then(($result: any) => {
        $result[1] = $$createType1($result[1]);
        return $result;
    });
}

/**
 * GetFileByteArray gets file byte array
 */
export function GetFileByteArray(key: string): $CancellablePromise<string> {
    return $Call.ByID(4080885587, key).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * GetFileContent gets file content
 */
export function GetFileContent(key: string): $CancellablePromise<string> {
    return $Call.ByID(804575277, key);
}

/**
 * GetFullFileUrl gets complete file URL
 */
export function GetFullFileUrl(url: string): $CancellablePromise<string> {
    return $Call.ByID(2209997786, url);
}

/**
 * GetKeyFromFullUrl extracts key from full URL
 */
export function GetKeyFromFullUrl(url: string): $CancellablePromise<string> {
    return $Call.ByID(2384010965, url);
}

/**
 * ReadFileFromAbsolutePath reads file from absolute path (for drag & drop)
 */
export function ReadFileFromAbsolutePath(absolutePath: string): $CancellablePromise<string> {
    return $Call.ByID(2083098666, absolutePath).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * UploadContent uploads content
 */
export function UploadContent(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(471472544, path, content);
}

/**
 * UploadMedia uploads media file
 */
export function UploadMedia(key: string, buffer: any): $CancellablePromise<string> {
    return $Call.ByID(4262710761, key, buffer);
}

// Private type creation functions
const $$createType0 = $models.FileItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
