// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService handles transaction history storage using SQLite database
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTransaction records a new transaction
 */
export function AddTransaction(txHash: string, txType: $models.TransactionType, amount: string, $from: string, to: string, desc: string): $CancellablePromise<void> {
    return $Call.ByID(2957658695, txHash, txType, amount, $from, to, desc);
}

/**
 * AddTransactionWithDetails records a new transaction with full details
 */
export function AddTransactionWithDetails(txHash: string, txType: $models.TransactionType, amount: string, $from: string, to: string, desc: string, tokenAddress: string, tokenSymbol: string, tokenDecimals: number, blockNumber: number, network: string, chainID: number, gasUsed: string, gasPrice: string, nonce: number, status: string): $CancellablePromise<void> {
    return $Call.ByID(3031256167, txHash, txType, amount, $from, to, desc, tokenAddress, tokenSymbol, tokenDecimals, blockNumber, network, chainID, gasUsed, gasPrice, nonce, status);
}

/**
 * ClearHistory deletes all records (use with caution)
 */
export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(2992028437);
}

/**
 * GetPendingTransactions returns all pending transactions
 */
export function GetPendingTransactions(): $CancellablePromise<$models.TransactionRecord[]> {
    return $Call.ByID(1178234580).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTransactionByHash returns a specific transaction by hash
 */
export function GetTransactionByHash(txHash: string): $CancellablePromise<$models.TransactionRecord | null> {
    return $Call.ByID(286479267, txHash).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetTransactions returns the list of transactions (latest 100 by default)
 */
export function GetTransactions(): $CancellablePromise<$models.TransactionRecord[]> {
    return $Call.ByID(1114448747).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTransactionsByAddress returns transactions for a specific address
 */
export function GetTransactionsByAddress(address: string, limit: number, offset: number): $CancellablePromise<$models.TransactionRecord[]> {
    return $Call.ByID(3499846046, address, limit, offset).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateTransactionStatus updates the status of a transaction
 */
export function UpdateTransactionStatus(txHash: string, status: string, blockNumber: number): $CancellablePromise<void> {
    return $Call.ByID(3975989575, txHash, status, blockNumber);
}

// Private type creation functions
const $$createType0 = $models.TransactionRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
