// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * JarvisService provides blockchain utilities from the jarvis package
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeTransaction decodes and analyzes a transaction
 */
export function AnalyzeTransaction(txHash: string, networkID: number): $CancellablePromise<$models.TxAnalysis | null> {
    return $Call.ByID(1099877993, txHash, networkID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * EstimateGas returns gas price estimates for a network
 */
export function EstimateGas(networkID: number): $CancellablePromise<$models.GasEstimate | null> {
    return $Call.ByID(328337004, networkID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetCurrentBlock returns the current block number
 */
export function GetCurrentBlock(networkID: number): $CancellablePromise<number> {
    return $Call.ByID(1711179501, networkID);
}

/**
 * GetNativeBalance returns the native token balance for an address
 */
export function GetNativeBalance(address: string, networkID: number): $CancellablePromise<$models.BalanceInfo | null> {
    return $Call.ByID(1485810044, address, networkID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetNetworkByID returns a specific network by chain ID
 */
export function GetNetworkByID(chainID: number): $CancellablePromise<$models.NetworkInfo | null> {
    return $Call.ByID(2828509811, chainID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSupportedNetworks returns all supported blockchain networks
 */
export function GetSupportedNetworks(): $CancellablePromise<$models.NetworkInfo[]> {
    return $Call.ByID(792631060).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetTokenAllowance returns the allowance of a token
 */
export function GetTokenAllowance(tokenAddress: string, owner: string, spender: string, networkID: number): $CancellablePromise<$models.BalanceInfo | null> {
    return $Call.ByID(3499575274, tokenAddress, owner, spender, networkID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTokenBalance returns the ERC20 token balance for an address
 */
export function GetTokenBalance(tokenAddress: string, walletAddress: string, networkID: number): $CancellablePromise<$models.BalanceInfo | null> {
    return $Call.ByID(3231083804, tokenAddress, walletAddress, networkID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTokenInfo fetches ERC20 token information from the blockchain
 */
export function GetTokenInfo(tokenAddress: string, networkID: number): $CancellablePromise<$models.TokenInfo | null> {
    return $Call.ByID(2532907732, tokenAddress, networkID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetTokenPrice returns the price of a token in USD
 */
export function GetTokenPrice(token: string, networkID: number): $CancellablePromise<number> {
    return $Call.ByID(615768821, token, networkID);
}

/**
 * IsContract checks if an address is a smart contract
 */
export function IsContract(address: string, networkID: number): $CancellablePromise<boolean> {
    return $Call.ByID(3633456199, address, networkID);
}

/**
 * LookupKnownToken checks if an address is in the known tokens database
 */
export function LookupKnownToken(address: string): $CancellablePromise<[string, boolean]> {
    return $Call.ByID(3863721275, address);
}

/**
 * ValidateAddress checks if a string is a valid EVM address
 */
export function ValidateAddress(address: string): $CancellablePromise<boolean> {
    return $Call.ByID(2666162693, address);
}

// Private type creation functions
const $$createType0 = $models.TxAnalysis.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GasEstimate.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.BalanceInfo.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.NetworkInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType6);
const $$createType9 = $models.TokenInfo.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
