// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KnowledgeBaseService manages knowledge bases with RAG capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../../cloudwego/eino/schema/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../database/generated/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chromem$0 from "../../pkg/eino-adapters/chromem/models.js";

/**
 * AddFileToKnowledgeBase adds a file to a knowledge base
 */
export function AddFileToKnowledgeBase(kbID: string, filePath: string, metadata: { [_: string]: any }, userID: string): $CancellablePromise<void> {
    return $Call.ByID(2844550582, kbID, filePath, metadata, userID);
}

/**
 * CreateKnowledgeBase creates a new knowledge base
 */
export function CreateKnowledgeBase(name: string, description: string, userID: string): $CancellablePromise<string> {
    return $Call.ByID(3872143208, name, description, userID);
}

/**
 * DeleteKnowledgeBase deletes a knowledge base
 */
export function DeleteKnowledgeBase(kbID: string, userID: string): $CancellablePromise<void> {
    return $Call.ByID(4015852381, kbID, userID);
}

/**
 * GetFileManager returns the file manager for a knowledge base
 */
export function GetFileManager(kbID: string, userID: string): $CancellablePromise<chromem$0.FileManager | null> {
    return $Call.ByID(2759124646, kbID, userID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetIndexer returns the Eino indexer for a knowledge base
 */
export function GetIndexer(kbID: string, userID: string): $CancellablePromise<chromem$0.Indexer | null> {
    return $Call.ByID(4150070740, kbID, userID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetKnowledgeBase gets a knowledge base by ID
 */
export function GetKnowledgeBase(kbID: string, userID: string): $CancellablePromise<db$0.KnowledgeBasis> {
    return $Call.ByID(830733914, kbID, userID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRetriever returns the Eino retriever for a knowledge base
 * This is used in RAG workflows and agent tools
 */
export function GetRetriever(kbID: string, userID: string): $CancellablePromise<chromem$0.Retriever | null> {
    return $Call.ByID(1834383765, kbID, userID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * ListKnowledgeBases lists all knowledge bases for a user
 */
export function ListKnowledgeBases(userID: string): $CancellablePromise<db$0.KnowledgeBasis[]> {
    return $Call.ByID(4122219297, userID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * QueryKnowledgeBase performs semantic search on a knowledge base
 */
export function QueryKnowledgeBase(kbID: string, query: string, topK: number, userID: string): $CancellablePromise<(schema$0.Document | null)[]> {
    return $Call.ByID(3310437766, kbID, query, topK, userID).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * RemoveFileFromKnowledgeBase removes a file from a knowledge base
 */
export function RemoveFileFromKnowledgeBase(kbID: string, fileID: string, userID: string): $CancellablePromise<void> {
    return $Call.ByID(3683533694, kbID, fileID, userID);
}

/**
 * UpdateKnowledgeBase updates a knowledge base
 */
export function UpdateKnowledgeBase(kbID: string, name: string, description: string, userID: string): $CancellablePromise<void> {
    return $Call.ByID(1928072071, kbID, name, description, userID);
}

// Private type creation functions
const $$createType0 = chromem$0.FileManager.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = chromem$0.Indexer.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = db$0.KnowledgeBasis.createFrom;
const $$createType5 = chromem$0.Retriever.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType4);
const $$createType8 = schema$0.Document.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
