// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChunkData represents chunk data for vector storage
 */
export class ChunkData {
    "id": string;
    "text": string;
    "fileId": string;
    "fileName": string;
    "type": string;
    "index": number;
    "metadata": { [_: string]: string };

    /** Creates a new ChunkData instance. */
    constructor($$source: Partial<ChunkData> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChunkData instance from a string or object.
     */
    static createFrom($$source: any = {}): ChunkData {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField6_0($$parsedSource["metadata"]);
        }
        return new ChunkData($$parsedSource as Partial<ChunkData>);
    }
}

/**
 * ProcessFileResponse represents the result of file processing
 */
export class ProcessFileResponse {
    "fileId": string;
    "documentId": string;
    "chunkIds"?: string[];
    "globalFileId"?: string;

    /** Creates a new ProcessFileResponse instance. */
    constructor($$source: Partial<ProcessFileResponse> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("documentId" in $$source)) {
            this["documentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessFileResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessFileResponse {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chunkIds" in $$parsedSource) {
            $$parsedSource["chunkIds"] = $$createField2_0($$parsedSource["chunkIds"]);
        }
        return new ProcessFileResponse($$parsedSource as Partial<ProcessFileResponse>);
    }
}

/**
 * SearchResult represents a search result from vector database
 */
export class SearchResult {
    "id": string;
    "similarity": number;
    "text": string;
    "fileId": string;
    "fileName": string;
    "type": string;
    "index": number;
    "metadata": { [_: string]: string };

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("similarity" in $$source)) {
            this["similarity"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
