// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../pkg/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$1 from "../../types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * BackendConfig represents the complete backend configuration
 */
export class BackendConfig {
    /**
     * "testnet" | "mainnet"
     */
    "environment": string;
    "network": NetworkEnvironment;
    "contracts": ContractAddresses;

    /** Creates a new BackendConfig instance. */
    constructor($$source: Partial<BackendConfig> = {}) {
        if (!("environment" in $$source)) {
            this["environment"] = "";
        }
        if (!("network" in $$source)) {
            this["network"] = (new NetworkEnvironment());
        }
        if (!("contracts" in $$source)) {
            this["contracts"] = (new ContractAddresses());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackendConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BackendConfig {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("network" in $$parsedSource) {
            $$parsedSource["network"] = $$createField1_0($$parsedSource["network"]);
        }
        if ("contracts" in $$parsedSource) {
            $$parsedSource["contracts"] = $$createField2_0($$parsedSource["contracts"]);
        }
        return new BackendConfig($$parsedSource as Partial<BackendConfig>);
    }
}

/**
 * BalanceInfo represents a balance result
 */
export class BalanceInfo {
    "raw": string;
    "formatted": string;
    "decimals": number;

    /** Creates a new BalanceInfo instance. */
    constructor($$source: Partial<BalanceInfo> = {}) {
        if (!("raw" in $$source)) {
            this["raw"] = "";
        }
        if (!("formatted" in $$source)) {
            this["formatted"] = "";
        }
        if (!("decimals" in $$source)) {
            this["decimals"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BalanceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BalanceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BalanceInfo($$parsedSource as Partial<BalanceInfo>);
    }
}

/**
 * CashbackStatsResponse represents cashback statistics for the frontend
 */
export class CashbackStatsResponse {
    /**
     * Total KAWAI earned (wei)
     */
    "total_cashback": string;

    /**
     * Pending (unclaimed) (wei)
     */
    "pending_cashback": string;

    /**
     * Already claimed (wei)
     */
    "claimed_cashback": string;

    /**
     * Number of deposits
     */
    "total_deposits": number;

    /**
     * Total USDT deposited (wei, 6 decimals)
     */
    "total_deposit_amount": string;

    /**
     * ISO timestamp
     */
    "first_deposit_at": string;

    /**
     * ISO timestamp
     */
    "last_deposit_at": string;

    /** Creates a new CashbackStatsResponse instance. */
    constructor($$source: Partial<CashbackStatsResponse> = {}) {
        if (!("total_cashback" in $$source)) {
            this["total_cashback"] = "";
        }
        if (!("pending_cashback" in $$source)) {
            this["pending_cashback"] = "";
        }
        if (!("claimed_cashback" in $$source)) {
            this["claimed_cashback"] = "";
        }
        if (!("total_deposits" in $$source)) {
            this["total_deposits"] = 0;
        }
        if (!("total_deposit_amount" in $$source)) {
            this["total_deposit_amount"] = "";
        }
        if (!("first_deposit_at" in $$source)) {
            this["first_deposit_at"] = "";
        }
        if (!("last_deposit_at" in $$source)) {
            this["last_deposit_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CashbackStatsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CashbackStatsResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CashbackStatsResponse($$parsedSource as Partial<CashbackStatsResponse>);
    }
}

/**
 * ChatCompletionMessage represents a message in the completion request
 */
export class ChatCompletionMessage {
    "role": string;
    "content": string;

    /** Creates a new ChatCompletionMessage instance. */
    constructor($$source: Partial<ChatCompletionMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatCompletionMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatCompletionMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatCompletionMessage($$parsedSource as Partial<ChatCompletionMessage>);
    }
}

/**
 * ChatCompletionRequest represents a stateless chat completion request
 * This is used for tasks like translation, summarization, etc.
 */
export class ChatCompletionRequest {
    "model": string;
    "provider": string;
    "messages": ChatCompletionMessage[];

    /** Creates a new ChatCompletionRequest instance. */
    constructor($$source: Partial<ChatCompletionRequest> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatCompletionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatCompletionRequest {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField2_0($$parsedSource["messages"]);
        }
        return new ChatCompletionRequest($$parsedSource as Partial<ChatCompletionRequest>);
    }
}

/**
 * ChatFileChunk represents a file chunk from RAG system
 */
export class ChatFileChunk {
    "fileId": string;
    "fileType": string;
    "fileUrl": string;
    "filename": string;
    "id": string;
    "similarity"?: number;
    "text": string;

    /** Creates a new ChatFileChunk instance. */
    constructor($$source: Partial<ChatFileChunk> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("fileType" in $$source)) {
            this["fileType"] = "";
        }
        if (!("fileUrl" in $$source)) {
            this["fileUrl"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatFileChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatFileChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatFileChunk($$parsedSource as Partial<ChatFileChunk>);
    }
}

/**
 * ChatImageItem represents an image attachment
 */
export class ChatImageItem {
    "alt"?: string;
    "id": string;
    "url": string;

    /** Creates a new ChatImageItem instance. */
    constructor($$source: Partial<ChatImageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatImageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatImageItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatImageItem($$parsedSource as Partial<ChatImageItem>);
    }
}

/**
 * ChatMessageError represents an error in a message
 */
export class ChatMessageError {
    "body"?: any;
    "message": string;
    "type": string;

    /** Creates a new ChatMessageError instance. */
    constructor($$source: Partial<ChatMessageError> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageError instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessageError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessageError($$parsedSource as Partial<ChatMessageError>);
    }
}

/**
 * ChatPluginPayload represents a plugin call payload
 */
export class ChatPluginPayload {
    "apiName": string;
    "arguments": string;
    "identifier": string;
    "type": string;

    /** Creates a new ChatPluginPayload instance. */
    constructor($$source: Partial<ChatPluginPayload> = {}) {
        if (!("apiName" in $$source)) {
            this["apiName"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = "";
        }
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatPluginPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatPluginPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatPluginPayload($$parsedSource as Partial<ChatPluginPayload>);
    }
}

/**
 * ChatRequest represents a chat request with agent capabilities
 */
export class ChatRequest {
    /**
     * Identity
     */
    "session_id": string;
    "user_id": string;

    /**
     * Message content
     */
    "message": string;

    /**
     * Message IDs (pre-generated by frontend for optimistic UI)
     * Pre-generated user message ID
     */
    "message_user_id"?: string;

    /**
     * Pre-generated assistant message ID
     */
    "message_assistant_id"?: string;

    /**
     * Context (Phase 4: Topic & Thread support)
     * Current topic (may be auto-created)
     */
    "topic_id"?: string;

    /**
     * Current thread (for branching)
     */
    "thread_id"?: string;

    /**
     * Parent message (for threading)
     */
    "parent_id"?: string;

    /**
     * File attachments (processed by FileProcessorService)
     * File IDs for RAG context retrieval
     */
    "file_ids"?: string[];

    /**
     * Configuration
     */
    "knowledge_base_id"?: string;
    "tools"?: string[];
    "context"?: { [_: string]: any };
    "temperature"?: number;
    "max_tokens"?: number;
    "stream"?: boolean;

    /** Creates a new ChatRequest instance. */
    constructor($$source: Partial<ChatRequest> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatRequest {
        const $$createField8_0 = $$createType4;
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("file_ids" in $$parsedSource) {
            $$parsedSource["file_ids"] = $$createField8_0($$parsedSource["file_ids"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField10_0($$parsedSource["tools"]);
        }
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField11_0($$parsedSource["context"]);
        }
        return new ChatRequest($$parsedSource as Partial<ChatRequest>);
    }
}

/**
 * ChatToolPayload represents a tool call payload
 */
export class ChatToolPayload {
    "apiName": string;
    "arguments": string;
    "id": string;
    "identifier": string;
    "type": string;

    /** Creates a new ChatToolPayload instance. */
    constructor($$source: Partial<ChatToolPayload> = {}) {
        if (!("apiName" in $$source)) {
            this["apiName"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatToolPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatToolPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatToolPayload($$parsedSource as Partial<ChatToolPayload>);
    }
}

/**
 * CitationItem represents a citation from search results
 */
export class CitationItem {
    "favicon"?: string;
    "id"?: string;
    "title"?: string;
    "url": string;

    /** Creates a new CitationItem instance. */
    constructor($$source: Partial<CitationItem> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CitationItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CitationItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CitationItem($$parsedSource as Partial<CitationItem>);
    }
}

/**
 * ClaimResult represents the result of a claim transaction
 */
export class ClaimResult {
    "tx_hash": string;
    "period_id": number;
    "reward_type": types$0.RewardType;
    "amount": string;

    /**
     * "submitted", "pending", "confirmed", "failed"
     */
    "status": string;

    /** Creates a new ClaimResult instance. */
    constructor($$source: Partial<ClaimResult> = {}) {
        if (!("tx_hash" in $$source)) {
            this["tx_hash"] = "";
        }
        if (!("period_id" in $$source)) {
            this["period_id"] = 0;
        }
        if (!("reward_type" in $$source)) {
            this["reward_type"] = types$0.RewardType.$zero;
        }
        if (!("amount" in $$source)) {
            this["amount"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClaimResult($$parsedSource as Partial<ClaimResult>);
    }
}

/**
 * ClaimableCashbackRecord represents a claimable cashback record for the frontend
 */
export class ClaimableCashbackRecord {
    "period": number;

    /**
     * KAWAI amount (wei)
     */
    "amount": string;

    /**
     * Merkle proof
     */
    "proof": string[];

    /**
     * Merkle root for verification
     */
    "merkle_root": string;

    /**
     * Whether already claimed
     */
    "claimed": boolean;

    /**
     * Original deposit tx (if available)
     */
    "deposit_tx_hash": string;

    /** Creates a new ClaimableCashbackRecord instance. */
    constructor($$source: Partial<ClaimableCashbackRecord> = {}) {
        if (!("period" in $$source)) {
            this["period"] = 0;
        }
        if (!("amount" in $$source)) {
            this["amount"] = "";
        }
        if (!("proof" in $$source)) {
            this["proof"] = [];
        }
        if (!("merkle_root" in $$source)) {
            this["merkle_root"] = "";
        }
        if (!("claimed" in $$source)) {
            this["claimed"] = false;
        }
        if (!("deposit_tx_hash" in $$source)) {
            this["deposit_tx_hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimableCashbackRecord instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimableCashbackRecord {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proof" in $$parsedSource) {
            $$parsedSource["proof"] = $$createField2_0($$parsedSource["proof"]);
        }
        return new ClaimableCashbackRecord($$parsedSource as Partial<ClaimableCashbackRecord>);
    }
}

/**
 * ClaimableReward represents a single claimable reward proof
 */
export class ClaimableReward {
    "index": number;

    /**
     * BigInt as string (raw, no decimals)
     */
    "amount": string;

    /**
     * Merkle proof (hex strings)
     */
    "proof": string[];

    /**
     * Root hash for verification
     */
    "merkle_root": string;

    /**
     * Settlement period identifier
     */
    "period_id": number;

    /**
     * "mining", "cashback", "referral", "stablecoin"
     */
    "reward_type": types$0.RewardType;

    /**
     * "unclaimed", "pending", "confirmed", "failed"
     */
    "claim_status": string;

    /**
     * Transaction hash if claimed
     */
    "claim_tx_hash": string;

    /**
     * When proof was generated
     */
    "created_at": string;

    /**
     * When claimed (if confirmed)
     */
    "claimed_at": string;

    /**
     * Human-readable amount
     */
    "formatted": string;

    /**
     * Token decimals (18 for KAWAI, 6 for USDT)
     */
    "decimals": number;

    /**
     * Mining-specific fields (for 9-field ClaimMiningReward)
     * Contributor's share
     */
    "contributor_amount"?: string;

    /**
     * Developer's share
     */
    "developer_amount"?: string;

    /**
     * User's cashback
     */
    "user_amount"?: string;

    /**
     * Affiliator's commission
     */
    "affiliator_amount"?: string;

    /**
     * Developer address
     */
    "developer_address"?: string;

    /**
     * User address
     */
    "user_address"?: string;

    /**
     * Affiliator address
     */
    "affiliator_address"?: string;

    /** Creates a new ClaimableReward instance. */
    constructor($$source: Partial<ClaimableReward> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("amount" in $$source)) {
            this["amount"] = "";
        }
        if (!("proof" in $$source)) {
            this["proof"] = [];
        }
        if (!("merkle_root" in $$source)) {
            this["merkle_root"] = "";
        }
        if (!("period_id" in $$source)) {
            this["period_id"] = 0;
        }
        if (!("reward_type" in $$source)) {
            this["reward_type"] = types$0.RewardType.$zero;
        }
        if (!("claim_status" in $$source)) {
            this["claim_status"] = "";
        }
        if (!("claim_tx_hash" in $$source)) {
            this["claim_tx_hash"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("claimed_at" in $$source)) {
            this["claimed_at"] = "";
        }
        if (!("formatted" in $$source)) {
            this["formatted"] = "";
        }
        if (!("decimals" in $$source)) {
            this["decimals"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimableReward instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimableReward {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proof" in $$parsedSource) {
            $$parsedSource["proof"] = $$createField2_0($$parsedSource["proof"]);
        }
        return new ClaimableReward($$parsedSource as Partial<ClaimableReward>);
    }
}

/**
 * ClaimableRewardsResponse represents the response from GetClaimableRewards
 */
export class ClaimableRewardsResponse {
    "address": string;
    "unclaimed_proofs": (ClaimableReward | null)[];
    "pending_proofs": (ClaimableReward | null)[];

    /**
     * NEW: For Recent Activity
     */
    "confirmed_proofs": (ClaimableReward | null)[];
    "total_kawai_claimable": string;
    "total_kawai_claimable_formatted": string;
    "total_usdt_claimable": string;
    "total_usdt_claimable_formatted": string;
    "current_kawai_accumulating": string;
    "current_usdt_accumulating": string;

    /** Creates a new ClaimableRewardsResponse instance. */
    constructor($$source: Partial<ClaimableRewardsResponse> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("unclaimed_proofs" in $$source)) {
            this["unclaimed_proofs"] = [];
        }
        if (!("pending_proofs" in $$source)) {
            this["pending_proofs"] = [];
        }
        if (!("confirmed_proofs" in $$source)) {
            this["confirmed_proofs"] = [];
        }
        if (!("total_kawai_claimable" in $$source)) {
            this["total_kawai_claimable"] = "";
        }
        if (!("total_kawai_claimable_formatted" in $$source)) {
            this["total_kawai_claimable_formatted"] = "";
        }
        if (!("total_usdt_claimable" in $$source)) {
            this["total_usdt_claimable"] = "";
        }
        if (!("total_usdt_claimable_formatted" in $$source)) {
            this["total_usdt_claimable_formatted"] = "";
        }
        if (!("current_kawai_accumulating" in $$source)) {
            this["current_kawai_accumulating"] = "";
        }
        if (!("current_usdt_accumulating" in $$source)) {
            this["current_usdt_accumulating"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClaimableRewardsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ClaimableRewardsResponse {
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("unclaimed_proofs" in $$parsedSource) {
            $$parsedSource["unclaimed_proofs"] = $$createField1_0($$parsedSource["unclaimed_proofs"]);
        }
        if ("pending_proofs" in $$parsedSource) {
            $$parsedSource["pending_proofs"] = $$createField2_0($$parsedSource["pending_proofs"]);
        }
        if ("confirmed_proofs" in $$parsedSource) {
            $$parsedSource["confirmed_proofs"] = $$createField3_0($$parsedSource["confirmed_proofs"]);
        }
        return new ClaimableRewardsResponse($$parsedSource as Partial<ClaimableRewardsResponse>);
    }
}

/**
 * ContractAddresses represents all smart contract addresses
 */
export class ContractAddresses {
    /**
     * Token Addresses
     * Stablecoin address: MockStablecoin (testnet) or USDC (mainnet)
     */
    "usdt": string;
    "kawai": string;

    /**
     * Payment & Vault
     */
    "paymentVault": string;

    /**
     * OTC Market
     */
    "otcMarket": string;

    /**
     * Reward Distributors
     */
    "miningDistributor": string;
    "cashbackDistributor": string;
    "referralDistributor": string;

    /**
     * Revenue Sharing
     */
    "usdtDistributor": string;

    /** Creates a new ContractAddresses instance. */
    constructor($$source: Partial<ContractAddresses> = {}) {
        if (!("usdt" in $$source)) {
            this["usdt"] = "";
        }
        if (!("kawai" in $$source)) {
            this["kawai"] = "";
        }
        if (!("paymentVault" in $$source)) {
            this["paymentVault"] = "";
        }
        if (!("otcMarket" in $$source)) {
            this["otcMarket"] = "";
        }
        if (!("miningDistributor" in $$source)) {
            this["miningDistributor"] = "";
        }
        if (!("cashbackDistributor" in $$source)) {
            this["cashbackDistributor"] = "";
        }
        if (!("referralDistributor" in $$source)) {
            this["referralDistributor"] = "";
        }
        if (!("usdtDistributor" in $$source)) {
            this["usdtDistributor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContractAddresses instance from a string or object.
     */
    static createFrom($$source: any = {}): ContractAddresses {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContractAddresses($$parsedSource as Partial<ContractAddresses>);
    }
}

/**
 * ContributorInfo represents contributor information for frontend display
 */
export class ContributorInfo {
    "wallet_address": string;
    "endpoint_url": string;
    "region": string;
    "status": string;
    "last_seen": string;
    "available_models": string[];
    "active_requests": number;
    "total_requests": number;
    "avg_response_time": number;
    "success_rate": number;
    "cpu_cores": number;
    "total_ram": number;
    "available_ram": number;
    "gpu_model": string;
    "gpu_memory": number;
    "score"?: number;

    /** Creates a new ContributorInfo instance. */
    constructor($$source: Partial<ContributorInfo> = {}) {
        if (!("wallet_address" in $$source)) {
            this["wallet_address"] = "";
        }
        if (!("endpoint_url" in $$source)) {
            this["endpoint_url"] = "";
        }
        if (!("region" in $$source)) {
            this["region"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("last_seen" in $$source)) {
            this["last_seen"] = "";
        }
        if (!("available_models" in $$source)) {
            this["available_models"] = [];
        }
        if (!("active_requests" in $$source)) {
            this["active_requests"] = 0;
        }
        if (!("total_requests" in $$source)) {
            this["total_requests"] = 0;
        }
        if (!("avg_response_time" in $$source)) {
            this["avg_response_time"] = 0;
        }
        if (!("success_rate" in $$source)) {
            this["success_rate"] = 0;
        }
        if (!("cpu_cores" in $$source)) {
            this["cpu_cores"] = 0;
        }
        if (!("total_ram" in $$source)) {
            this["total_ram"] = 0;
        }
        if (!("available_ram" in $$source)) {
            this["available_ram"] = 0;
        }
        if (!("gpu_model" in $$source)) {
            this["gpu_model"] = "";
        }
        if (!("gpu_memory" in $$source)) {
            this["gpu_memory"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContributorInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ContributorInfo {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("available_models" in $$parsedSource) {
            $$parsedSource["available_models"] = $$createField5_0($$parsedSource["available_models"]);
        }
        return new ContributorInfo($$parsedSource as Partial<ContributorInfo>);
    }
}

/**
 * CreateThreadRequest represents a request to create a new thread
 */
export class CreateThreadRequest {
    /**
     * Message to branch from
     */
    "source_message_id": string;

    /**
     * Topic this thread belongs to
     */
    "topic_id": string;
    "title"?: string;

    /**
     * continuation or standalone
     */
    "type": ThreadType;
    "parent_thread_id"?: string;

    /** Creates a new CreateThreadRequest instance. */
    constructor($$source: Partial<CreateThreadRequest> = {}) {
        if (!("source_message_id" in $$source)) {
            this["source_message_id"] = "";
        }
        if (!("topic_id" in $$source)) {
            this["topic_id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ThreadType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateThreadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateThreadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateThreadRequest($$parsedSource as Partial<CreateThreadRequest>);
    }
}

/**
 * CreateThreadResponse represents the response from creating a thread
 */
export class CreateThreadResponse {
    "thread_id": string;
    "title": string;
    "type": string;
    "status": string;
    "created_at": number;
    "error"?: string;

    /** Creates a new CreateThreadResponse instance. */
    constructor($$source: Partial<CreateThreadResponse> = {}) {
        if (!("thread_id" in $$source)) {
            this["thread_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateThreadResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateThreadResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateThreadResponse($$parsedSource as Partial<CreateThreadResponse>);
    }
}

/**
 * GasEstimate represents gas estimation for a network
 */
export class GasEstimate {
    "maxGasPriceGwei": number;
    "maxTipGwei": number;
    "isDynamicFee": boolean;

    /** Creates a new GasEstimate instance. */
    constructor($$source: Partial<GasEstimate> = {}) {
        if (!("maxGasPriceGwei" in $$source)) {
            this["maxGasPriceGwei"] = 0;
        }
        if (!("maxTipGwei" in $$source)) {
            this["maxTipGwei"] = 0;
        }
        if (!("isDynamicFee" in $$source)) {
            this["isDynamicFee"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GasEstimate instance from a string or object.
     */
    static createFrom($$source: any = {}): GasEstimate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GasEstimate($$parsedSource as Partial<GasEstimate>);
    }
}

/**
 * GroundingSearch represents search grounding data for messages
 */
export class GroundingSearch {
    "citations"?: CitationItem[];
    "searchQueries"?: string[];

    /** Creates a new GroundingSearch instance. */
    constructor($$source: Partial<GroundingSearch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroundingSearch instance from a string or object.
     */
    static createFrom($$source: any = {}): GroundingSearch {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("citations" in $$parsedSource) {
            $$parsedSource["citations"] = $$createField0_0($$parsedSource["citations"]);
        }
        if ("searchQueries" in $$parsedSource) {
            $$parsedSource["searchQueries"] = $$createField1_0($$parsedSource["searchQueries"]);
        }
        return new GroundingSearch($$parsedSource as Partial<GroundingSearch>);
    }
}

/**
 * ListThreadsRequest represents a request to list threads
 */
export class ListThreadsRequest {
    "topic_id": string;

    /** Creates a new ListThreadsRequest instance. */
    constructor($$source: Partial<ListThreadsRequest> = {}) {
        if (!("topic_id" in $$source)) {
            this["topic_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListThreadsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListThreadsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListThreadsRequest($$parsedSource as Partial<ListThreadsRequest>);
    }
}

/**
 * LogInfo represents a decoded event log
 */
export class LogInfo {
    "name": string;
    "topics": string[];
    "data": ParamInfo[];

    /** Creates a new LogInfo instance. */
    constructor($$source: Partial<LogInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("topics" in $$source)) {
            this["topics"] = [];
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LogInfo {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("topics" in $$parsedSource) {
            $$parsedSource["topics"] = $$createField1_0($$parsedSource["topics"]);
        }
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new LogInfo($$parsedSource as Partial<LogInfo>);
    }
}

/**
 * MarketStats represents current marketplace statistics
 */
export class MarketStats {
    /**
     * Lowest ask price in USDT per token
     */
    "lowestAskPrice": string;

    /**
     * Highest recent trade price
     */
    "highestBidPrice": string;

    /**
     * 24-hour trading volume in USDT
     */
    "volume24h": string;

    /**
     * 24-hour price change percentage
     */
    "priceChange24h": string;

    /**
     * Number of active orders
     */
    "activeOrdersCount": number;

    /**
     * Recent completed trades
     */
    "recentTrades": Trade[];

    /** Creates a new MarketStats instance. */
    constructor($$source: Partial<MarketStats> = {}) {
        if (!("lowestAskPrice" in $$source)) {
            this["lowestAskPrice"] = "";
        }
        if (!("highestBidPrice" in $$source)) {
            this["highestBidPrice"] = "";
        }
        if (!("volume24h" in $$source)) {
            this["volume24h"] = "";
        }
        if (!("priceChange24h" in $$source)) {
            this["priceChange24h"] = "";
        }
        if (!("activeOrdersCount" in $$source)) {
            this["activeOrdersCount"] = 0;
        }
        if (!("recentTrades" in $$source)) {
            this["recentTrades"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarketStats instance from a string or object.
     */
    static createFrom($$source: any = {}): MarketStats {
        const $$createField5_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recentTrades" in $$parsedSource) {
            $$parsedSource["recentTrades"] = $$createField5_0($$parsedSource["recentTrades"]);
        }
        return new MarketStats($$parsedSource as Partial<MarketStats>);
    }
}

/**
 * MemoryIntegration provides integration between memory services and chat
 */
export class MemoryIntegration {

    /** Creates a new MemoryIntegration instance. */
    constructor($$source: Partial<MemoryIntegration> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryIntegration instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryIntegration {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryIntegration($$parsedSource as Partial<MemoryIntegration>);
    }
}

/**
 * ModelPerformance represents performance metrics
 */
export class ModelPerformance {
    "tps"?: number;
    "ttft"?: number;
    "duration"?: number;
    "latency"?: number;

    /** Creates a new ModelPerformance instance. */
    constructor($$source: Partial<ModelPerformance> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPerformance instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelPerformance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPerformance($$parsedSource as Partial<ModelPerformance>);
    }
}

/**
 * ModelReasoning represents reasoning/thinking content
 */
export class ModelReasoning {
    "content"?: string;
    "duration"?: number;
    "signature"?: string;

    /** Creates a new ModelReasoning instance. */
    constructor($$source: Partial<ModelReasoning> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelReasoning instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelReasoning {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelReasoning($$parsedSource as Partial<ModelReasoning>);
    }
}

/**
 * ModelUsage represents token usage metrics
 */
export class ModelUsage {
    "inputCachedTokens"?: number;
    "inputCacheMissTokens"?: number;
    "inputWriteCacheTokens"?: number;
    "inputTextTokens"?: number;
    "inputImageTokens"?: number;
    "inputAudioTokens"?: number;
    "inputCitationTokens"?: number;
    "outputTextTokens"?: number;
    "outputImageTokens"?: number;
    "outputAudioTokens"?: number;
    "outputReasoningTokens"?: number;
    "acceptedPredictionTokens"?: number;
    "rejectedPredictionTokens"?: number;
    "totalInputTokens"?: number;
    "totalOutputTokens"?: number;
    "totalTokens"?: number;
    "cost"?: number;

    /** Creates a new ModelUsage instance. */
    constructor($$source: Partial<ModelUsage> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelUsage($$parsedSource as Partial<ModelUsage>);
    }
}

/**
 * NetworkEnvironment represents a blockchain network
 */
export class NetworkEnvironment {
    "name": string;
    "chainId": number;
    "isTestnet": boolean;

    /** Creates a new NetworkEnvironment instance. */
    constructor($$source: Partial<NetworkEnvironment> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("chainId" in $$source)) {
            this["chainId"] = 0;
        }
        if (!("isTestnet" in $$source)) {
            this["isTestnet"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkEnvironment instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkEnvironment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkEnvironment($$parsedSource as Partial<NetworkEnvironment>);
    }
}

/**
 * NetworkInfo represents a blockchain network for the frontend
 */
export class NetworkInfo {
    "id": number;
    "name": string;
    "nativeTokenSymbol": string;
    "nativeTokenDecimal": number;
    "explorerURL": string;
    "isTestnet": boolean;
    "icon": string;

    /**
     * "MOCK" (testnet) or "USDC" (mainnet)
     */
    "stablecoinSymbol": string;

    /**
     * Full display name
     */
    "stablecoinName": string;

    /**
     * "USDT" (testnet) or "USDC" (mainnet) for messages
     */
    "stablecoinShort": string;

    /** Creates a new NetworkInfo instance. */
    constructor($$source: Partial<NetworkInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nativeTokenSymbol" in $$source)) {
            this["nativeTokenSymbol"] = "";
        }
        if (!("nativeTokenDecimal" in $$source)) {
            this["nativeTokenDecimal"] = 0;
        }
        if (!("explorerURL" in $$source)) {
            this["explorerURL"] = "";
        }
        if (!("isTestnet" in $$source)) {
            this["isTestnet"] = false;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("stablecoinSymbol" in $$source)) {
            this["stablecoinSymbol"] = "";
        }
        if (!("stablecoinName" in $$source)) {
            this["stablecoinName"] = "";
        }
        if (!("stablecoinShort" in $$source)) {
            this["stablecoinShort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInfo($$parsedSource as Partial<NetworkInfo>);
    }
}

/**
 * Order represents a sell order in the marketplace
 */
export class Order {
    "id": string;
    "seller": string;

    /**
     * KAWAI token amount (in wei)
     */
    "tokenAmount": string;

    /**
     * Total USDT price (in wei)
     */
    "usdtPrice": string;

    /**
     * USDT price per KAWAI token
     */
    "pricePerToken": string;

    /**
     * active, filled, cancelled
     */
    "status": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * Transaction hash for order creation
     */
    "txHash": string;

    /**
     * Remaining tokens for partial fills
     */
    "remainingAmount": string;

    /** Creates a new Order instance. */
    constructor($$source: Partial<Order> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("seller" in $$source)) {
            this["seller"] = "";
        }
        if (!("tokenAmount" in $$source)) {
            this["tokenAmount"] = "";
        }
        if (!("usdtPrice" in $$source)) {
            this["usdtPrice"] = "";
        }
        if (!("pricePerToken" in $$source)) {
            this["pricePerToken"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("txHash" in $$source)) {
            this["txHash"] = "";
        }
        if (!("remainingAmount" in $$source)) {
            this["remainingAmount"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Order instance from a string or object.
     */
    static createFrom($$source: any = {}): Order {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Order($$parsedSource as Partial<Order>);
    }
}

/**
 * OrderHistory represents a user's order history with execution details
 * Requirements: 4.1, 4.2 - Order history with status and timestamps
 */
export class OrderHistory {
    "orders": OrderHistoryEntry[];
    "trades": TradeHistoryEntry[];
    "total": number;

    /** Creates a new OrderHistory instance. */
    constructor($$source: Partial<OrderHistory> = {}) {
        if (!("orders" in $$source)) {
            this["orders"] = [];
        }
        if (!("trades" in $$source)) {
            this["trades"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderHistory {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orders" in $$parsedSource) {
            $$parsedSource["orders"] = $$createField0_0($$parsedSource["orders"]);
        }
        if ("trades" in $$parsedSource) {
            $$parsedSource["trades"] = $$createField1_0($$parsedSource["trades"]);
        }
        return new OrderHistory($$parsedSource as Partial<OrderHistory>);
    }
}

/**
 * OrderHistoryEntry represents an order in the user's history
 * Requirements: 4.1, 4.4, 4.5 - Order details with status and timestamps
 */
export class OrderHistoryEntry {
    "id": string;
    "seller": string;

    /**
     * KAWAI token amount (in wei)
     */
    "tokenAmount": string;

    /**
     * Total USDT price (in wei)
     */
    "usdtPrice": string;

    /**
     * USDT price per KAWAI token
     */
    "pricePerToken": string;

    /**
     * active, filled, cancelled
     */
    "status": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * Transaction hash for order creation
     */
    "txHash": string;

    /**
     * Remaining tokens for partial fills
     */
    "remainingAmount": string;
    "statusHistory": OrderStatusChange[];

    /**
     * Number of trades for this order
     */
    "tradeCount": number;

    /**
     * Total amount filled across all trades
     */
    "filledAmount": string;

    /** Creates a new OrderHistoryEntry instance. */
    constructor($$source: Partial<OrderHistoryEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("seller" in $$source)) {
            this["seller"] = "";
        }
        if (!("tokenAmount" in $$source)) {
            this["tokenAmount"] = "";
        }
        if (!("usdtPrice" in $$source)) {
            this["usdtPrice"] = "";
        }
        if (!("pricePerToken" in $$source)) {
            this["pricePerToken"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("txHash" in $$source)) {
            this["txHash"] = "";
        }
        if (!("remainingAmount" in $$source)) {
            this["remainingAmount"] = "";
        }
        if (!("statusHistory" in $$source)) {
            this["statusHistory"] = [];
        }
        if (!("tradeCount" in $$source)) {
            this["tradeCount"] = 0;
        }
        if (!("filledAmount" in $$source)) {
            this["filledAmount"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderHistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderHistoryEntry {
        const $$createField10_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("statusHistory" in $$parsedSource) {
            $$parsedSource["statusHistory"] = $$createField10_0($$parsedSource["statusHistory"]);
        }
        return new OrderHistoryEntry($$parsedSource as Partial<OrderHistoryEntry>);
    }
}

/**
 * OrderResult represents the result of order creation
 */
export class OrderResult {
    "success": boolean;
    "orderID"?: string;
    "txHash"?: string;
    "error"?: string;

    /** Creates a new OrderResult instance. */
    constructor($$source: Partial<OrderResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrderResult($$parsedSource as Partial<OrderResult>);
    }
}

/**
 * OrderStatusChange represents a status change event for an order
 * Requirements: 4.5 - Order status tracking with timestamps
 */
export class OrderStatusChange {
    "status": string;
    "timestamp": time$0.Time;

    /**
     * Transaction hash if status change was on-chain
     */
    "txHash"?: string;

    /** Creates a new OrderStatusChange instance. */
    constructor($$source: Partial<OrderStatusChange> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderStatusChange instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderStatusChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrderStatusChange($$parsedSource as Partial<OrderStatusChange>);
    }
}

/**
 * OrderSummary represents a summary of an order for trade history
 */
export class OrderSummary {
    "id": string;
    "tokenAmount": string;
    "usdtPrice": string;
    "pricePerToken": string;

    /** Creates a new OrderSummary instance. */
    constructor($$source: Partial<OrderSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tokenAmount" in $$source)) {
            this["tokenAmount"] = "";
        }
        if (!("usdtPrice" in $$source)) {
            this["usdtPrice"] = "";
        }
        if (!("pricePerToken" in $$source)) {
            this["pricePerToken"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrderSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): OrderSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OrderSummary($$parsedSource as Partial<OrderSummary>);
    }
}

/**
 * ParamInfo represents a decoded parameter
 */
export class ParamInfo {
    "name": string;
    "type": string;
    "value": string;

    /** Creates a new ParamInfo instance. */
    constructor($$source: Partial<ParamInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParamInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ParamInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParamInfo($$parsedSource as Partial<ParamInfo>);
    }
}

/**
 * ProjectToken represents a project-specific token
 */
export class ProjectToken {
    "address": string;
    "name": string;
    "symbol": string;

    /** Creates a new ProjectToken instance. */
    constructor($$source: Partial<ProjectToken> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("symbol" in $$source)) {
            this["symbol"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectToken instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectToken {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectToken($$parsedSource as Partial<ProjectToken>);
    }
}

/**
 * ReferralStats represents referral statistics
 */
export class ReferralStats {
    "code": string;
    "total_referrals": number;
    "total_earnings_usdt": number;
    "total_earnings_kawai": string;

    /** Creates a new ReferralStats instance. */
    constructor($$source: Partial<ReferralStats> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("total_referrals" in $$source)) {
            this["total_referrals"] = 0;
        }
        if (!("total_earnings_usdt" in $$source)) {
            this["total_earnings_usdt"] = 0;
        }
        if (!("total_earnings_kawai" in $$source)) {
            this["total_earnings_kawai"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReferralStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ReferralStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReferralStats($$parsedSource as Partial<ReferralStats>);
    }
}

/**
 * RevenueShareStatsResponse represents revenue sharing statistics
 */
export class RevenueShareStatsResponse {
    /**
     * Raw balance (18 decimals)
     */
    "kawai_balance": string;

    /**
     * Human-readable balance
     */
    "kawai_balance_formatted": string;

    /**
     * Total KAWAI supply
     */
    "total_supply": string;

    /**
     * User's share percentage
     */
    "share_percentage": string;

    /** Creates a new RevenueShareStatsResponse instance. */
    constructor($$source: Partial<RevenueShareStatsResponse> = {}) {
        if (!("kawai_balance" in $$source)) {
            this["kawai_balance"] = "";
        }
        if (!("kawai_balance_formatted" in $$source)) {
            this["kawai_balance_formatted"] = "";
        }
        if (!("total_supply" in $$source)) {
            this["total_supply"] = "";
        }
        if (!("share_percentage" in $$source)) {
            this["share_percentage"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RevenueShareStatsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): RevenueShareStatsResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RevenueShareStatsResponse($$parsedSource as Partial<RevenueShareStatsResponse>);
    }
}

/**
 * SearchResult represents a search result from vector database
 */
export class SearchResult {
    "id": string;
    "similarity": number;
    "text": string;
    "fileId": string;
    "fileName": string;
    "type": string;
    "index": number;
    "metadata": { [_: string]: string };

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("similarity" in $$source)) {
            this["similarity"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField7_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * StreamEventPayload represents the payload for chat stream events.
 * This is emitted via Wails events ('chat:stream') and consumed by frontend.
 * Frontend can import this type from generated bindings.
 */
export class StreamEventPayload {
    "type": types$1.ChatStreamEvent;
    "session_id": string;
    "message_id": string;
    "topic_id"?: string;

    /**
     * Content fields
     */
    "content"?: string;

    /**
     * Legacy support
     */
    "full_content"?: string;

    /**
     * Reasoning
     */
    "reasoning"?: ModelReasoning | null;

    /**
     * Tools
     * For single tool call event (legacy/alternative)
     */
    "tool"?: ChatToolPayload | null;

    /**
     * For tool_call event
     */
    "tools"?: ChatToolPayload[];

    /**
     * Tool Result
     */
    "tool_call_id"?: string;
    "tool_msg_id"?: string;
    "plugin"?: ChatPluginPayload | null;
    "pluginState"?: any;

    /**
     * Complete event fields
     */
    "search"?: GroundingSearch | null;
    "chunksList"?: ChatFileChunk[];
    "imageList"?: ChatImageItem[];
    "usage"?: ModelUsage | null;
    "error"?: ChatMessageError | null;
    "performance"?: ModelPerformance | null;

    /** Creates a new StreamEventPayload instance. */
    constructor($$source: Partial<StreamEventPayload> = {}) {
        if (!("type" in $$source)) {
            this["type"] = types$1.ChatStreamEvent.$zero;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("message_id" in $$source)) {
            this["message_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEventPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamEventPayload {
        const $$createField6_0 = $$createType23;
        const $$createField7_0 = $$createType25;
        const $$createField8_0 = $$createType26;
        const $$createField11_0 = $$createType28;
        const $$createField13_0 = $$createType30;
        const $$createField14_0 = $$createType32;
        const $$createField15_0 = $$createType34;
        const $$createField16_0 = $$createType36;
        const $$createField17_0 = $$createType38;
        const $$createField18_0 = $$createType40;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasoning" in $$parsedSource) {
            $$parsedSource["reasoning"] = $$createField6_0($$parsedSource["reasoning"]);
        }
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField7_0($$parsedSource["tool"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField8_0($$parsedSource["tools"]);
        }
        if ("plugin" in $$parsedSource) {
            $$parsedSource["plugin"] = $$createField11_0($$parsedSource["plugin"]);
        }
        if ("search" in $$parsedSource) {
            $$parsedSource["search"] = $$createField13_0($$parsedSource["search"]);
        }
        if ("chunksList" in $$parsedSource) {
            $$parsedSource["chunksList"] = $$createField14_0($$parsedSource["chunksList"]);
        }
        if ("imageList" in $$parsedSource) {
            $$parsedSource["imageList"] = $$createField15_0($$parsedSource["imageList"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField16_0($$parsedSource["usage"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField17_0($$parsedSource["error"]);
        }
        if ("performance" in $$parsedSource) {
            $$parsedSource["performance"] = $$createField18_0($$parsedSource["performance"]);
        }
        return new StreamEventPayload($$parsedSource as Partial<StreamEventPayload>);
    }
}

/**
 * SyncDepositRequest represents a sync request from user client
 */
export class SyncDepositRequest {
    "txHash": string;
    "userAddress": string;

    /** Creates a new SyncDepositRequest instance. */
    constructor($$source: Partial<SyncDepositRequest> = {}) {
        if (!("txHash" in $$source)) {
            this["txHash"] = "";
        }
        if (!("userAddress" in $$source)) {
            this["userAddress"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncDepositRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncDepositRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncDepositRequest($$parsedSource as Partial<SyncDepositRequest>);
    }
}

/**
 * SyncDepositResponse represents the sync response
 */
export class SyncDepositResponse {
    "success": boolean;
    "message": string;
    "amount"?: string;
    "newBalance"?: string;
    "blockNumber"?: number;
    "alreadySync"?: boolean;

    /** Creates a new SyncDepositResponse instance. */
    constructor($$source: Partial<SyncDepositResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncDepositResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncDepositResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncDepositResponse($$parsedSource as Partial<SyncDepositResponse>);
    }
}

/**
 * ThreadInfo represents thread information
 */
export class ThreadInfo {
    "id": string;
    "title": string;
    "type": string;
    "status": string;
    "topic_id": string;
    "source_message_id": string;
    "parent_thread_id"?: string;
    "last_active_at": number;
    "created_at": number;
    "updated_at": number;

    /** Creates a new ThreadInfo instance. */
    constructor($$source: Partial<ThreadInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("topic_id" in $$source)) {
            this["topic_id"] = "";
        }
        if (!("source_message_id" in $$source)) {
            this["source_message_id"] = "";
        }
        if (!("last_active_at" in $$source)) {
            this["last_active_at"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadInfo($$parsedSource as Partial<ThreadInfo>);
    }
}

/**
 * ThreadStatus represents the status of a thread
 */
export enum ThreadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThreadStatusActive = "active",
    ThreadStatusDeprecated = "deprecated",
    ThreadStatusArchived = "archived",
};

/**
 * ThreadType represents the type of thread
 */
export enum ThreadType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Continue from a message
     */
    ThreadTypeContinuation = "continuation",

    /**
     * Standalone thread
     */
    ThreadTypeStandalone = "standalone",
};

/**
 * TokenInfo represents ERC20 token information
 */
export class TokenInfo {
    "address": string;
    "name": string;
    "symbol": string;
    "decimals": number;
    "isKnown": boolean;

    /** Creates a new TokenInfo instance. */
    constructor($$source: Partial<TokenInfo> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("symbol" in $$source)) {
            this["symbol"] = "";
        }
        if (!("decimals" in $$source)) {
            this["decimals"] = 0;
        }
        if (!("isKnown" in $$source)) {
            this["isKnown"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TokenInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenInfo($$parsedSource as Partial<TokenInfo>);
    }
}

/**
 * Trade represents a completed trade transaction
 */
export class Trade {
    "id": string;
    "orderID": string;
    "buyer": string;
    "seller": string;
    "tokenAmount": string;
    "usdtAmount": string;

    /**
     * Price per token
     */
    "price": string;
    "timestamp": time$0.Time;
    "txHash": string;

    /** Creates a new Trade instance. */
    constructor($$source: Partial<Trade> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("orderID" in $$source)) {
            this["orderID"] = "";
        }
        if (!("buyer" in $$source)) {
            this["buyer"] = "";
        }
        if (!("seller" in $$source)) {
            this["seller"] = "";
        }
        if (!("tokenAmount" in $$source)) {
            this["tokenAmount"] = "";
        }
        if (!("usdtAmount" in $$source)) {
            this["usdtAmount"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("txHash" in $$source)) {
            this["txHash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Trade instance from a string or object.
     */
    static createFrom($$source: any = {}): Trade {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Trade($$parsedSource as Partial<Trade>);
    }
}

/**
 * TradeHistoryEntry represents a trade in the user's history
 * Requirements: 4.2 - Trade history with execution details
 */
export class TradeHistoryEntry {
    "id": string;
    "orderID": string;
    "buyer": string;
    "seller": string;
    "tokenAmount": string;
    "usdtAmount": string;

    /**
     * Price per token
     */
    "price": string;
    "timestamp": time$0.Time;
    "txHash": string;

    /**
     * Summary of the original order
     */
    "orderDetails": OrderSummary;

    /** Creates a new TradeHistoryEntry instance. */
    constructor($$source: Partial<TradeHistoryEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("orderID" in $$source)) {
            this["orderID"] = "";
        }
        if (!("buyer" in $$source)) {
            this["buyer"] = "";
        }
        if (!("seller" in $$source)) {
            this["seller"] = "";
        }
        if (!("tokenAmount" in $$source)) {
            this["tokenAmount"] = "";
        }
        if (!("usdtAmount" in $$source)) {
            this["usdtAmount"] = "";
        }
        if (!("price" in $$source)) {
            this["price"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("txHash" in $$source)) {
            this["txHash"] = "";
        }
        if (!("orderDetails" in $$source)) {
            this["orderDetails"] = (new OrderSummary());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TradeHistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): TradeHistoryEntry {
        const $$createField9_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("orderDetails" in $$parsedSource) {
            $$parsedSource["orderDetails"] = $$createField9_0($$parsedSource["orderDetails"]);
        }
        return new TradeHistoryEntry($$parsedSource as Partial<TradeHistoryEntry>);
    }
}

/**
 * TradeResult represents the result of a trade execution
 */
export class TradeResult {
    "success": boolean;
    "txHash": string;
    "orderID": string;

    /**
     * Amount of KAWAI tokens traded
     */
    "tokenAmount": string;

    /**
     * Amount of USDT paid
     */
    "usdtAmount": string;

    /**
     * Buyer's wallet address
     */
    "buyer": string;

    /**
     * Seller's wallet address
     */
    "seller": string;
    "error"?: string;

    /** Creates a new TradeResult instance. */
    constructor($$source: Partial<TradeResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("txHash" in $$source)) {
            this["txHash"] = "";
        }
        if (!("orderID" in $$source)) {
            this["orderID"] = "";
        }
        if (!("tokenAmount" in $$source)) {
            this["tokenAmount"] = "";
        }
        if (!("usdtAmount" in $$source)) {
            this["usdtAmount"] = "";
        }
        if (!("buyer" in $$source)) {
            this["buyer"] = "";
        }
        if (!("seller" in $$source)) {
            this["seller"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TradeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TradeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TradeResult($$parsedSource as Partial<TradeResult>);
    }
}

/**
 * TrialClaim represents the result of claiming trial
 */
export class TrialClaim {
    "balance_added_usdt": number;
    "balance_added_kawai": string;
    "has_referral": boolean;
    "referral_bonus_usdt"?: number;
    "referral_bonus_kawai"?: string;

    /** Creates a new TrialClaim instance. */
    constructor($$source: Partial<TrialClaim> = {}) {
        if (!("balance_added_usdt" in $$source)) {
            this["balance_added_usdt"] = 0;
        }
        if (!("balance_added_kawai" in $$source)) {
            this["balance_added_kawai"] = "";
        }
        if (!("has_referral" in $$source)) {
            this["has_referral"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrialClaim instance from a string or object.
     */
    static createFrom($$source: any = {}): TrialClaim {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrialClaim($$parsedSource as Partial<TrialClaim>);
    }
}

/**
 * TxAnalysis represents a decoded transaction
 */
export class TxAnalysis {
    "hash": string;
    "status": string;
    "from": string;
    "to": string;
    "value": string;
    "gasUsed": string;
    "gasCost": string;
    "method": string;
    "txType": string;
    "params": ParamInfo[];
    "logs": LogInfo[];
    "blockNumber": number;
    "error"?: string;

    /** Creates a new TxAnalysis instance. */
    constructor($$source: Partial<TxAnalysis> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("gasUsed" in $$source)) {
            this["gasUsed"] = "";
        }
        if (!("gasCost" in $$source)) {
            this["gasCost"] = "";
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("txType" in $$source)) {
            this["txType"] = "";
        }
        if (!("params" in $$source)) {
            this["params"] = [];
        }
        if (!("logs" in $$source)) {
            this["logs"] = [];
        }
        if (!("blockNumber" in $$source)) {
            this["blockNumber"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TxAnalysis instance from a string or object.
     */
    static createFrom($$source: any = {}): TxAnalysis {
        const $$createField9_0 = $$createType12;
        const $$createField10_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField9_0($$parsedSource["params"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField10_0($$parsedSource["logs"]);
        }
        return new TxAnalysis($$parsedSource as Partial<TxAnalysis>);
    }
}

/**
 * UserBalanceInfo represents user balance data formatted for UI display
 */
export class UserBalanceInfo {
    "address": string;

    /**
     * Formatted (e.g., "5.00")
     */
    "usdt_balance": string;

    /**
     * Raw micro USDT value
     */
    "usdt_micro": string;

    /**
     * In wei
     */
    "kawai_balance": string;
    "trial_claimed": boolean;

    /**
     * Empty if no referrer
     */
    "referrer_address": string;
    "has_referrer": boolean;

    /** Creates a new UserBalanceInfo instance. */
    constructor($$source: Partial<UserBalanceInfo> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("usdt_balance" in $$source)) {
            this["usdt_balance"] = "";
        }
        if (!("usdt_micro" in $$source)) {
            this["usdt_micro"] = "";
        }
        if (!("kawai_balance" in $$source)) {
            this["kawai_balance"] = "";
        }
        if (!("trial_claimed" in $$source)) {
            this["trial_claimed"] = false;
        }
        if (!("referrer_address" in $$source)) {
            this["referrer_address"] = "";
        }
        if (!("has_referrer" in $$source)) {
            this["has_referrer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserBalanceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UserBalanceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserBalanceInfo($$parsedSource as Partial<UserBalanceInfo>);
    }
}

/**
 * WalletInfo represents a wallet in the list
 */
export class WalletInfo {
    "address": string;
    "description": string;
    "isActive": boolean;

    /** Creates a new WalletInfo instance. */
    constructor($$source: Partial<WalletInfo> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("isActive" in $$source)) {
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WalletInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WalletInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WalletInfo($$parsedSource as Partial<WalletInfo>);
    }
}

/**
 * WalletStatus represents the current state of the wallet
 */
export class WalletStatus {
    "hasWallet": boolean;
    "isLocked": boolean;
    "address": string;
    "wallets": WalletInfo[];

    /** Creates a new WalletStatus instance. */
    constructor($$source: Partial<WalletStatus> = {}) {
        if (!("hasWallet" in $$source)) {
            this["hasWallet"] = false;
        }
        if (!("isLocked" in $$source)) {
            this["isLocked"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("wallets" in $$source)) {
            this["wallets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WalletStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): WalletStatus {
        const $$createField3_0 = $$createType45;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wallets" in $$parsedSource) {
            $$parsedSource["wallets"] = $$createField3_0($$parsedSource["wallets"]);
        }
        return new WalletStatus($$parsedSource as Partial<WalletStatus>);
    }
}

// Private type creation functions
const $$createType0 = NetworkEnvironment.createFrom;
const $$createType1 = ContractAddresses.createFrom;
const $$createType2 = ChatCompletionMessage.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = ClaimableReward.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = CitationItem.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ParamInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Trade.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = OrderHistoryEntry.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = TradeHistoryEntry.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = OrderStatusChange.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Map($Create.Any, $Create.Any);
const $$createType22 = ModelReasoning.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = ChatToolPayload.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $Create.Array($$createType24);
const $$createType27 = ChatPluginPayload.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = GroundingSearch.createFrom;
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = ChatFileChunk.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = ChatImageItem.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = ModelUsage.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = ChatMessageError.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
const $$createType39 = ModelPerformance.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = OrderSummary.createFrom;
const $$createType42 = LogInfo.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = WalletInfo.createFrom;
const $$createType45 = $Create.Array($$createType44);
