// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../types/models.js";

/**
 * ChatFileChunk represents a file chunk from RAG system
 */
export class ChatFileChunk {
    "fileId": string;
    "fileType": string;
    "fileUrl": string;
    "filename": string;
    "id": string;
    "similarity"?: number;
    "text": string;

    /** Creates a new ChatFileChunk instance. */
    constructor($$source: Partial<ChatFileChunk> = {}) {
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("fileType" in $$source)) {
            this["fileType"] = "";
        }
        if (!("fileUrl" in $$source)) {
            this["fileUrl"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatFileChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatFileChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatFileChunk($$parsedSource as Partial<ChatFileChunk>);
    }
}

/**
 * ChatImageItem represents an image attachment
 */
export class ChatImageItem {
    "alt"?: string;
    "id": string;
    "url": string;

    /** Creates a new ChatImageItem instance. */
    constructor($$source: Partial<ChatImageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatImageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatImageItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatImageItem($$parsedSource as Partial<ChatImageItem>);
    }
}

/**
 * ChatMessageError represents an error in a message
 */
export class ChatMessageError {
    "body"?: any;
    "message": string;
    "type": string;

    /** Creates a new ChatMessageError instance. */
    constructor($$source: Partial<ChatMessageError> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageError instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessageError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessageError($$parsedSource as Partial<ChatMessageError>);
    }
}

/**
 * ChatPluginPayload represents a plugin call payload
 */
export class ChatPluginPayload {
    "apiName": string;
    "arguments": string;
    "identifier": string;
    "type": string;

    /** Creates a new ChatPluginPayload instance. */
    constructor($$source: Partial<ChatPluginPayload> = {}) {
        if (!("apiName" in $$source)) {
            this["apiName"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = "";
        }
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatPluginPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatPluginPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatPluginPayload($$parsedSource as Partial<ChatPluginPayload>);
    }
}

/**
 * ChatRequest represents a chat request with agent capabilities
 */
export class ChatRequest {
    /**
     * Identity
     */
    "session_id": string;
    "user_id": string;

    /**
     * Message content
     */
    "message": string;

    /**
     * Message IDs (pre-generated by frontend for optimistic UI)
     * Pre-generated user message ID
     */
    "message_user_id"?: string;

    /**
     * Pre-generated assistant message ID
     */
    "message_assistant_id"?: string;

    /**
     * Context (Phase 4: Topic & Thread support)
     * Current topic (may be auto-created)
     */
    "topic_id"?: string;

    /**
     * Current thread (for branching)
     */
    "thread_id"?: string;

    /**
     * Parent message (for threading)
     */
    "parent_id"?: string;

    /**
     * File attachments (processed by FileProcessorService)
     * File IDs for RAG context retrieval
     */
    "file_ids"?: string[];

    /**
     * Configuration
     */
    "knowledge_base_id"?: string;
    "tools"?: string[];
    "context"?: { [_: string]: any };
    "temperature"?: number;
    "max_tokens"?: number;
    "stream"?: boolean;

    /** Creates a new ChatRequest instance. */
    constructor($$source: Partial<ChatRequest> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("user_id" in $$source)) {
            this["user_id"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatRequest {
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("file_ids" in $$parsedSource) {
            $$parsedSource["file_ids"] = $$createField8_0($$parsedSource["file_ids"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField10_0($$parsedSource["tools"]);
        }
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField11_0($$parsedSource["context"]);
        }
        return new ChatRequest($$parsedSource as Partial<ChatRequest>);
    }
}

/**
 * ChatToolPayload represents a tool call payload
 */
export class ChatToolPayload {
    "apiName": string;
    "arguments": string;
    "id": string;
    "identifier": string;
    "type": string;

    /** Creates a new ChatToolPayload instance. */
    constructor($$source: Partial<ChatToolPayload> = {}) {
        if (!("apiName" in $$source)) {
            this["apiName"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("identifier" in $$source)) {
            this["identifier"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatToolPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatToolPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatToolPayload($$parsedSource as Partial<ChatToolPayload>);
    }
}

/**
 * CitationItem represents a citation from search results
 */
export class CitationItem {
    "favicon"?: string;
    "id"?: string;
    "title"?: string;
    "url": string;

    /** Creates a new CitationItem instance. */
    constructor($$source: Partial<CitationItem> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CitationItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CitationItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CitationItem($$parsedSource as Partial<CitationItem>);
    }
}

/**
 * CreateThreadRequest represents a request to create a new thread
 */
export class CreateThreadRequest {
    /**
     * Message to branch from
     */
    "source_message_id": string;

    /**
     * Topic this thread belongs to
     */
    "topic_id": string;
    "title"?: string;

    /**
     * continuation or standalone
     */
    "type": ThreadType;
    "parent_thread_id"?: string;

    /** Creates a new CreateThreadRequest instance. */
    constructor($$source: Partial<CreateThreadRequest> = {}) {
        if (!("source_message_id" in $$source)) {
            this["source_message_id"] = "";
        }
        if (!("topic_id" in $$source)) {
            this["topic_id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ThreadType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateThreadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateThreadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateThreadRequest($$parsedSource as Partial<CreateThreadRequest>);
    }
}

/**
 * CreateThreadResponse represents the response from creating a thread
 */
export class CreateThreadResponse {
    "thread_id": string;
    "title": string;
    "type": string;
    "status": string;
    "created_at": number;
    "error"?: string;

    /** Creates a new CreateThreadResponse instance. */
    constructor($$source: Partial<CreateThreadResponse> = {}) {
        if (!("thread_id" in $$source)) {
            this["thread_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateThreadResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateThreadResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateThreadResponse($$parsedSource as Partial<CreateThreadResponse>);
    }
}

/**
 * GroundingSearch represents search grounding data for messages
 */
export class GroundingSearch {
    "citations"?: CitationItem[];
    "searchQueries"?: string[];

    /** Creates a new GroundingSearch instance. */
    constructor($$source: Partial<GroundingSearch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroundingSearch instance from a string or object.
     */
    static createFrom($$source: any = {}): GroundingSearch {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("citations" in $$parsedSource) {
            $$parsedSource["citations"] = $$createField0_0($$parsedSource["citations"]);
        }
        if ("searchQueries" in $$parsedSource) {
            $$parsedSource["searchQueries"] = $$createField1_0($$parsedSource["searchQueries"]);
        }
        return new GroundingSearch($$parsedSource as Partial<GroundingSearch>);
    }
}

/**
 * ListThreadsRequest represents a request to list threads
 */
export class ListThreadsRequest {
    "topic_id": string;

    /** Creates a new ListThreadsRequest instance. */
    constructor($$source: Partial<ListThreadsRequest> = {}) {
        if (!("topic_id" in $$source)) {
            this["topic_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListThreadsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ListThreadsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListThreadsRequest($$parsedSource as Partial<ListThreadsRequest>);
    }
}

/**
 * MemoryIntegration provides integration between memory services and chat
 */
export class MemoryIntegration {

    /** Creates a new MemoryIntegration instance. */
    constructor($$source: Partial<MemoryIntegration> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryIntegration instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryIntegration {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryIntegration($$parsedSource as Partial<MemoryIntegration>);
    }
}

/**
 * ModelPerformance represents performance metrics
 */
export class ModelPerformance {
    "tps"?: number;
    "ttft"?: number;
    "duration"?: number;
    "latency"?: number;

    /** Creates a new ModelPerformance instance. */
    constructor($$source: Partial<ModelPerformance> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelPerformance instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelPerformance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelPerformance($$parsedSource as Partial<ModelPerformance>);
    }
}

/**
 * ModelReasoning represents reasoning/thinking content
 */
export class ModelReasoning {
    "content"?: string;
    "duration"?: number;
    "signature"?: string;

    /** Creates a new ModelReasoning instance. */
    constructor($$source: Partial<ModelReasoning> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelReasoning instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelReasoning {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelReasoning($$parsedSource as Partial<ModelReasoning>);
    }
}

/**
 * ModelUsage represents token usage metrics
 */
export class ModelUsage {
    "inputCachedTokens"?: number;
    "inputCacheMissTokens"?: number;
    "inputWriteCacheTokens"?: number;
    "inputTextTokens"?: number;
    "inputImageTokens"?: number;
    "inputAudioTokens"?: number;
    "inputCitationTokens"?: number;
    "outputTextTokens"?: number;
    "outputImageTokens"?: number;
    "outputAudioTokens"?: number;
    "outputReasoningTokens"?: number;
    "acceptedPredictionTokens"?: number;
    "rejectedPredictionTokens"?: number;
    "totalInputTokens"?: number;
    "totalOutputTokens"?: number;
    "totalTokens"?: number;
    "cost"?: number;

    /** Creates a new ModelUsage instance. */
    constructor($$source: Partial<ModelUsage> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelUsage($$parsedSource as Partial<ModelUsage>);
    }
}

/**
 * SearchResult represents a search result from vector database
 */
export class SearchResult {
    "id": string;
    "similarity": number;
    "text": string;
    "fileId": string;
    "fileName": string;
    "type": string;
    "index": number;
    "metadata": { [_: string]: string };

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("similarity" in $$source)) {
            this["similarity"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("fileId" in $$source)) {
            this["fileId"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        const $$createField7_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * StreamEventPayload represents the payload for chat stream events.
 * This is emitted via Wails events ('chat:stream') and consumed by frontend.
 * Frontend can import this type from generated bindings.
 */
export class StreamEventPayload {
    "type": types$0.ChatStreamEvent;
    "session_id": string;
    "message_id": string;
    "topic_id"?: string;

    /**
     * Content fields
     */
    "content"?: string;

    /**
     * Legacy support
     */
    "full_content"?: string;

    /**
     * Reasoning
     */
    "reasoning"?: ModelReasoning | null;

    /**
     * Tools
     * For single tool call event (legacy/alternative)
     */
    "tool"?: ChatToolPayload | null;

    /**
     * For tool_call event
     */
    "tools"?: ChatToolPayload[];

    /**
     * Tool Result
     */
    "tool_call_id"?: string;
    "tool_msg_id"?: string;
    "plugin"?: ChatPluginPayload | null;
    "pluginState"?: any;

    /**
     * Complete event fields
     */
    "search"?: GroundingSearch | null;
    "chunksList"?: ChatFileChunk[];
    "imageList"?: ChatImageItem[];
    "usage"?: ModelUsage | null;
    "error"?: ChatMessageError | null;
    "performance"?: ModelPerformance | null;

    /** Creates a new StreamEventPayload instance. */
    constructor($$source: Partial<StreamEventPayload> = {}) {
        if (!("type" in $$source)) {
            this["type"] = types$0.ChatStreamEvent.$zero;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }
        if (!("message_id" in $$source)) {
            this["message_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamEventPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamEventPayload {
        const $$createField6_0 = $$createType6;
        const $$createField7_0 = $$createType8;
        const $$createField8_0 = $$createType9;
        const $$createField11_0 = $$createType11;
        const $$createField13_0 = $$createType13;
        const $$createField14_0 = $$createType15;
        const $$createField15_0 = $$createType17;
        const $$createField16_0 = $$createType19;
        const $$createField17_0 = $$createType21;
        const $$createField18_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasoning" in $$parsedSource) {
            $$parsedSource["reasoning"] = $$createField6_0($$parsedSource["reasoning"]);
        }
        if ("tool" in $$parsedSource) {
            $$parsedSource["tool"] = $$createField7_0($$parsedSource["tool"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField8_0($$parsedSource["tools"]);
        }
        if ("plugin" in $$parsedSource) {
            $$parsedSource["plugin"] = $$createField11_0($$parsedSource["plugin"]);
        }
        if ("search" in $$parsedSource) {
            $$parsedSource["search"] = $$createField13_0($$parsedSource["search"]);
        }
        if ("chunksList" in $$parsedSource) {
            $$parsedSource["chunksList"] = $$createField14_0($$parsedSource["chunksList"]);
        }
        if ("imageList" in $$parsedSource) {
            $$parsedSource["imageList"] = $$createField15_0($$parsedSource["imageList"]);
        }
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField16_0($$parsedSource["usage"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField17_0($$parsedSource["error"]);
        }
        if ("performance" in $$parsedSource) {
            $$parsedSource["performance"] = $$createField18_0($$parsedSource["performance"]);
        }
        return new StreamEventPayload($$parsedSource as Partial<StreamEventPayload>);
    }
}

/**
 * ThreadInfo represents thread information
 */
export class ThreadInfo {
    "id": string;
    "title": string;
    "type": string;
    "status": string;
    "topic_id": string;
    "source_message_id": string;
    "parent_thread_id"?: string;
    "last_active_at": number;
    "created_at": number;
    "updated_at": number;

    /** Creates a new ThreadInfo instance. */
    constructor($$source: Partial<ThreadInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("topic_id" in $$source)) {
            this["topic_id"] = "";
        }
        if (!("source_message_id" in $$source)) {
            this["source_message_id"] = "";
        }
        if (!("last_active_at" in $$source)) {
            this["last_active_at"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreadInfo($$parsedSource as Partial<ThreadInfo>);
    }
}

/**
 * ThreadStatus represents the status of a thread
 */
export enum ThreadStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThreadStatusActive = "active",
    ThreadStatusDeprecated = "deprecated",
    ThreadStatusArchived = "archived",
};

/**
 * ThreadType represents the type of thread
 */
export enum ThreadType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Continue from a message
     */
    ThreadTypeContinuation = "continuation",

    /**
     * Standalone thread
     */
    ThreadTypeStandalone = "standalone",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = CitationItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = ModelReasoning.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = ChatToolPayload.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType7);
const $$createType10 = ChatPluginPayload.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = GroundingSearch.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = ChatFileChunk.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ChatImageItem.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = ModelUsage.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = ChatMessageError.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = ModelPerformance.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
