// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReferralService provides referral system functionality for the Wails desktop app
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClaimFreeTrialWithReferral claims free trial with optional referral code
 * This is a Wails-exposed method for the frontend
 */
export function ClaimFreeTrialWithReferral(address: string, machineID: string, referralCode: string): $CancellablePromise<$models.TrialClaim | null> {
    return $Call.ByID(1937664462, address, machineID, referralCode).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateReferralCode creates a new referral code for the user
 * This is a Wails-exposed method for the frontend
 */
export function CreateReferralCode(userAddress: string): $CancellablePromise<string> {
    return $Call.ByID(3623966757, userAddress);
}

/**
 * GetReferralBonusAmounts returns the bonus amounts for referral system
 * This is a helper method for the frontend to display bonus information
 */
export function GetReferralBonusAmounts(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(1692318686).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetReferralStats retrieves referral statistics for the user
 * This is a Wails-exposed method for the frontend
 */
export function GetReferralStats(userAddress: string): $CancellablePromise<$models.ReferralStats | null> {
    return $Call.ByID(4034229409, userAddress).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TrialClaim.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.ReferralStats.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
