// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThreadManagementService handles thread creation and management for conversation branching
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "../database/generated/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateThread creates a new thread for conversation branching
 */
export function CreateThread(req: $models.CreateThreadRequest): $CancellablePromise<$models.CreateThreadResponse | null> {
    return $Call.ByID(953650907, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteThread deletes a thread
 */
export function DeleteThread(threadID: string, userID: string): $CancellablePromise<void> {
    return $Call.ByID(1748637968, threadID, userID);
}

/**
 * GetThread retrieves a single thread by ID
 */
export function GetThread(threadID: string, userID: string): $CancellablePromise<$models.ThreadInfo | null> {
    return $Call.ByID(1665891689, threadID, userID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetThreadMessages retrieves all messages in a thread
 * This returns messages that have the thread_id set
 */
export function GetThreadMessages(threadID: string, userID: string): $CancellablePromise<db$0.Message[]> {
    return $Call.ByID(3110997449, threadID, userID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListThreadsByTopic lists all threads for a given topic
 */
export function ListThreadsByTopic(req: $models.ListThreadsRequest): $CancellablePromise<$models.ThreadInfo[]> {
    return $Call.ByID(391066348, req).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpdateThreadLastActive updates the last active time of a thread
 */
export function UpdateThreadLastActive(threadID: string, userID: string): $CancellablePromise<void> {
    return $Call.ByID(1073717100, threadID, userID);
}

/**
 * UpdateThreadStatus updates the status of a thread
 */
export function UpdateThreadStatus(threadID: string, userID: string, status: $models.ThreadStatus): $CancellablePromise<void> {
    return $Call.ByID(1752417880, threadID, userID, status);
}

// Private type creation functions
const $$createType0 = $models.CreateThreadResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ThreadInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = db$0.Message.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($$createType2);
