// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VectorSearchService handles vector search operations using chromem
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as chromem$0 from "../../pkg/chromem/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddChunks adds chunks with embeddings to the vector database
 */
export function AddChunks(userID: string, chunks: $models.ChunkData[]): $CancellablePromise<void> {
    return $Call.ByID(905471236, userID, chunks);
}

/**
 * Close closes the vector database
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(4056678341);
}

/**
 * DeleteChunks deletes chunks from the vector database
 */
export function DeleteChunks(userID: string, chunkIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(1656762454, userID, chunkIDs);
}

/**
 * DeleteChunksByFileID deletes all chunks for a specific file
 */
export function DeleteChunksByFileID(userID: string, fileID: string): $CancellablePromise<void> {
    return $Call.ByID(423798180, userID, fileID);
}

/**
 * GetChromemDB returns the underlying chromem database instance
 * This is used by FileProcessorService for RAG processing
 */
export function GetChromemDB(): $CancellablePromise<chromem$0.DB | null> {
    return $Call.ByID(343570764).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStats returns statistics about the vector database
 */
export function GetStats(userID: string): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(2926512952, userID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetUserCollection gets or creates a collection for a user
 */
export function GetUserCollection(userID: string): $CancellablePromise<chromem$0.Collection | null> {
    return $Call.ByID(2975725854, userID).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SemanticSearch performs semantic search on chunks
 */
export function SemanticSearch(userID: string, query: string, fileIDs: string[], limit: number): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(3829428111, userID, query, fileIDs, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * SemanticSearchMultipleFiles performs semantic search across multiple files
 */
export function SemanticSearchMultipleFiles(userID: string, query: string, fileIDs: string[], limit: number): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(3120119170, userID, query, fileIDs, limit).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = chromem$0.DB.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = chromem$0.Collection.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.SearchResult.createFrom;
const $$createType6 = $Create.Array($$createType5);
