// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WalletService handles local wallet management using jarvis/accounts
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoClaimTrialIfNeeded checks if user needs to claim trial and claims it automatically
 * This should be called after successful wallet unlock
 * Returns: (claimed bool, usdtAmount float64, kawaiAmount string, error)
 */
export function AutoClaimTrialIfNeeded(referralCode: string): $CancellablePromise<[boolean, number, string]> {
    return $Call.ByID(2949526248, referralCode);
}

/**
 * CreateWallet creates a new wallet (supports multiple wallets)
 */
export function CreateWallet(password: string, mnemonic: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(3156236324, password, mnemonic, description);
}

/**
 * DeleteWallet removes a wallet from storage
 */
export function DeleteWallet(address: string): $CancellablePromise<void> {
    return $Call.ByID(3346398499, address);
}

/**
 * ExportKeystore returns the keystore JSON content for a wallet
 */
export function ExportKeystore(address: string): $CancellablePromise<string> {
    return $Call.ByID(2188264459, address);
}

/**
 * GenerateMnemonic creates a new 12-word bip39 mnemonic
 */
export function GenerateMnemonic(): $CancellablePromise<string> {
    return $Call.ByID(4204644906);
}

/**
 * GetAPIKey returns the API key for the current wallet (generating one if needed)
 */
export function GetAPIKey(): $CancellablePromise<string> {
    return $Call.ByID(1840933700);
}

/**
 * GetCurrentAddress returns the current active wallet address
 */
export function GetCurrentAddress(): $CancellablePromise<string> {
    return $Call.ByID(1124137400);
}

/**
 * GetStatus returns the current wallet status
 */
export function GetStatus(): $CancellablePromise<$models.WalletStatus> {
    return $Call.ByID(914601537).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetWallets returns a list of all stored wallets
 */
export function GetWallets(): $CancellablePromise<$models.WalletInfo[]> {
    return $Call.ByID(3479245187).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * HasWallet checks if a wallet already exists
 */
export function HasWallet(): $CancellablePromise<boolean> {
    return $Call.ByID(1864518230);
}

/**
 * ImportKeystore imports a keystore from JSON content
 */
export function ImportKeystore(keystoreJSON: string, password: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(3547868716, keystoreJSON, password, description);
}

/**
 * ImportPrivateKey imports a wallet from a private key
 */
export function ImportPrivateKey(privateKeyHex: string, password: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(1034386550, privateKeyHex, password, description);
}

/**
 * LockWallet clears the private key from memory
 */
export function LockWallet(): $CancellablePromise<void> {
    return $Call.ByID(468559547);
}

/**
 * SetupWallet creates a new keystore from a password and mnemonic (first wallet only)
 */
export function SetupWallet(password: string, mnemonic: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(4273098007, password, mnemonic, name);
}

/**
 * SignMessage signs a message with the private key
 */
export function SignMessage(message: string): $CancellablePromise<string> {
    return $Call.ByID(1296718787, message);
}

/**
 * SwitchWallet switches to a different wallet by address
 */
export function SwitchWallet(address: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(3633929328, address, password);
}

/**
 * UnlockWallet decrypts the keystore and loads it into memory
 */
export function UnlockWallet(password: string): $CancellablePromise<string> {
    return $Call.ByID(3504105564, password);
}

/**
 * UpdateWalletDescription updates the description of a wallet
 */
export function UpdateWalletDescription(address: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(2292003669, address, description);
}

// Private type creation functions
const $$createType0 = $models.WalletStatus.createFrom;
const $$createType1 = $models.WalletInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
