// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Message represents a message in a conversation.
 */
export class Message {
    "role": Role;
    "content": Part[];

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("role" in $$source)) {
            this["role"] = Role.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField1_0($$parsedSource["content"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * Part represents a part of a message content.
 */
export type Part = any;

/**
 * Role represents the role of a message sender.
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleSystem = "system",
    RoleUser = "user",
    RoleAssistant = "assistant",
    RoleTool = "tool",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
