// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides local file system operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EditFile performs search and replace in a file
 */
export function EditFile(params: $models.EditLocalFileParams): $CancellablePromise<$models.EditLocalFileResult | null> {
    return $Call.ByID(200051221, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetCommandOutput gets output from a running command
 */
export function GetCommandOutput(params: $models.GetCommandOutputParams): $CancellablePromise<$models.GetCommandOutputResult | null> {
    return $Call.ByID(847401159, params).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GlobFiles searches for files using glob patterns
 */
export function GlobFiles(params: $models.GlobFilesParams): $CancellablePromise<$models.GlobFilesResult | null> {
    return $Call.ByID(3594572644, params).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GrepContent searches for content in files using grep-like functionality
 */
export function GrepContent(params: $models.GrepContentParams): $CancellablePromise<$models.GrepContentResult | null> {
    return $Call.ByID(4166207212, params).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * KillCommand kills a running command
 */
export function KillCommand(params: $models.KillCommandParams): $CancellablePromise<$models.KillCommandResult | null> {
    return $Call.ByID(2966117492, params).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListFiles lists files in a directory
 */
export function ListFiles(params: $models.ListLocalFileParams): $CancellablePromise<$models.LocalFileItem[]> {
    return $Call.ByID(1080438982, params).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * MoveFiles moves multiple files
 */
export function MoveFiles(params: $models.MoveLocalFilesParams): $CancellablePromise<$models.LocalMoveFilesResultItem[]> {
    return $Call.ByID(2218991233, params).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * OpenFile opens a file with the default application
 */
export function OpenFile(params: $models.OpenLocalFileParams): $CancellablePromise<void> {
    return $Call.ByID(381746933, params);
}

/**
 * OpenFileOrFolder opens a file or folder based on the type
 */
export function OpenFileOrFolder(path: string, isDirectory: boolean): $CancellablePromise<void> {
    return $Call.ByID(3361896896, path, isDirectory);
}

/**
 * OpenFolder opens a folder with the default file manager
 */
export function OpenFolder(params: $models.OpenLocalFolderParams): $CancellablePromise<void> {
    return $Call.ByID(428220031, params);
}

/**
 * ReadFile reads a file with optional line range
 */
export function ReadFile(params: $models.LocalReadFileParams): $CancellablePromise<$models.LocalReadFileResult | null> {
    return $Call.ByID(4238919093, params).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ReadFiles reads multiple files
 */
export function ReadFiles(params: $models.LocalReadFilesParams): $CancellablePromise<($models.LocalReadFileResult | null)[]> {
    return $Call.ByID(2209306290, params).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * RenameFile renames a file
 */
export function RenameFile(params: $models.RenameLocalFileParams): $CancellablePromise<$models.RenameLocalFileResult | null> {
    return $Call.ByID(3061543947, params).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * RunCommand runs a shell command
 */
export function RunCommand(params: $models.RunCommandParams): $CancellablePromise<$models.RunCommandResult | null> {
    return $Call.ByID(438907449, params).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * SearchFiles searches for files by keywords
 */
export function SearchFiles(params: $models.LocalSearchFilesParams): $CancellablePromise<$models.LocalFileItem[]> {
    return $Call.ByID(3648913902, params).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * WriteFile writes content to a file
 */
export function WriteFile(params: $models.WriteLocalFileParams): $CancellablePromise<$models.WriteFileResult | null> {
    return $Call.ByID(1225369148, params).then(($result: any) => {
        return $$createType22($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EditLocalFileResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GetCommandOutputResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GlobFilesResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GrepContentResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.KillCommandResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.LocalFileItem.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.LocalMoveFilesResultItem.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.LocalReadFileResult.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.RenameLocalFileResult.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.RunCommandResult.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $models.WriteFileResult.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
