// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CrawlErrorResult represents a failed crawl result
 */
export class CrawlErrorResult {
    "errorMessage": string;
    "errorType": string;
    "url": string;

    /** Creates a new CrawlErrorResult instance. */
    constructor($$source: Partial<CrawlErrorResult> = {}) {
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = "";
        }
        if (!("errorType" in $$source)) {
            this["errorType"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrawlErrorResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CrawlErrorResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CrawlErrorResult($$parsedSource as Partial<CrawlErrorResult>);
    }
}

/**
 * CrawlImplType represents the type of crawler implementation
 */
export enum CrawlImplType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CrawlImplJina = "jina",
    CrawlImplNaive = "naive",
    CrawlImplBrowserless = "browserless",
};

/**
 * CrawlPagesRequest represents a request to crawl multiple pages
 */
export class CrawlPagesRequest {
    "urls": string[];
    "impls"?: CrawlImplType[];

    /** Creates a new CrawlPagesRequest instance. */
    constructor($$source: Partial<CrawlPagesRequest> = {}) {
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrawlPagesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CrawlPagesRequest {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField0_0($$parsedSource["urls"]);
        }
        if ("impls" in $$parsedSource) {
            $$parsedSource["impls"] = $$createField1_0($$parsedSource["impls"]);
        }
        return new CrawlPagesRequest($$parsedSource as Partial<CrawlPagesRequest>);
    }
}

/**
 * CrawlPagesResponse represents the response from crawling multiple pages
 */
export class CrawlPagesResponse {
    "results": CrawlResult[];

    /** Creates a new CrawlPagesResponse instance. */
    constructor($$source: Partial<CrawlPagesResponse> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrawlPagesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CrawlPagesResponse {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new CrawlPagesResponse($$parsedSource as Partial<CrawlPagesResponse>);
    }
}

/**
 * CrawlResult is a union type for crawl results
 */
export class CrawlResult {
    "success"?: CrawlSuccessResult | null;
    "error"?: CrawlErrorResult | null;

    /** Creates a new CrawlResult instance. */
    constructor($$source: Partial<CrawlResult> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrawlResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CrawlResult {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("success" in $$parsedSource) {
            $$parsedSource["success"] = $$createField0_0($$parsedSource["success"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new CrawlResult($$parsedSource as Partial<CrawlResult>);
    }
}

/**
 * CrawlSuccessResult represents a successful crawl result
 */
export class CrawlSuccessResult {
    "title": string;
    "content": string;
    "url": string;
    "website": string;

    /**
     * "jina" or "kawai" (naive)
     */
    "crawler": string;

    /** Creates a new CrawlSuccessResult instance. */
    constructor($$source: Partial<CrawlSuccessResult> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("website" in $$source)) {
            this["website"] = "";
        }
        if (!("crawler" in $$source)) {
            this["crawler"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CrawlSuccessResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CrawlSuccessResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CrawlSuccessResult($$parsedSource as Partial<CrawlSuccessResult>);
    }
}

/**
 * SearchParams represents optional search parameters
 */
export class SearchParams {
    "searchCategories"?: string[];
    "searchEngines"?: string[];
    "searchTimeRange"?: string;

    /** Creates a new SearchParams instance. */
    constructor($$source: Partial<SearchParams> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchParams {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("searchCategories" in $$parsedSource) {
            $$parsedSource["searchCategories"] = $$createField0_0($$parsedSource["searchCategories"]);
        }
        if ("searchEngines" in $$parsedSource) {
            $$parsedSource["searchEngines"] = $$createField1_0($$parsedSource["searchEngines"]);
        }
        return new SearchParams($$parsedSource as Partial<SearchParams>);
    }
}

/**
 * SearchQuery combines query string with search parameters
 */
export class SearchQuery {
    "query": string;
    "searchCategories"?: string[];
    "searchEngines"?: string[];
    "searchTimeRange"?: string;

    /** Creates a new SearchQuery instance. */
    constructor($$source: Partial<SearchQuery> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchQuery {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("searchCategories" in $$parsedSource) {
            $$parsedSource["searchCategories"] = $$createField1_0($$parsedSource["searchCategories"]);
        }
        if ("searchEngines" in $$parsedSource) {
            $$parsedSource["searchEngines"] = $$createField2_0($$parsedSource["searchEngines"]);
        }
        return new SearchQuery($$parsedSource as Partial<SearchQuery>);
    }
}

/**
 * UniformSearchResponse represents the response from a search query
 */
export class UniformSearchResponse {
    /**
     * milliseconds
     */
    "costTime": number;
    "query": string;
    "resultNumbers": number;
    "results": UniformSearchResult[];

    /** Creates a new UniformSearchResponse instance. */
    constructor($$source: Partial<UniformSearchResponse> = {}) {
        if (!("costTime" in $$source)) {
            this["costTime"] = 0;
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("resultNumbers" in $$source)) {
            this["resultNumbers"] = 0;
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UniformSearchResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UniformSearchResponse {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        return new UniformSearchResponse($$parsedSource as Partial<UniformSearchResponse>);
    }
}

/**
 * UniformSearchResult represents a single search result
 */
export class UniformSearchResult {
    "category"?: string;
    "content": string;
    "engines": string[];
    "iframeSrc"?: string;
    "imgSrc"?: string;
    "parsedUrl": string;
    "publishedDate"?: string;
    "score": number;
    "thumbnail"?: string;
    "title": string;
    "url": string;

    /** Creates a new UniformSearchResult instance. */
    constructor($$source: Partial<UniformSearchResult> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("engines" in $$source)) {
            this["engines"] = [];
        }
        if (!("parsedUrl" in $$source)) {
            this["parsedUrl"] = "";
        }
        if (!("score" in $$source)) {
            this["score"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UniformSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UniformSearchResult {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("engines" in $$parsedSource) {
            $$parsedSource["engines"] = $$createField2_0($$parsedSource["engines"]);
        }
        return new UniformSearchResult($$parsedSource as Partial<UniformSearchResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = CrawlResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = CrawlSuccessResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = CrawlErrorResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = UniformSearchResult.createFrom;
const $$createType9 = $Create.Array($$createType8);
