// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides search and crawl functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CrawlPages crawls multiple URLs concurrently
 * @param {$models.CrawlPagesRequest} req
 * @returns {$CancellablePromise<$models.CrawlPagesResponse | null>}
 */
export function CrawlPages(req) {
    return $Call.ByID(859859617, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Query performs a search query using the configured provider
 * @param {string} query
 * @param {$models.SearchParams | null} params
 * @returns {$CancellablePromise<$models.UniformSearchResponse | null>}
 */
export function Query(query, params) {
    return $Call.ByID(2892717164, query, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * WebSearch performs a web search with retry logic
 * @param {$models.SearchQuery} query
 * @returns {$CancellablePromise<$models.UniformSearchResponse | null>}
 */
export function WebSearch(query) {
    return $Call.ByID(2733580510, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CrawlPagesResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $0.UniformSearchResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
