// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UserBalanceInfo represents user balance data formatted for UI display
 */
export class UserBalanceInfo {
    "address": string;

    /**
     * Formatted (e.g., "5.00")
     */
    "usdt_balance": string;

    /**
     * Raw micro USDT value
     */
    "usdt_micro": string;

    /**
     * In wei
     */
    "kawai_balance": string;
    "trial_claimed": boolean;

    /**
     * Empty if no referrer
     */
    "referrer_address": string;
    "has_referrer": boolean;

    /** Creates a new UserBalanceInfo instance. */
    constructor($$source: Partial<UserBalanceInfo> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("usdt_balance" in $$source)) {
            this["usdt_balance"] = "";
        }
        if (!("usdt_micro" in $$source)) {
            this["usdt_micro"] = "";
        }
        if (!("kawai_balance" in $$source)) {
            this["kawai_balance"] = "";
        }
        if (!("trial_claimed" in $$source)) {
            this["trial_claimed"] = false;
        }
        if (!("referrer_address" in $$source)) {
            this["referrer_address"] = "";
        }
        if (!("has_referrer" in $$source)) {
            this["has_referrer"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserBalanceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UserBalanceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserBalanceInfo($$parsedSource as Partial<UserBalanceInfo>);
    }
}

/**
 * WalletInfo represents a wallet in the list
 */
export class WalletInfo {
    "address": string;
    "description": string;
    "isActive": boolean;

    /** Creates a new WalletInfo instance. */
    constructor($$source: Partial<WalletInfo> = {}) {
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("isActive" in $$source)) {
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WalletInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WalletInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WalletInfo($$parsedSource as Partial<WalletInfo>);
    }
}

/**
 * WalletStatus represents the current state of the wallet
 */
export class WalletStatus {
    "hasWallet": boolean;
    "isLocked": boolean;
    "address": string;
    "wallets": WalletInfo[];

    /** Creates a new WalletStatus instance. */
    constructor($$source: Partial<WalletStatus> = {}) {
        if (!("hasWallet" in $$source)) {
            this["hasWallet"] = false;
        }
        if (!("isLocked" in $$source)) {
            this["isLocked"] = false;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("wallets" in $$source)) {
            this["wallets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WalletStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): WalletStatus {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wallets" in $$parsedSource) {
            $$parsedSource["wallets"] = $$createField3_0($$parsedSource["wallets"]);
        }
        return new WalletStatus($$parsedSource as Partial<WalletStatus>);
    }
}

// Private type creation functions
const $$createType0 = WalletInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
