// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WalletService handles local wallet management using jarvis/accounts
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoClaimTrialIfNeeded checks if user needs to claim trial and claims it automatically
 * This should be called after successful wallet unlock
 * Returns: (claimed bool, usdtAmount float64, kawaiAmount string, error)
 */
export function AutoClaimTrialIfNeeded(referralCode: string): $CancellablePromise<[boolean, number, string]> {
    return $Call.ByID(1068878584, referralCode);
}

/**
 * CreateWallet creates a new wallet (supports multiple wallets)
 */
export function CreateWallet(password: string, mnemonic: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(4169369396, password, mnemonic, description);
}

/**
 * DeleteWallet removes a wallet from storage
 */
export function DeleteWallet(address: string): $CancellablePromise<void> {
    return $Call.ByID(1975928467, address);
}

/**
 * ExportKeystore returns the keystore JSON content for a wallet
 */
export function ExportKeystore(address: string): $CancellablePromise<string> {
    return $Call.ByID(1147849243, address);
}

/**
 * GenerateMnemonic creates a new 12-word bip39 mnemonic
 */
export function GenerateMnemonic(): $CancellablePromise<string> {
    return $Call.ByID(2275811770);
}

/**
 * GetAPIKey returns the API key for the current wallet (generating one if needed)
 */
export function GetAPIKey(): $CancellablePromise<string> {
    return $Call.ByID(1946461076);
}

/**
 * GetCurrentAccountAddress returns the current account address if unlocked
 */
export function GetCurrentAccountAddress(): $CancellablePromise<string> {
    return $Call.ByID(707392469);
}

/**
 * GetCurrentAddress returns the current active wallet address
 */
export function GetCurrentAddress(): $CancellablePromise<string> {
    return $Call.ByID(2878401512);
}

/**
 * GetStatus returns the current wallet status
 */
export function GetStatus(): $CancellablePromise<$models.WalletStatus> {
    return $Call.ByID(3424115057).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetUserBalanceInfo retrieves and formats user balance for UI display
 * Returns nil if no wallet is active or kvstore is not available
 */
export function GetUserBalanceInfo(): $CancellablePromise<$models.UserBalanceInfo | null> {
    return $Call.ByID(1283850420).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetWallets returns a list of all stored wallets
 */
export function GetWallets(): $CancellablePromise<$models.WalletInfo[]> {
    return $Call.ByID(4283798419).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * HasWallet checks if a wallet already exists
 */
export function HasWallet(): $CancellablePromise<boolean> {
    return $Call.ByID(3931158054);
}

/**
 * ImportKeystore imports a keystore from JSON content
 */
export function ImportKeystore(keystoreJSON: string, password: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(144912988, keystoreJSON, password, description);
}

/**
 * ImportPrivateKey imports a wallet from a private key
 */
export function ImportPrivateKey(privateKeyHex: string, password: string, description: string): $CancellablePromise<string> {
    return $Call.ByID(1357053446, privateKeyHex, password, description);
}

/**
 * IsUnlocked returns true if the wallet is currently unlocked
 */
export function IsUnlocked(): $CancellablePromise<boolean> {
    return $Call.ByID(4056850556);
}

/**
 * LockWallet clears the private key from memory
 */
export function LockWallet(): $CancellablePromise<void> {
    return $Call.ByID(3301395339);
}

/**
 * SetupWallet creates a new keystore from a password and mnemonic (first wallet only)
 */
export function SetupWallet(password: string, mnemonic: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(2717630663, password, mnemonic, name);
}

/**
 * SignMessage signs a message with the private key
 */
export function SignMessage(message: string): $CancellablePromise<string> {
    return $Call.ByID(111912659, message);
}

/**
 * SwitchWallet switches to a different wallet by address
 */
export function SwitchWallet(address: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(1462909024, address, password);
}

/**
 * UnlockWallet decrypts the keystore and loads it into memory
 */
export function UnlockWallet(password: string): $CancellablePromise<string> {
    return $Call.ByID(4230168652, password);
}

/**
 * UpdateWalletDescription updates the description of a wallet
 */
export function UpdateWalletDescription(address: string, description: string): $CancellablePromise<void> {
    return $Call.ByID(4016685477, address, description);
}

// Private type creation functions
const $$createType0 = $models.WalletStatus.createFrom;
const $$createType1 = $models.UserBalanceInfo.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $models.WalletInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
