// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ContextEngineeringRequest represents the request payload for context engineering
 */
export class ContextEngineeringRequest {
    "messages": Message[];
    "tools"?: string[];
    "model": string;
    "provider": string;
    "systemRole"?: string;
    "inputTemplate"?: string;
    "enableHistoryCount"?: boolean;
    "historyCount"?: number;
    "historySummary"?: string;
    "sessionId"?: string;
    "isWelcomeQuestion"?: boolean;
    "variables"?: { [_: string]: any };

    /** Creates a new ContextEngineeringRequest instance. */
    constructor($$source: Partial<ContextEngineeringRequest> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextEngineeringRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextEngineeringRequest {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField1_0($$parsedSource["tools"]);
        }
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField11_0($$parsedSource["variables"]);
        }
        return new ContextEngineeringRequest($$parsedSource as Partial<ContextEngineeringRequest>);
    }
}

/**
 * ContextEngineeringResponse represents the response from context engineering
 */
export class ContextEngineeringResponse {
    "messages": Message[];
    "error"?: string;

    /** Creates a new ContextEngineeringResponse instance. */
    constructor($$source: Partial<ContextEngineeringResponse> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextEngineeringResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextEngineeringResponse {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new ContextEngineeringResponse($$parsedSource as Partial<ContextEngineeringResponse>);
    }
}

/**
 * Message represents a chat message
 */
export class Message {
    "ID": string;

    /**
     * "user", "assistant", "system", "tool"
     */
    "Role": string;

    /**
     * string or []ContentPart
     */
    "Content": any;
    "CreatedAt": number;
    "UpdatedAt": number;

    /**
     * Additional metadata
     */
    "Meta": { [_: string]: any };

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = 0;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = 0;
        }
        if (!("Meta" in $$source)) {
            this["Meta"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Meta" in $$parsedSource) {
            $$parsedSource["Meta"] = $$createField5_0($$parsedSource["Meta"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

// Private type creation functions
const $$createType0 = Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
