package models

// GetAvailableModels returns all available Stable Diffusion models sorted by resource requirements
// Models are ordered from smallest to largest to ensure fallback logic works correctly
func GetAvailableModels() []ModelSpec {
	return []ModelSpec{
		{
			Name:            "sd-v1-5-q4_0",
			URL:             "https://huggingface.co/second-state/stable-diffusion-v1-5-GGUF/resolve/main/stable-diffusion-v1-5-pruned-emaonly-Q4_0.gguf",
			Filename:        "stable-diffusion-v1-5-pruned-emaonly-Q4_0.gguf",
			Size:            1570,
			MinRAM:          4,
			RecommendedRAM:  8,
			MinVRAM:         2,
			RecommendedVRAM: 4,
			ModelType:       "SD1.5",
			Description:     "Stable Diffusion v1.5 quantized (4-bit) - compact and efficient",
			Quantization:    "q4_0",
		},
		{
			Name:            "sd-v1-5-q8_0",
			URL:             "https://huggingface.co/second-state/stable-diffusion-v1-5-GGUF/resolve/main/stable-diffusion-v1-5-pruned-emaonly-Q8_0.gguf",
			Filename:        "stable-diffusion-v1-5-pruned-emaonly-Q8_0.gguf",
			Size:            1760,
			MinRAM:          4,
			RecommendedRAM:  8,
			MinVRAM:         2,
			RecommendedVRAM: 4,
			ModelType:       "SD1.5",
			Description:     "Stable Diffusion v1.5 quantized (8-bit) - good quality, smaller size",
			Quantization:    "q8_0",
		},
		{
			Name:            "sd-turbo-q8_0",
			URL:             "https://huggingface.co/gpustack/stable-diffusion-v2-1-turbo-GGUF/resolve/main/stable-diffusion-v2-1-turbo-Q8_0.gguf",
			Filename:        "stable-diffusion-v2-1-turbo-Q8_0.gguf",
			Size:            2215,
			MinRAM:          4,
			RecommendedRAM:  6,
			MinVRAM:         2,
			RecommendedVRAM: 4,
			ModelType:       "SD-Turbo",
			Description:     "SD-Turbo v2.1 quantized (8-bit GGUF) - ultra-fast generation, 1-4 steps",
			Quantization:    "q8_0",
		},
		{
			Name:            "sd-v1-5-f16",
			URL:             "https://huggingface.co/second-state/stable-diffusion-v1-5-GGUF/resolve/main/stable-diffusion-v1-5-pruned-emaonly-f16.gguf",
			Filename:        "stable-diffusion-v1-5-pruned-emaonly-f16.gguf",
			Size:            2130,
			MinRAM:          6,
			RecommendedRAM:  12,
			MinVRAM:         4,
			RecommendedVRAM: 6,
			ModelType:       "SD1.5",
			Description:     "Stable Diffusion v1.5 (16-bit) - balanced quality and performance",
			Quantization:    "f16",
		},
		{
			Name:            "sdxl-base-q4_0",
			URL:             "https://huggingface.co/hum-ma/SDXL-models-GGUF/resolve/main/stable-diffusion-xl-base-1.0-Q4_0.gguf",
			Filename:        "stable-diffusion-xl-base-1.0-Q4_0.gguf",
			Size:            1490,
			MinRAM:          8,
			RecommendedRAM:  12,
			MinVRAM:         4,
			RecommendedVRAM: 8,
			ModelType:       "SDXL",
			Description:     "Stable Diffusion XL Base quantized (4-bit) - good quality, manageable size",
			Quantization:    "q4_0",
		},
		{
			Name:            "sdxl-base-q5",
			URL:             "https://huggingface.co/hum-ma/SDXL-models-GGUF/resolve/main/stable-diffusion-xl-base-1.0-Q5_K_M.gguf",
			Filename:        "stable-diffusion-xl-base-1.0-Q5_K_M.gguf",
			Size:            1840,
			MinRAM:          8,
			RecommendedRAM:  12,
			MinVRAM:         4,
			RecommendedVRAM: 8,
			ModelType:       "SDXL",
			Description:     "Stable Diffusion XL Base quantized (5-bit) - higher quality than Q4",
			Quantization:    "q5_k_m",
		},
	}
}
