// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalSystemService provides local file system operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as localfs$0 from "../localfs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EditLocalFile edits a file with search and replace
 */
export function EditLocalFile(filePath: string, oldString: string, newString: string, replaceAll: boolean): $CancellablePromise<$models.EditLocalFileState | null> {
    return $Call.ByID(2969804163, filePath, oldString, newString, replaceAll).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetCommandOutput gets output from a running command
 */
export function GetCommandOutput(shellID: string, filter: string): $CancellablePromise<$models.GetCommandOutputState | null> {
    return $Call.ByID(1131069922, shellID, filter).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GlobFiles searches for files using glob patterns
 */
export function GlobFiles(pattern: string, path: string): $CancellablePromise<$models.GlobFilesState | null> {
    return $Call.ByID(647175551, pattern, path).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GrepContent searches for content in files
 */
export function GrepContent(params: localfs$0.GrepContentParams): $CancellablePromise<$models.GrepContentState | null> {
    return $Call.ByID(427143387, params).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * KillCommand kills a running command
 */
export function KillCommand(shellID: string): $CancellablePromise<$models.KillCommandState | null> {
    return $Call.ByID(629548231, shellID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListLocalFiles lists files in a directory
 */
export function ListLocalFiles(path: string): $CancellablePromise<$models.LocalFileListState | null> {
    return $Call.ByID(4248751424, path).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * MoveLocalFiles moves multiple files
 */
export function MoveLocalFiles(items: localfs$0.MoveLocalFileParams[]): $CancellablePromise<$models.LocalMoveFilesState | null> {
    return $Call.ByID(4001594497, items).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ReadLocalFile reads content from a file
 */
export function ReadLocalFile(path: string, loc: number[]): $CancellablePromise<$models.LocalReadFileState | null> {
    return $Call.ByID(1762131543, path, loc).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ReadLocalFiles reads multiple files
 */
export function ReadLocalFiles(paths: string[]): $CancellablePromise<$models.LocalReadFilesState | null> {
    return $Call.ByID(2073367212, paths).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * RenameLocalFile renames a file or directory
 */
export function RenameLocalFile(path: string, newName: string): $CancellablePromise<$models.LocalRenameFileState | null> {
    return $Call.ByID(2769779513, path, newName).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * RunCommand runs a shell command
 */
export function RunCommand(command: string, description: string, runInBackground: boolean, timeout: number): $CancellablePromise<$models.RunCommandState | null> {
    return $Call.ByID(1432550400, command, description, runInBackground, timeout).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * SearchLocalFiles searches for files matching keywords
 */
export function SearchLocalFiles(keywords: string, directory: string): $CancellablePromise<$models.LocalFileSearchState | null> {
    return $Call.ByID(573412684, keywords, directory).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * WriteLocalFile writes content to a file
 */
export function WriteLocalFile(path: string, content: string): $CancellablePromise<localfs$0.WriteFileResult | null> {
    return $Call.ByID(3894757462, path, content).then(($result: any) => {
        return $$createType25($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EditLocalFileState.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GetCommandOutputState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GlobFilesState.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GrepContentState.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.KillCommandState.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.LocalFileListState.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.LocalMoveFilesState.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.LocalReadFileState.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.LocalReadFilesState.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.LocalRenameFileState.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.RunCommandState.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $models.LocalFileSearchState.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = localfs$0.WriteFileResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
