// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service provides speech-to-text transcription using whisper-cpp CLI
 * This is a Wails-compatible service wrapper around Manager
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Close is a no-op for CLI-based service (kept for interface compatibility)
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(2123239868);
}

/**
 * DownloadModel downloads a Whisper model
 * @param {string} modelName
 * @returns {$CancellablePromise<void>}
 */
export function DownloadModel(modelName) {
    return $Call.ByID(225735077, modelName);
}

/**
 * GetAvailableModels returns a list of models available for download
 * @returns {$CancellablePromise<{ [_: string]: any }[]>}
 */
export function GetAvailableModels() {
    return $Call.ByID(1080073701).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetModelsDirectory returns the path to the models directory
 * @returns {$CancellablePromise<string>}
 */
export function GetModelsDirectory() {
    return $Call.ByID(2447906205);
}

/**
 * GetRecommendedModel returns a recommended model
 * @returns {$CancellablePromise<string>}
 */
export function GetRecommendedModel() {
    return $Call.ByID(3976321756);
}

/**
 * GetVersion returns the whisper-cpp version
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(700932488);
}

/**
 * InstallWhisper installs whisper-cpp (platform-specific)
 * @returns {$CancellablePromise<void>}
 */
export function InstallWhisper() {
    return $Call.ByID(1612841699);
}

/**
 * IsModelDownloaded checks if a model is downloaded
 * @param {string} modelName
 * @returns {$CancellablePromise<boolean>}
 */
export function IsModelDownloaded(modelName) {
    return $Call.ByID(1326043064, modelName);
}

/**
 * IsWhisperInstalled checks if whisper-cpp is installed
 * @returns {$CancellablePromise<boolean>}
 */
export function IsWhisperInstalled() {
    return $Call.ByID(1343405760);
}

/**
 * ListModels returns all installed Whisper models
 * @returns {$CancellablePromise<string[]>}
 */
export function ListModels() {
    return $Call.ByID(344636106).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Transcribe transcribes an audio file to text
 * modelName: the name of the model to use (e.g., "base", "tiny")
 * audioPath: path to the audio file
 * @param {string} modelName
 * @param {string} audioPath
 * @returns {$CancellablePromise<string>}
 */
export function Transcribe(modelName, audioPath) {
    return $Call.ByID(1034032627, modelName, audioPath);
}

/**
 * TranscribeWithOptions transcribes with custom options
 * @param {string} modelName
 * @param {string} audioPath
 * @param {{ [_: string]: any }} options
 * @returns {$CancellablePromise<string>}
 */
export function TranscribeWithOptions(modelName, audioPath, options) {
    return $Call.ByID(1488458335, modelName, audioPath, options);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
