// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2123239868);
}

export function DownloadModel(modelName: string): $CancellablePromise<void> {
    return $Call.ByID(225735077, modelName);
}

export function GetAvailableModels(): $CancellablePromise<string[]> {
    return $Call.ByID(1080073701).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDependencyStatus(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(2632820599).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetFFmpegPath(): $CancellablePromise<string> {
    return $Call.ByID(2171569190);
}

export function GetFFmpegVersion(): $CancellablePromise<string> {
    return $Call.ByID(2192842503);
}

export function GetModelsDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2447906205);
}

export function GetRecommendedModel(): $CancellablePromise<string> {
    return $Call.ByID(3976321756);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(700932488);
}

export function InstallFFmpeg(): $CancellablePromise<void> {
    return $Call.ByID(2674346258);
}

export function InstallWhisper(): $CancellablePromise<void> {
    return $Call.ByID(1612841699);
}

export function IsFFmpegInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(71865805);
}

export function IsModelDownloaded(modelName: string): $CancellablePromise<boolean> {
    return $Call.ByID(1326043064, modelName);
}

export function IsWhisperInstalled(): $CancellablePromise<boolean> {
    return $Call.ByID(1343405760);
}

export function ListModels(): $CancellablePromise<string[]> {
    return $Call.ByID(344636106).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Transcribe(modelName: string, audioPath: string): $CancellablePromise<string> {
    return $Call.ByID(1034032627, modelName, audioPath);
}

export function TranscribeWithOptions(modelName: string, audioPath: string, options: { [_: string]: any }): $CancellablePromise<string> {
    return $Call.ByID(1488458335, modelName, audioPath, options);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
