// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RewardType represents the type of reward being distributed
 */
export enum RewardType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * RewardTypeMining represents mining rewards (KAWAI tokens)
     */
    RewardTypeMining = "mining",

    /**
     * RewardTypeCashback represents deposit cashback rewards (KAWAI tokens)
     */
    RewardTypeCashback = "cashback",

    /**
     * RewardTypeReferral represents referral rewards (KAWAI tokens)
     */
    RewardTypeReferral = "referral",

    /**
     * RewardTypeRevenue represents revenue sharing rewards (stablecoin)
     */
    RewardTypeRevenue = "revenue",
};
