// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Voice represents a TTS voice
 */
export class Voice {
    /**
     * Creates a new Voice instance.
     * @param {Partial<Voice>} [$$source = {}] - The source object to create the Voice.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Language"] = "";
        }
        if (!("Gender" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Gender"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Voice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Voice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Voice(/** @type {Partial<Voice>} */($$parsedSource));
    }
}
