// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TTSService provides text-to-speech using native OS capabilities
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDefaultVoice returns the system default voice
 * @returns {$CancellablePromise<string>}
 */
export function GetDefaultVoice() {
    return $Call.ByID(2874629625);
}

/**
 * GetPlatformInfo returns information about TTS capabilities
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetPlatformInfo() {
    return $Call.ByID(972539031).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetRecommendedVoices returns high-quality voices for common languages
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function GetRecommendedVoices() {
    return $Call.ByID(3934854060).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetVoicesByLanguage returns voices filtered by language code
 * @param {string} langCode
 * @returns {$CancellablePromise<$models.Voice[]>}
 */
export function GetVoicesByLanguage(langCode) {
    return $Call.ByID(1798815532, langCode).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsPlatformSupported returns whether TTS is supported on current platform
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPlatformSupported() {
    return $Call.ByID(3975092979);
}

/**
 * ListVoices returns available TTS voices
 * @returns {$CancellablePromise<$models.Voice[]>}
 */
export function ListVoices() {
    return $Call.ByID(618892183).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Speak converts text to speech using default voice
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function Speak(text) {
    return $Call.ByID(3761971450, text);
}

/**
 * SpeakToAudio generates speech and returns audio data as byte array
 * This is more convenient than SpeakToFile for frontend integration
 * @param {string} text
 * @returns {$CancellablePromise<string>}
 */
export function SpeakToAudio(text) {
    return $Call.ByID(1434654203, text).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * SpeakToAudioWithVoice generates speech with specified voice and returns audio data
 * @param {string} text
 * @param {string} voice
 * @returns {$CancellablePromise<string>}
 */
export function SpeakToAudioWithVoice(text, voice) {
    return $Call.ByID(1116692903, text, voice).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * SpeakToFile saves speech to an audio file
 * @param {string} text
 * @param {string} outputPath
 * @returns {$CancellablePromise<void>}
 */
export function SpeakToFile(text, outputPath) {
    return $Call.ByID(3726559761, text, outputPath);
}

/**
 * SpeakToFileWithVoice saves speech to file with specified voice
 * @param {string} text
 * @param {string} outputPath
 * @param {string} voice
 * @returns {$CancellablePromise<void>}
 */
export function SpeakToFileWithVoice(text, outputPath, voice) {
    return $Call.ByID(1206590681, text, outputPath, voice);
}

/**
 * SpeakWithRate converts text to speech with custom speaking rate
 * @param {string} text
 * @param {number} rate
 * @returns {$CancellablePromise<void>}
 */
export function SpeakWithRate(text, rate) {
    return $Call.ByID(2287117700, text, rate);
}

/**
 * SpeakWithVoice converts text to speech using specified voice
 * @param {string} text
 * @param {string} voice
 * @returns {$CancellablePromise<void>}
 */
export function SpeakWithVoice(text, voice) {
    return $Call.ByID(3218565704, text, voice);
}

/**
 * Stop stops any ongoing speech
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2567653844);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.Voice.createFrom;
const $$createType3 = $Create.Array($$createType2);
